### ISSUE TITLE
Build oracle in fabric 1.4 with golang

### ISSUE THREAD

**Issue by gianfabiopezzolla** [hyperledger/fabric#1513]
Hi there, I'm new with fabric 1.4, I try to understand how can I build an oracle in golang for smart contract, have you some good resources, articles, posts, or practical exemple to start with? thanks

**Comment by denyeart** [comment]
Hello, Github issues are for code issues.
For general questions, please post to the Fabric mailing list: https://lists.hyperledger.org/g/fabric
