### ISSUE TITLE
Purge private data on demand

### ISSUE THREAD

**Issue by denyeart** [hyperledger/fabric#2787]
See background discussion at https://jira.hyperledger.org/browse/FAB-5097.

See agreed upon RFC at https://github.com/hyperledger/fabric-rfcs/blob/main/text/0000-private_data_purge.md.

**Comment by mbwhite** [comment]
Hello,

I tried yesterday the combination of the two Fabric PRs 2477 (Julian's) and 3448 (mine). I tested this with an updated Gateway application and chaincode from the Fabric Samples (PR 769) .  Functionally everything connected and worked. There was a 20 second delay on the purge which I understand is awaiting the purge commit story.

Fabric peer PRs
https://github.com/hyperledger/fabric/pull/3477 Transaction Simulator
https://github.com/hyperledger/fabric/pull/3448 Chaincode Handler (requires PR 3477)

Chaincode PRs
Node -> https://github.com/hyperledger/fabric-chaincode-node/pull/313
Java -> https://github.com/hyperledger/fabric-chaincode-java/pull/243
Go -> https://github.com/hyperledger/fabric-chaincode-go/pull/45

Samples
Started updating the PrivateData example https://github.com/hyperledger/fabric-samples/pull/769  (more to do here)
