### ISSUE TITLE
Fix implicit collection endorsement policy when passed to discovery code

### ISSUE THREAD

**Issue by manish-sethi** [hyperledger/fabric#2798]
Thanks @andrew-coleman for adding the integration test. 

One more point - I am not sure what was the motivation but it appears that we also allow the implicit collection policy to be [configured via channel config](https://github.com/hyperledger/fabric/blob/240cf0e182938a09832ba4162c3c229c81848e3f/core/chaincode/lifecycle/deployedcc_infoprovider.go#L266).

I feel that moving the existing code in a separate function and invoking that function from both the existing code and your code may allow to keep this important logic at one place.

_Originally posted by @manish-sethi in https://github.com/hyperledger/fabric/pull/2784#discussion_r677765449_

**Comment by denyeart** [comment]
Replaced by https://github.com/hyperledger/fabric-gateway/issues/347

**Comment by denyeart** [comment]
Replaced with https://github.com/hyperledger/fabric-gateway/issues/347
