### ISSUE TITLE
Certificate expiration/renew documentation

### ISSUE THREAD

**Issue by denyeart** [hyperledger/fabric#2808]
While there is some scattered guidance for dealing with certificate expirations throughout the Fabric docs, we need to pull the information all together and make it more comprehensive so that users have a complete view of the various certificates in Fabric environments and step-by-step guidance for dealing with expired certificates (e.g. user vs node vs TLS certificate expirations).

**Comment by joshhus** [comment]
- Could move existing IBP certs table to Fabric and edit / add client considerations.
- Fabric samples need code for re-enrollment of certs.
- What are the types of certs and their differences. e.g. application ID, user ID, system/service ID ... 
- What are the variables dependent upon the identity service used? e.g. Fabric doesn't require IBM w3, I think IBP does.

**Comment by denyeart** [comment]
We'll use #3195 instead, closing this one.
