### ISSUE TITLE
failed to create or read WAL: failed to open WAL: fileutil: file already locked

### ISSUE THREAD

**Issue by liurenhao** [hyperledger/fabric#2815]
My orderer stopped due to the following error：
![13a4b93cc9a5ea9e621b09481b9051e](https://user-images.githubusercontent.com/11327335/128692390-d7b18e81-e613-4aac-a35c-f65a7354a50d.png)
 When I restarted the orderer, I got a new error
Error creating consenter: failed to restore persisted raft data: failed to create or read WAL: failed to open WAL: fileutil: file already locked。
What should I do to restart the orderer？

**Comment by andycao125** [comment]
I had this problem too, how did you solve it?
