### ISSUE TITLE
Organization User Limit Not Working 

### ISSUE THREAD

**Issue by khizerarshad** [hyperledger/fabric#2846]
I have noticed a strange bug with Hyperledger Fabric's latest release 2.3

The organization's cryptogen files have user limit check, but this check doesn't work exactly. 

`  # "Users"
    # ---------------------------------------------------------------------------
    # Count: The number of user accounts _in addition_ to Admin
    # ---------------------------------------------------------------------------
    Users:
      Count: 2`
      
Only 2 additional users can be in this organization. But I have created more than 10 users.

**Comment by lindluni** [comment]
Looking at `cmd/cryptogen/main.go`, `Users.Count` is not meant to limit the number of users it is used by cryptogen to automatically generate a specific number of default profiles in excess of the admin account: https://github.com/hyperledger/fabric/blob/main/cmd/cryptogen/main.go#L334
