### ISSUE TITLE
require github.com/hyperledger/fabric: version "v2.3.2" invalid: should be v0 or v1, not v2

### ISSUE THREAD

**Issue by CoreyCheung** [hyperledger/fabric#2890]
solution：
vim go.mod
module github.com/hyperledger/fabric/v2
go 1.14
require (...)

**Comment by denyeart** [comment]
@CoreyCheung are you suggesting the same thing as in #2929

**Comment by denyeart** [comment]
I assume this is a duplicate, closing.
