### ISSUE TITLE
Write config blocks synchronously in Orderer

### ISSUE THREAD

**Issue by Alex-duzhichao** [hyperledger/fabric#2908]
https://github.com/hyperledger/fabric/blob/3594a3be1644b20bf028fa22f5609a82dfbf0950/orderer/common/multichannel/blockwriter.go#L168-L176
As above snippet shows, Orderer writes config blocks to ledger asynchronously.

https://github.com/hyperledger/fabric/blob/3594a3be1644b20bf028fa22f5609a82dfbf0950/orderer/common/follower/follower_chain.go#L552-L568
As above snippet shows, follower chain reads blocks from ledger directly.

Assume the config block contains a transaction which remove the node from consenters, the consensus chain will switch to follower chain which reads last config block from ledger directly. 
Because of writing config block asynchronously, follower chain maybe read a stale config block in which the node is still a consenter. So the node will switch back to a consenter again.
This is a unexpected behavior.

**Comment by denyeart** [comment]
Fixed in #2909.
