### ISSUE TITLE
scripts/createChannel.sh: line 40: osnadmin: command not found

### ISSUE THREAD

**Issue by favccxx** [hyperledger/fabric#2922]
I start the fabric network with 2.2 success,  But failed to create channel, for the reason osnadmin command not found.

[root@localhost test-network]# docker ps -a
CONTAINER ID   IMAGE                               COMMAND             CREATED       STATUS       PORTS                                                                                                                                 NAMES
b2b687198a46   hyperledger/fabric-tools:latest     "/bin/bash"         4 hours ago   Up 4 hours                                                                                                                                         cli
751a7424a695   hyperledger/fabric-peer:latest      "peer node start"   4 hours ago   Up 4 hours   0.0.0.0:9051->9051/tcp, :::9051->9051/tcp, 7051/tcp, 0.0.0.0:19051->19051/tcp, :::19051->19051/tcp                                    peer0.org2.example.com
d64f2a4943a9   hyperledger/fabric-orderer:latest   "orderer"           4 hours ago   Up 4 hours   0.0.0.0:7050->7050/tcp, :::7050->7050/tcp, 0.0.0.0:7053->7053/tcp, :::7053->7053/tcp, 0.0.0.0:17050->17050/tcp, :::17050->17050/tcp   orderer.example.com
d717dcb2bb9f   hyperledger/fabric-peer:latest      "peer node start"   4 hours ago   Up 4 hours   0.0.0.0:7051->7051/tcp, :::7051->7051/tcp, 0.0.0.0:17051->17051/tcp, :::17051->17051/tcp                                              peer0.org1.example.com

[root@localhost test-network]# ./network.sh createChannel
Creating channel 'mychannel'.
If network is not up, starting nodes with CLI timeout of '5' tries and CLI delay of '3' seconds and using database 'leveldb 
Generating channel genesis block 'mychannel.block'
/app/fabric/fabric/scripts/fabric-samples/bin/configtxgen
+ configtxgen -profile TwoOrgsApplicationGenesis -outputBlock ./channel-artifacts/mychannel.block -channelID mychannel
2021-09-15 01:12:46.162 PDT [common.tools.configtxgen] main -> INFO 001 Loading configuration
2021-09-15 01:12:46.172 PDT [common.tools.configtxgen.localconfig] completeInitialization -> INFO 002 orderer type: etcdraft
2021-09-15 01:12:46.172 PDT [common.tools.configtxgen.localconfig] completeInitialization -> INFO 003 Orderer.EtcdRaft.Options unset, setting to tick_interval:"500ms" election_tick:10 heartbeat_tick:1 max_inflight_blocks:5 snapshot_interval_size:16777216 
2021-09-15 01:12:46.172 PDT [common.tools.configtxgen.localconfig] Load -> INFO 004 Loaded configuration: /app/fabric/fabric/scripts/fabric-samples/test-network/configtx/configtx.yaml
2021-09-15 01:12:46.173 PDT [common.tools.configtxgen] doOutputBlock -> INFO 005 Generating genesis block
2021-09-15 01:12:46.173 PDT [common.tools.configtxgen] doOutputBlock -> WARN 006 Genesis block does not contain a consortiums group definition.  This block cannot be used for orderer bootstrap.
2021-09-15 01:12:46.174 PDT [common.tools.configtxgen] doOutputBlock -> INFO 007 Writing genesis block
+ res=0
Creating channel mychannel
Using organization 1
+ osnadmin channel join --channelID mychannel --config-block ./channel-artifacts/mychannel.block -o localhost:7053 --ca-file /app/fabric/fabric/scripts/fabric-samples/test-network/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp/tlscacerts/tlsca.example.com-cert.pem --client-cert /app/fabric/fabric/scripts/fabric-samples/test-network/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.crt --client-key /app/fabric/fabric/scripts/fabric-samples/test-network/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.key
+ res=127
+ osnadmin channel join --channelID mychannel --config-block ./channel-artifacts/mychannel.block -o localhost:7053 --ca-file /app/fabric/fabric/scripts/fabric-samples/test-network/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp/tlscacerts/tlsca.example.com-cert.pem --client-cert /app/fabric/fabric/scripts/fabric-samples/test-network/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.crt --client-key /app/fabric/fabric/scripts/fabric-samples/test-network/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.key
+ res=127
+ osnadmin channel join --channelID mychannel --config-block ./channel-artifacts/mychannel.block -o localhost:7053 --ca-file /app/fabric/fabric/scripts/fabric-samples/test-network/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp/tlscacerts/tlsca.example.com-cert.pem --client-cert /app/fabric/fabric/scripts/fabric-samples/test-network/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.crt --client-key /app/fabric/fabric/scripts/fabric-samples/test-network/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.key
+ res=127
+ osnadmin channel join --channelID mychannel --config-block ./channel-artifacts/mychannel.block -o localhost:7053 --ca-file /app/fabric/fabric/scripts/fabric-samples/test-network/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp/tlscacerts/tlsca.example.com-cert.pem --client-cert /app/fabric/fabric/scripts/fabric-samples/test-network/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.crt --client-key /app/fabric/fabric/scripts/fabric-samples/test-network/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.key
+ res=127
scripts/createChannel.sh: line 40: osnadmin: command not found

How can i get the osnadmin command?

**Comment by denali49** [comment]
Hello,

The OSN Admin capabilities were introduced in Fabric 2.3 so you need to be on that version to have visibility to the OSN Admin commands.

I hope this helps.

Chris

**Comment by tkuhrt** [comment]
I did the following steps to get past this issue from `fabric-samples/test-network`:
```
git checkout v2.2.3
./network.sh down && ./network.sh up -ca
./network.sh createChannel
```

**Comment by denyeart** [comment]
Right, samples tagged with v2.2.x releases don't use osnadmin command. More recent samples (main branch) use osnadmin command.
