### ISSUE TITLE
First Chaincode init function gets called for all chaincodes

### ISSUE THREAD

**Issue by wyazdani** [hyperledger/fabric#2928]
Hi, I am facing an issue when I am working with multiple chaincodes I define the in index.js but when I package them through fabric cli the issue I see is that the first chaincode Init function is repeated on the others,. Attaching sample code

Declaring in index.js
```
const FabCar = require('./lib/fabcar');
const FabCar2 = require('./lib/fabcar2');
module.exports.FabCar = FabCar;
module.exports.FabCar2 = FabCar2r;
module.exports.contracts = [FabCar,FabCar2];
```

Then when calling chaincode
```
 ./network.sh deployCC -ccn fabcar -ccv 1 -cci initLedger -ccl javascript -ccp ${CC_SRC_PATH}
./network.sh deployCC -ccn fabcar2 -ccv 1 -cci initSubjects -ccl javascript -ccp ${CC_SRC_PATH}
```

It Throws error
Error: endorsement failure during invoke. response: status:500 message:"error in simulation: transaction returned with failure: Error: You've asked to invoke a function that does not exist: initSubjects" 

Where as this function does exist in fabcar2

**Comment by denali49** [comment]
Hi, 
I think this is a typo in your declarations in index.js 
FabCar2r;
