### ISSUE TITLE
Gateway: closing stale connections to orderer nodes

### ISSUE THREAD

**Issue by andrew-coleman** [hyperledger/fabric#2948]
The gateway registry maintains a grpc connection cache to other endorsing peers and orderers.  Currently, there is no mechanism in place to close these connections to stale peer or orderer nodes, which will cause resource leaks.
This story will implement connection closure and removal of orderers from the gateway registry.
For orderer nodes, it can hook into the config change callback and detect whether an orderer has been removed from a channel.  If it has, it can look to see if that orderer endpoint is used by any channel, and if not, call the necessary cleanup code.

Peer node closure will be handled in a separate user story.

**Comment by denyeart** [comment]
Replaced by https://github.com/hyperledger/fabric-gateway/issues/345
