### ISSUE TITLE
Setting up the development environment documentation is out of date

### ISSUE THREAD

**Issue by davidkel** [hyperledger/fabric#2960]
In devenv.rst the pre-reqs are
```
Setting up the development environment
--------------------------------------

Prerequisites
~~~~~~~~~~~~~

-  `Git client <https://git-scm.com/downloads>`__
-  `Go <https://golang.org/dl/>`__ version 1.15.x
-  `Docker <https://docs.docker.com/get-docker/>`__ version 18.03 or later
-  (macOS) `Xcode Command Line Tools <https://developer.apple.com/downloads/>`__
-  `SoftHSM <https://github.com/opendnssec/SoftHSMv2>`__
-  `jq <https://stedolan.github.io/jq/download/>`__
```

For Go we need to update this to 1.16.7 across main/2.2/2.3 but also mention that building tagged versions may require an older version of Go.

The versions of docker vary between windows/mac/linux (windows/mac have docker desktop versioning) so would need to provide more context here really. 

For Mac, using brew to install pre-reqs could be an issue (I don't know I'm not a mac user) but in the docs it says
```
brew install git go jq softhsm
```
How do you know what version of go or softhsm you are going to install. 

We should restrict people to softhsm 2.5 for now as there are known problems with softhsm 2.6

**Comment by davidkel** [comment]
As a further assistance it might be helpful to also give a ubuntu example of setting the PKCS11 environment variables in order for the build to run

**Comment by denyeart** [comment]
@davidkel I added some clarifications around Go and brew: https://github.com/hyperledger/fabric/pull/2973.

Go ahead with the hsm updates since you've got the most information in that area.

**Comment by justin-themedium** [comment]
@davidkel Thank you for the information about known issues with softhsm2 v2.6.
I tried it with v2.6.1 (by brew install) and suffered on macOS for a while.
Once I installed v2.5, I passed the pkcs11 test during the build.

**Comment by denyeart** [comment]
HSM clarifications added in https://github.com/hyperledger/fabric/pull/2977/ , closing. Thanks @davidkel

**Comment by sousoul** [comment]
> @davidkel Thank you for the information about known issues with softhsm2 v2.6. I tried it with v2.6.1 (by brew install) and suffered on macOS for a while. Once I installed v2.5, I passed the pkcs11 test during the build.

I have installed softhsm v2.5 on macOS, however, I cannot pass e2e test and lifecycle test during build. 
```
There were failures detected in the following suites:
	      e2e ./integration/e2e
	lifecycle ./integration/lifecycle

Ginkgo ran 16 suites in 47m37.809114611s
Test Suite Failed
make: *** [integration-test] Error 1
```
Have you met the same error?
