### ISSUE TITLE
Unix socket for Docker Daemon required for `peer lifecycle chaincode install`?

### ISSUE THREAD

**Issue by cdesch** [hyperledger/fabric#2969]
When running the installation of `chaincode` on HLF `2.2.1` and HLF-CA `1.4.7` on a kubernetes cluster using the container image `hyperledger/fabric-tools:2.2.1`  with the command: 

     peer lifecycle chaincode install resource_types.tar.gz &> pkg.txt

I get the following error:

    Error: chaincode install failed with status: 500 - failed to invoke backing implementation of 'InstallChaincode': could not build chaincode: docker build failed: docker image inspection failed: Get 
    "http://unix.sock/images/dev-peer0-org1-service-resource_types_1-972753cf09d55e2dddfe48aeb77e795d1c28a81c0f04cd0ce3c4e79ad78ec4f379fb4a6a08dbd993d7e81f3364c6aa40cdcfdac582dccb209e8180fdb2e4c295/json": 
    dial unix /var/run/docker.sock: connect: no such file or directory     

This error appears to be because there is no `hostBindMount` to `/var/run` that would have the Unix socket for the docker daemon. Why is the docker daemon required for installing chaincode?

**Comment by cdesch** [comment]
Ah, I just saw this in the docs https://hyperledger-fabric.readthedocs.io/en/release-2.2/deploypeer/peerplan.html#chaincode

**Comment by julian-trustgrid** [comment]
@cdesch @denyeart  I'm encountering this issue as well. What did you do to fix this?

**Comment by qt-wu** [comment]
@cdesch @denyeart  I'm encountering this issue as well. What did you do to fix this?

**Comment by satota2** [comment]
Hello @qt-wu
> @cdesch @denyeart I'm encountering this issue as well. What did you do to fix this?

This problem has already been solved with the introduction of Chaincode as a Service.

For running Fabric in a Kubernetes environment, you should use the Chaincode as a Service feature.
Using this feature should help you avoid the issues you are experiencing with the chaincode installation failure.
You can find the details here:
https://hyperledger-fabric.readthedocs.io/en/latest/cc_service.html

For a Kubernetes-based example using KIND, check out this sample which employs the Chaincode as a Service model.
https://github.com/hyperledger/fabric-samples/tree/main/test-network-k8s

Additionally, Fabric v2.2 and 2.3 are beyond their community maintenance period. I strongly recommend using v2.5 (the latest LTS version) or later, to ensure better support and stability.

**Comment by cdesch** [comment]
thank you @satota2
