### ISSUE TITLE
How can i change the consensus with my own?

### ISSUE THREAD

**Issue by regre1** [hyperledger/fabric#2970]
I've proposed a new consensus based on DAG, and i want to take a try with Fabric.
But it seems that the consensus algorithm can only support raft or kafka. How can i change the consensus with my own?

**Comment by yacovm** [comment]
Look at [this](https://github.com/SmartBFT-Go/fabric/) fork of Fabric that implemented SmartBFT consensus and look at this [paper](https://arxiv.org/abs/2107.06922).
