### ISSUE TITLE
Include the chaincode hash when installing an already existing chaincode

### ISSUE THREAD

**Issue by varadgit** [hyperledger/fabric#2976]
When installing a new chaincode on the peer you do get the package id of the chaincode which is good... this allows customers to use that data to go through the approve/commit steps.

However the issue is when they are reinstalling an existing chaincode there is nothing in the response to indicate the package id(hash). Install in that case returns a message that the chaincode already exists. We should include the package id of the chaincode in the response when it is already installed on the peer.

**Comment by satota2** [comment]
@denyeart I want to take the issue.

**Comment by satota2** [comment]
@denyeart @varadgit
I have recently submitted the following patch and it has been merged.
I think this may have solved this Issue, but is it still not enough?
https://github.com/hyperledger/fabric/commit/cf341ee49aabae95f583add859ac9186e0a42bb4
 
I think another good way is to add a command to calculate the package ID for
the packaged source code (e.g., `peer lifecycle chaincode calulatepackageid`).
If you think this command is also useful, I would like to make the patches, what do you think about the idea?

**Comment by denyeart** [comment]
@satota2 It looks like your PR may satisfy the request from @varadgit 

Note that `peer lifecycle chaincode queryinstalled` already can return the package id for installed chaincodes:
https://hyperledger-fabric.readthedocs.io/en/latest/commands/peerlifecycle.html#peer-lifecycle-chaincode-queryinstalled-example

I guess you are asking about adding a new function to find the package id from a packaged chaincode rather than an installed chaincode. That sounds like a good idea. Here is the code to compute the package id:
https://github.com/hyperledger/fabric/blob/main/core/chaincode/persistence/persistence.go#L147-L148

**Comment by satota2** [comment]
@denyeart  Thank you for your comments and useful information.
 
> I guess you are asking about adding a new function to find the package id from a packaged chaincode rather than an installed chaincode. 

Yes, I'm thinking of adding that function.
 
Although `queryinstalled` returns the package ID for installed chaincodes, I think this new function will be useful in some cases.
For example, the following cases: 
- When multiple chaincode packages with the same label name are installed, it is possible to identify which ID corresponds to which package later.
- To check whether a particular chaincode package is installed or not without installing that package (without executing `chaincode install`).
 
> That sounds like a good idea.

Thanks for agreeing with the idea.
I'm going to implement this function and submit the patches, referring to the code you gave me.

**Comment by satota2** [comment]
@denyeart We may be able to close this Issue. Please let me know if there are any other features that should be added or improved in this issue.

**Comment by denyeart** [comment]
Yes, looks like this is all done, closing.
@varadgit please re-open or open another issue if you think anything else needs to be done in this space.

**Comment by satota2** [comment]
@denyeart
> Yes, looks like this is all done, closing.

Thank you for the confirmation.
I don't seem to have the permission to close this Issue, so could you please close the issue?
