### ISSUE TITLE
Unable to use peer/orderer binaries from windows package

### ISSUE THREAD

**Issue by davidkel** [hyperledger/fabric#2984]
The first issue is that the binaries don't have the '.exe' extension so would be good to package them with the extension.

The other problem is the following code from internal/fileutil.go

```
// SyncDir fsyncs the given dir
func SyncDir(dirPath string) error {
	dir, err := os.Open(dirPath)
	if err != nil {
		return errors.Wrapf(err, "error while opening dir:%s", dirPath)
	}
	if err := dir.Sync(); err != nil {
		dir.Close()
		return errors.Wrapf(err, "error while synching dir:%s", dirPath)
	}
	if err := dir.Close(); err != nil {
		return errors.Wrapf(err, "error while closing dir:%s", dirPath)
	}
	return err
}
```
calling Sync on a dir fails with the error "The handle is invalid." on windows as it isn't valid to perform that action

As a workaround I used the following implementation

```
// SyncDir fsyncs the given dir
func SyncDir(dirPath string) error {
	dir, err := os.Open(dirPath)
	if err != nil {
		return errors.Wrapf(err, "error while opening dir:%s", dirPath)
	}
	if err := dir.Sync(); err != nil {
		if !strings.Contains(err.Error(), "The handle is invalid.") {
			dir.Close()
			return errors.Wrapf(err, "error while synching dir:%s", dirPath)
		}
	}
	if err := dir.Close(); err != nil {
		return errors.Wrapf(err, "error while closing dir:%s", dirPath)
	}
	return err
}
```
But this will only work on english versions of windows probably so a better soln should be done
- detect if the platform is windows ?
- remove this function into 2 separate files and use 
```
//go:build linux
// +build linux
```
to embed the correct file for the correct platform

**Comment by denyeart** [comment]
@davidkel Everything in the Go `os` package is platform agnostic, and I believe that would include File.Sync(). Do you have any idea why it fails?

This utility function has been in main code path for a long time and we haven't heard of issues on Windows from others (I assume somebody has tried Fabric on Windows but I could be wrong). We don't test or claim support for operating systems besides linux, but since the code uses OS agnostic functions everything should work, and if they don't, we'd accept PRs to fix.

**Comment by davidkel** [comment]
@denyeart Go runtime code is agnostic but that doesn't mean you can use the apis for all situations it seems. In the case of Sync, on unix systems you can call fsync on a directory, on windows the Sync call translates to FlushFileBuffers in Go which cannot be invoked on directories according to the win32 api docs. This is why the orderer and peer fail to launch for me as it attempts to create directories which invokes the Sync. Therefore in the fabric code, you can't call the Sync method on a directory handle on windows and windows returns an error message saying the handle is invalid.
I see running fabric natively on windows as a development platform in the same way you might run fabric natively on a mac and that fabric is not supported in any other capacity (eg production) on these platforms (native, via docker or WSL)

I'll be submitting a PR soon to address this. Apart from this issue I am able to run fabric on windows natively with no need for docker at all (using external builders)
