### ISSUE TITLE
Confusing examples on Read-Write set semantics

### ISSUE THREAD

**Issue by gqqnbig** [hyperledger/fabric#3015]
[docs/source/readwrite.rst](https://github.com/hyperledger/fabric/blob/main/docs/source/readwrite.rst) says each read operation has a key and a version. However, the read operations in the last World state example have no version.

Do you like me adding read version to the example? It would be like this:

> World state: (k1,1,v1), (k2,1,v2), (k3,1,v3), (k4,1,v4), (k5,1,v5)
> T1 -> Write(k1, v1'), Write(k2, v2')
> T2 -> Read(k1, v1), Write(k3, v3')
> T3 -> Write(k2, v2'')
> T4 -> Write(k2, v2'''), read(k2, v2)
> T5 -> Write(k6, v6'), read(k5, v4)

T5 will fail because it reads k5 of version 4 but in world state k5 is of version 5, meaning someone has updated k5 before T5 got committed (or validated?).

**Comment by denyeart** [comment]
Let's get input from the author @manish-sethi

**Comment by manish-sethi** [comment]
It is implicit that the version in a `read` operation is same what is written by the most recent transaction on the key. This example shows that given the initial world-state and a sequence of transactions, how these transactions will behave during validation.

I am fine if you want to add versions in the reads explicitly but what you have in the suggested change, is not correct. E.g., T5 has `read(k5, v4)` when the version in the world state is (k5,1,v5) on which T5 was simulated.

**Comment by gqqnbig** [comment]
@manish-sethi 

The reason that I wrote "T5 -> Write(k6, v6'), read(k5, **v4**)" is to show the importance of the read version. As the article previously said, read version is used for validation, is essential, and cannot be removed.

With "T5 -> Write(k6, v6'), read(k5, **v4**)", we show readers how a transaction is rejected due to wrong read version. Otherwise the current example does not cover read version.

I admit I missed the sentence "T1, T2, T3, T4, and T5, all simulated on the same snapshot of the world state."

**Comment by manish-sethi** [comment]
> With "T5 -> Write(k6, v6'), read(k5, **v4**)", we show readers how a transaction is rejected due to wrong read version. Otherwise the current example does not cover read version.
> 
This is covered in the current example... see the sentence `T2 fails validation because it reads a key, k1, which was modified by a preceding transaction - T1`

**Comment by gqqnbig** [comment]
Agree. But it is not rejected due to literally read version. Since "modified by a preceding transaction" is implemented as a version increment, why don't we show it in the example clearly?

The current example implicitly declares and modifies read version. My point is we can make it explicit.

**Comment by manish-sethi** [comment]
> But it is not rejected due to literally read version

Not sure what you mean here. It is clearly rejected because the version that `T2` read during simulation is changed by `T1` before `T2` get committed.

I have one suggestion if you think that it would make the example clearer. 

Add the versions to the reads (which would all be the same as in the initial world-state). Moreover, after commit of each of the transactions (T1, T2, ...T5), we could show the new world-state this would show how the version in the world state has changed since the simulation of a transaction and hence the rejection.

**Comment by gqqnbig** [comment]
See if you guys are happy with the following revision. If yes, I will make a PR.


Now, consider a set of five transactions ``T1, T2, T3, T4, and T5``, all
simulated on the same snapshot of the world state. The following snippet
shows the snapshot of the world state against which the transactions are
simulated and the sequence of read and write activities performed by
each of these transactions.

.. code-block:: none

    World state: (k1,1,v1), (k2,1,v2), (k3,1,v3), (k4,1,v4), (k5,1,v5)
    T1 -> Write(k1, v1'), Write(k2, v2')
    T2 -> Read(k1,1), Write(k3, v3')
    T3 -> Write(k2, v2'')
    T4 -> Write(k2, v2'''), read(k2,1)
    T5 -> Write(k6, v6'), read(k5,1)

Now, assume that these transactions are ordered in the sequence of
T1,..,T5 (could be contained in a single block or different blocks)

1. ``T1`` passes validation because it does not perform any read.
   Further, the tuple of keys ``k1`` and ``k2`` in the world state are
   updated to ``(k1,2,v1'), (k2,2,v2')``

2. ``T2`` fails validation because it reads key ``k1`` of version 1 but ``k1`` in the world state has progressed to version 2.

3. ``T3`` passes the validation because it does not perform a read.
   Further the tuple of the key, ``k2``, in the world state is updated
   to ``(k2,3,v2'')``

4. ``T4`` fails the validation because it reads key ``k2`` of version 1 but ``k2`` in the world state has progressed to version 2.

5. ``T5`` passes validation because it reads a key, ``k5``, which is still on version 1.

**Comment by manish-sethi** [comment]
You have referred to versions as `1, 2` in your text. In the example the versions are referred to as `V1, V2,...` and when a version is updated it's referred to as `v1', V2',...`.

If you read the first paragraph in this example, a tuple in the world-state is in the form `(key, value, version)`

**Comment by gqqnbig** [comment]
Well, no. Section Example simulation and validation says the world state is represented by a tuple **(k,ver,val)** where ver is the latest version of the key k having val as its value.

**Comment by manish-sethi** [comment]
Sorry, my mistake. Yes, you are right. I misread my own text :-). Please go ahead with your changes. Just fix one error in your text...

`T4 fails the validation because it reads key k2 of version 1 but k2 in the world state has progressed to version 2.` -> ....progressed to **version 3**

**Comment by gqqnbig** [comment]
@manish-sethi I made a PR. Can you help review?
