### ISSUE TITLE
How can I join orderers from two organisations?

### ISSUE THREAD

**Issue by luismcortestirado** [hyperledger/fabric#3018]
Good morning, I have an issue with Minifabric and I need to be able to resolve it.
I have the following infrastructure generated on two different computers:

--> Computer 1:

    CA: "ca01.domain01.net"
    Peer 1: "peer01.org01.domain01.net".
    Peer 2: "peer02.org01.domain01.net"
    Orderer: "ord-fabric01.domain01.net"

--> Computer 2:

    CA: "ca01.domain02.es"
    Peer 1: "peer01.org02.domain02.es"
    Peer 2: "peer02.org02.domain02.es"
    Orderer: "ord-fabric01.domain02.es"

I have joined both organisations by following tutorials such as the following:

    https://www.youtube.com/watch?v=c1Ab57IrgZg
    https://github.com/hyperledger-labs/minifabric/blob/main/docs/AddNewOrganization.md

When I finish, both organisations are joined correctly, but I start the "Hyperledger Explorer" tool and only the orderer of the first organisation appears and I need both orderers to appear.
How can I make both orderers join the same channel? Thank you for your time and dedication.

**Comment by luismcortestirado** [comment]
????????????????????????????????????

**Comment by denyeart** [comment]
Closing - Fabric issues are meant for Fabric code issues.

Please open against https://github.com/hyperledger-labs/minifabric or utilize community support such as rocketchat https://chat.hyperledger.org/channel/fabric-questions or mailing list.
