### ISSUE TITLE
Add new function in chaincode shim

### ISSUE THREAD

**Issue by manish-sethi** [hyperledger/fabric#3020]
Add new function in chaincode shim - PurgePrivateData(collection, key string) error

**Comment by mbwhite** [comment]
Related Stories
- [x] Add in the field for the new API into the protos code
- [x] Add in the Fabric side - shim handler to accepts this request
      - https://github.com/hyperledger/fabric/pull/3448/
- [x] Node Chaincode Implementation
     - https://github.com/hyperledger/fabric-chaincode-node/pull/313
- [x] Java Chaincode Implementation
     - https://github.com/hyperledger/fabric-chaincode-java/pull/250
- [x] Go Chaincode Implementation
     - https://github.com/hyperledger/fabric-chaincode-go/pull/45
- [x] System test
     - Tests added per PRs above.

**Comment by fraVlaca** [comment]
@mbwhite think you can link (https://github.com/hyperledger/fabric-chaincode-node/pull/313) for the node api and https://github.com/hyperledger/fabric-chaincode-go/pull/55  for the node one and tick them off

**Comment by denyeart** [comment]
@mbwhite In the task list above the link to Java issue/PR is not correct. I believe that is done now. Could you correct the task list. Are we then ready to close this issue, or what else remains?

**Comment by mbwhite** [comment]
thanks @denyeart - this can be closed off.
