### ISSUE TITLE
Error: chaincode install failed with status: 500 

### ISSUE THREAD

**Issue by ws160920096** [hyperledger/fabric#3039]
I built version 2.4 and used test-network to test the network. The smart contract was not successfully deployed, and an error was reported as follows:
**Error: chaincode install failed with status: 500 - failed to invoke backing implementation of 'InstallChaincode': could not build chaincode: docker build failed: docker image inspection failed: **cannot connect to Docker endpoint**
Chaincode installation on peer0.org1 has failed
Deploying chaincode failed**

After searching online, it is not the go agent.My environment is built by Docker under Windows.Through the method of the net did not solve.
I need your help. Thank you!Hope to get your answer

**Comment by denyeart** [comment]
The issues in this repository are meant for core Fabric code issues.
It sounds like this problem is environmental, can't connect to Docker endpoint on your machine. For these types of issues please look for community support on Fabric mailing list or Rocketchat.
https://hyperledger-fabric.readthedocs.io/en/latest/CONTRIBUTING.html#getting-help

**Comment by SononGod** [comment]
Error: chaincode install failed with status: 500 - failed to invoke backing implementation of 'InstallChaincode': could not build chaincode: docker build failed: docker image inspection failed: cannot connect to Docker endpoint facing the same issue. exposed docker endpoint but still not working.

**Comment by Thejava-monk** [comment]
Facing the same issue. Any solution?

**Comment by melihassoun** [comment]
Hello !
I'm facing the same issue and I don't know how to fix it

I tried these commands 

**go mod tidy
go mod vendor**
but it doesn't work.

Can anyone help, please !

thank you

**Comment by melihassoun** [comment]
> I built version 2.4 and used test-network to test the network. The smart contract was not successfully deployed, and an error was reported as follows: **Error: chaincode install failed with status: 500 - failed to invoke backing implementation of 'InstallChaincode': could not build chaincode: docker build failed: docker image inspection failed: **cannot connect to Docker endpoint** Chaincode installation on peer0.org1 has failed Deploying chaincode failed**
> 
> After searching online, it is not the go agent.My environment is built by Docker under Windows.Through the method of the net did not solve. I need your help. Thank you!Hope to get your answer

Did you fix the problem ?!

**Comment by PandaManPMC** [comment]
I had the same problem and was looking for a way to fix it.

**Comment by SononGod** [comment]
Hi Man, Because of this issue I am using wsl2 in windows. Try to use IBM
blockchain platform extension in vs studio. as a local network. it will be
easier than open-source hyper ledger fabric. Windows don't provide that
much support for fabric instead use ubuntu. If you want more information I
will create video and will share you link.

**Comment by PandaManPMC** [comment]
go mod vendor
Execute the above command to download the dependencies into the source code and repackage the chaincode, and the installation is successful. I solved it this way.

**Comment by SononGod** [comment]
Tank you!

**Comment by melihassoun** [comment]
I think that the problem for me was the way that I installed go...
to fix it, I downloaded go and used tar-xvf .... instead of sudo apt

**Comment by Jakirik** [comment]
try downgrade my golang version to 1.13, works for me
using 
Ubuntu 20.04.4 LTS
Hyperledger fabric 2.4

refer to 
https://stackoverflow.com/questions/64315723/hyperledger-fabric-chaincode-installation-on-peer0-org1-has-failed

**Comment by prajwal-creator-art** [comment]
In the chaincode-go/go.mod file
open using the nano or vim editor and change the version from
go 1.14 to go 1.13
This worked for me

**Comment by nikoturin** [comment]
I did the change chaincode-go/go.mod to go 1.13 and it worked for me, thanks prajwal ...

**Comment by c0mr4t** [comment]
I did the downgrading thing as well and it also worked for me. But I think, your system's go version just has to match the version that is specified in fabric-samples/asset-transfer-basic/chaincode-go/go.mod

**Comment by vinayak-naik** [comment]
> In the chaincode-go/go.mod file open using the nano or vim editor and change the version from go 1.14 to go 1.13 This worked for me

This worked for me

**Comment by deamonyi** [comment]
Hello！
I'm facing the same issue and I try change chaincode-go/go.mod to go 1.13, but it still doesn't work.
The error was reported as follows:
`Error: chaincode install failed with status: 500 - failed to invoke backing implementation of 'InstallChaincode': could not build chaincode: docker build failed: docker image inspection failed: cannot connect to Docker endpoint
Chaincode installation on peer0.org1 has failed
Deploying chaincode failed
`
using windows 10, fabirc 2.4 and go 1.19
I need some help to fix it.

**Comment by sufuy45** [comment]
![image](https://user-images.githubusercontent.com/89099840/198825789-b0ef9371-2f78-44f2-860e-20c03ab2f016.png)

**Comment by yo-1008** [comment]
Hello, having the same problem than @deamonyi. Try to change to go 1.13 but same error message

using:
Ubuntu 21.10
fabric 2.4
go 1.19

thank u in advance

**Comment by JohanIskandar** [comment]
> ![image](https://user-images.githubusercontent.com/89099840/198825789-b0ef9371-2f78-44f2-860e-20c03ab2f016.png)

if this does not work, then uncheck -> apply and restart and then check it again if you are using istio

**Comment by yo-1008** [comment]
Thank you @JohanIskandar but i'm using Ubuntu and according to this: https://github.com/docker/for-linux/issues/1168 --> grpc fuse is not use in ubuntu binaries.

using:
Ubuntu 21.10
fabric 2.2
go 1.19

BR

**Comment by JohanIskandar** [comment]
Thanks for the heads-up. Your information is really helpful.

**Comment by ecemozturkk** [comment]
When I try to run `brew install go@1.14` to downgrade my go version , it says **Error: go@1.14 has been disabled because it is not supported upstream!**
Any help?

**Comment by JohanIskandar** [comment]
As long as it works on Ubuntu I am fine.  I havent tried another version
apart from ***@***.***  Thanks guys for all the help.

**Comment by JohanIskandar** [comment]
I had problem with docker desktop, but it works on Ubuntu

**Comment by yo-1008** [comment]
Interesting.

What version are you using? Ubuntu, docker, Golang

Thank u in advance :)

**Comment by yo-1008** [comment]
And Fabric.

**Comment by deamonyi** [comment]
I try use fabirc-sample2.2 and it worked successfully.

**Comment by lylelllll** [comment]
> I did the downgrading thing as well and it also worked for me. But I think, your system's go version just has to match the version that is specified in fabric-samples/asset-transfer-basic/chaincode-go/go.mod

it work ,thanks

**Comment by bellaj** [comment]
Sometimes you need only to grant internet access to your peer.

**Comment by bellaj** [comment]
Sometimes you need only to grant internet access to your peer.

**Comment by ArnWEB** [comment]
How to grant internet access to your peer can you please elaborate! it will be help ful thanks

**Comment by uttom-akash** [comment]
Thanks. @prajwal-creator. It also worked for me. basically, the go version should match. 
![image](https://github.com/hyperledger/fabric/assets/28487482/1315762f-a20a-4e6a-82dd-c39e72475a72)

**Comment by bellaj** [comment]
check also go.work in porject root and fix the version

**Comment by asirialwis** [comment]
I have downgrade the docker version to 28. It works for me.
