### ISSUE TITLE
Unable to edit ORG1MSPanchors.tx in Hyperledger Fabric

### ISSUE THREAD

**Issue by luismcortestirado** [hyperledger/fabric#3057]
Hello, I'm trying to edit the file ORG1MSPanchors.tx, so I've executed the following commands:
```
-> configtxlator proto_decode --input ./channel-artifacts/ORG1MSPanchors.tx --type common.Envelope >channel-artifacts/ORG1MSPanchors.json
-> nano channel-artifacts/ORG1MSPanchors.json
-> configtxlator proto_encode --input ./channel-artifacts/ORG1MSPanchors.json --type common.Envelope >./channel-artifacts/ORG1MSPanchors.tx
```

But the changes are not made in ORG1MSPanchors.tx. Does anyone know why this might be? Thanks...

**Comment by xujiamingtxwd123** [comment]
Describe the modified fields about ORG1MSPanchors.json ，It is helpful for everyone to analyze the problem

**Comment by luismcortestirado** [comment]
I have changed the version number in the "payload.data.config_update.read_set.groups.Application.version" and "payload.data.config_update.write_set.groups.Application.version" fields as indicated in this issue: https://stackoverflow.com/questions/53999025/hyperledger-fabric-error-validating-readset-readset-expected-key-group-ch, but the changes are not being made.

**Comment by denyeart** [comment]
Please use stackoverflow or mailing list for usage questions.
