### ISSUE TITLE
Unable to get Fabric Network with TLS Chain of Trust of multiple Fabric CA Servers working!

### ISSUE THREAD

**Issue by aaronbeer81** [hyperledger/fabric#3058]
Repost for publicity: [https://github.com/hyperledger/fabric-ca/issues/266](https://github.com/hyperledger/fabric-ca/issues/266)
Please comment only on the linked Issue!

Thank you very much!

**Comment by denyeart** [comment]
Please reserve github issues for Fabric code issues.

For getting help, see the community help resources mentioned at:
https://hyperledger-fabric.readthedocs.io/en/latest/CONTRIBUTING.html#getting-help
