### ISSUE TITLE
An error is reported when running the cmd "ORDERER_GENERAL_GENESISPROFILE=SampleDevModeSolo orderer" in macOS

### ISSUE THREAD

**Issue by Xingxingyeyouxinshi** [hyperledger/fabric#3076]
I need debug custom chaincode for development, I think this should be what all developers need. I used the IBM Blockchain Platform VSCode Extension to develop. Although it is very convenient to use, the latest version does not support debug, so I continue to use the devmod in the Hyperledger Faric official document, but it reports an error.

Environment
System：macOS Monterey 12.0.1
HLF：release-2.3

When I execute the instruction `ORDERER_GENERAL_GENESISPROFILE=SampleDevModeSolo orderer` according to "[Running chaincode in development mode](https://hyperledger-fabric.readthedocs.io/en/release-2.3/peer-chaincode-devmode.html)", it reports an error.

> 192:fabric Ryoma$ cd scripts/
192:scripts Ryoma$ ORDERER_GENERAL_GENESISPROFILE=SampleDevModeSolo orderer
2021-11-24 12:32:19.050 CST [localconfig] completeInitialization -> INFO 001 Kafka.Version unset, setting to 0.10.2.0
2021-11-24 12:32:19.051 CST [orderer.common.server] prettyPrintStruct -> INFO 002 Orderer config values:
	General.ListenAddress = "127.0.0.1"
	General.ListenPort = 7050
	General.TLS.Enabled = false
	General.TLS.PrivateKey = "/Users/Ryoma/go/fabric/sampleconfig/tls/server.key"
	General.TLS.Certificate = "/Users/Ryoma/go/fabric/sampleconfig/tls/server.crt"
	General.TLS.RootCAs = [/Users/Ryoma/go/fabric/sampleconfig/tls/ca.crt]
	General.TLS.ClientAuthRequired = false
	General.TLS.ClientRootCAs = []
	General.TLS.TLSHandshakeTimeShift = 0s
	General.Cluster.ListenAddress = ""
	General.Cluster.ListenPort = 0
	General.Cluster.ServerCertificate = ""
	General.Cluster.ServerPrivateKey = ""
	General.Cluster.ClientCertificate = ""
	General.Cluster.ClientPrivateKey = ""
	General.Cluster.RootCAs = []
	General.Cluster.DialTimeout = 5s
	General.Cluster.RPCTimeout = 7s
	General.Cluster.ReplicationBufferSize = 20971520
	General.Cluster.ReplicationPullTimeout = 5s
	General.Cluster.ReplicationRetryTimeout = 5s
	General.Cluster.ReplicationBackgroundRefreshInterval = 5m0s
	General.Cluster.ReplicationMaxRetries = 12
	General.Cluster.SendBufferSize = 10
	General.Cluster.CertExpirationWarningThreshold = 168h0m0s
	General.Cluster.TLSHandshakeTimeShift = 0s
	General.Keepalive.ServerMinInterval = 1m0s
	General.Keepalive.ServerInterval = 2h0m0s
	General.Keepalive.ServerTimeout = 20s
	General.ConnectionTimeout = 0s
	General.GenesisMethod = ""
	General.GenesisFile = ""
	General.BootstrapMethod = "file"
	General.BootstrapFile = "/Users/Ryoma/go/fabric/sampleconfig/genesisblock"
	General.Profile.Enabled = false
	General.Profile.Address = "0.0.0.0:6060"
	General.LocalMSPDir = "/Users/Ryoma/go/fabric/sampleconfig/msp"
	General.LocalMSPID = "SampleOrg"
	General.BCCSP.Default = "SW"
	General.BCCSP.SW.Security = 256
	General.BCCSP.SW.Hash = "SHA2"
	General.BCCSP.SW.FileKeystore.KeyStorePath = ""
	General.Authentication.TimeWindow = 15m0s
	General.Authentication.NoExpirationChecks = false
	General.MaxRecvMsgSize = 104857600
	General.MaxSendMsgSize = 104857600
	FileLedger.Location = "/var/hyperledger/production/orderer"
	FileLedger.Prefix = ""
	Kafka.Retry.ShortInterval = 5s
	Kafka.Retry.ShortTotal = 10m0s
	Kafka.Retry.LongInterval = 5m0s
	Kafka.Retry.LongTotal = 12h0m0s
	Kafka.Retry.NetworkTimeouts.DialTimeout = 10s
	Kafka.Retry.NetworkTimeouts.ReadTimeout = 10s
	Kafka.Retry.NetworkTimeouts.WriteTimeout = 10s
	Kafka.Retry.Metadata.RetryMax = 3
	Kafka.Retry.Metadata.RetryBackoff = 250ms
	Kafka.Retry.Producer.RetryMax = 3
	Kafka.Retry.Producer.RetryBackoff = 100ms
	Kafka.Retry.Consumer.RetryBackoff = 2s
	Kafka.Verbose = false
	Kafka.Version = 0.10.2.0
	Kafka.TLS.Enabled = false
	Kafka.TLS.PrivateKey = ""
	Kafka.TLS.Certificate = ""
	Kafka.TLS.RootCAs = []
	Kafka.TLS.ClientAuthRequired = false
	Kafka.TLS.ClientRootCAs = []
	Kafka.TLS.TLSHandshakeTimeShift = 0s
	Kafka.SASLPlain.Enabled = false
	Kafka.SASLPlain.User = ""
	Kafka.SASLPlain.Password = ""
	Kafka.Topic.ReplicationFactor = 3
	Debug.BroadcastTraceDir = ""
	Debug.DeliverTraceDir = ""
	Consensus = map[SnapDir:/var/hyperledger/production/orderer/etcdraft/snapshot WALDir:/var/hyperledger/production/orderer/etcdraft/wal]
	Operations.ListenAddress = "127.0.0.1:8443"
	Operations.TLS.Enabled = false
	Operations.TLS.PrivateKey = ""
	Operations.TLS.Certificate = ""
	Operations.TLS.RootCAs = []
	Operations.TLS.ClientAuthRequired = false
	Operations.TLS.ClientRootCAs = []
	Operations.TLS.TLSHandshakeTimeShift = 0s
	Metrics.Provider = "disabled"
	Metrics.Statsd.Network = "udp"
	Metrics.Statsd.Address = "127.0.0.1:8125"
	Metrics.Statsd.WriteInterval = 30s
	Metrics.Statsd.Prefix = ""
	ChannelParticipation.Enabled = false
	ChannelParticipation.MaxRequestBodySize = 1048576
	Admin.ListenAddress = "127.0.0.1:9443"
	Admin.TLS.Enabled = false
	Admin.TLS.PrivateKey = ""
	Admin.TLS.Certificate = ""
	Admin.TLS.RootCAs = []
	Admin.TLS.ClientAuthRequired = true
	Admin.TLS.ClientRootCAs = []
	Admin.TLS.TLSHandshakeTimeShift = 0s
panic: Error creating dir if missing: error while creating dir: /var/hyperledger/production/orderer/index: mkdir /var/hyperledger: permission denied

goroutine 1 [running]:
github.com/hyperledger/fabric/common/ledger/util/leveldbhelper.(*DB).Open(0xc000135590)
	/Users/Ryoma/go/fabric/common/ledger/util/leveldbhelper/leveldb_helper.go:71 +0x205
github.com/hyperledger/fabric/common/ledger/util/leveldbhelper.openDBAndCheckFormat(0xc000088120)
	/Users/Ryoma/go/fabric/common/ledger/util/leveldbhelper/leveldb_provider.go:72 +0x145
github.com/hyperledger/fabric/common/ledger/util/leveldbhelper.NewProvider(0xc0000fd118)
	/Users/Ryoma/go/fabric/common/ledger/util/leveldbhelper/leveldb_provider.go:60 +0x1d
github.com/hyperledger/fabric/common/ledger/blkstorage.NewProvider(0xc00000e378, 0xc00000e3a8, {0x4bbb9d0, 0x526a670})
	/Users/Ryoma/go/fabric/common/ledger/blkstorage/blockstore_provider.go:70 +0x14d
github.com/hyperledger/fabric/common/ledger/blockledger/fileledger.New({0xc00040c300, 0x23}, {0x4bbb9d0, 0x526a670})
	/Users/Ryoma/go/fabric/common/ledger/blockledger/fileledger/factory.go:103 +0x113
github.com/hyperledger/fabric/orderer/common/server.createLedgerFactory(0x0, {0x4bbb9d0, 0x526a670})
	/Users/Ryoma/go/fabric/orderer/common/server/util.go:24 +0x105
github.com/hyperledger/fabric/orderer/common/server.Main()
	/Users/Ryoma/go/fabric/orderer/common/server/main.go:115 +0x5b5
main.main()
	/Users/Ryoma/go/fabric/cmd/orderer/main.go:15 +0x17
192:scripts Ryoma$ sudo ORDERER_GENERAL_GENESISPROFILE=SampleDevModeSolo orderer

next,it reported an error when I try to run this cmd `sudo ORDERER_GENERAL_GENESISPROFILE=SampleDevModeSolo orderer`.

192:fabric Ryoma$ sudo ORDERER_GENERAL_GENESISPROFILE=SampleDevModeSolo orderer
Password:
2021-11-24 14:33:44.910 CST [viperutil] ReadInConfig -> ERRO 001 Unable to open the config file: 
2021-11-24 14:33:44.913 CST [orderer.common.server] Main -> ERRO 002 failed to parse config:  Error reading configuration: open : no such file or directory

Anyone help?

**Comment by timo-kang** [comment]
I think you didn't export `FABRIC_CFG_PATH` so that it cannot find the config file.

**Comment by Xingxingyeyouxinshi** [comment]
> I think you didn't export `FABRIC_CFG_PATH` so that it cannot find the config file.

in the fabric directory,I run the following commands in turn.

> $ make orderer peer configtxgen
> $ export PATH=$(pwd)/build/bin:$PATH
> $ export FABRIC_CFG_PATH=$(pwd)/sampleconfig
> $ configtxgen -profile SampleDevModeSolo -channelID syschannel -outputBlock genesisblock -configPath $FABRIC_CFG_PATH -outputBlock $(pwd)/sampleconfig/genesisblock
> $ ORDERER_GENERAL_GENESISPROFILE=SampleDevModeSolo orderer

it reported an error when I run this cmd `ORDERER_GENERAL_GENESISPROFILE=SampleDevModeSolo orderer`.

> 192:fabric Ryoma$ git checkout 2.3.3
error: pathspec '2.3.3' did not match any file(s) known to git
192:fabric Ryoma$ git checkout release-2.3.3
error: pathspec 'release-2.3.3' did not match any file(s) known to git
192:fabric Ryoma$ git checkout release-2.3
Branch 'release-2.3' set up to track remote branch 'release-2.3' from 'origin'.
Switched to a new branch 'release-2.3'
192:fabric Ryoma$ make orderer peer configtxgen
Building build/bin/orderer
GOBIN=/Users/Ryoma/go/fabric/build/bin go install -tags "" -ldflags "-X github.com/hyperledger/fabric/common/metadata.Version=2.3.3 -X github.com/hyperledger/fabric/common/metadata.CommitSHA=c25cf25fa -X github.com/hyperledger/fabric/common/metadata.BaseDockerLabel=org.hyperledger.fabric -X github.com/hyperledger/fabric/common/metadata.DockerNamespace=hyperledger" github.com/hyperledger/fabric/cmd/orderer
Building build/bin/peer
GOBIN=/Users/Ryoma/go/fabric/build/bin go install -tags "" -ldflags "-X github.com/hyperledger/fabric/common/metadata.Version=2.3.3 -X github.com/hyperledger/fabric/common/metadata.CommitSHA=c25cf25fa -X github.com/hyperledger/fabric/common/metadata.BaseDockerLabel=org.hyperledger.fabric -X github.com/hyperledger/fabric/common/metadata.DockerNamespace=hyperledger" github.com/hyperledger/fabric/cmd/peer
Building build/bin/configtxgen
GOBIN=/Users/Ryoma/go/fabric/build/bin go install -tags "" -ldflags "-X github.com/hyperledger/fabric/common/metadata.Version=2.3.3 -X github.com/hyperledger/fabric/common/metadata.CommitSHA=c25cf25fa -X github.com/hyperledger/fabric/common/metadata.BaseDockerLabel=org.hyperledger.fabric -X github.com/hyperledger/fabric/common/metadata.DockerNamespace=hyperledger" github.com/hyperledger/fabric/cmd/configtxgen
192:fabric Ryoma$ export PATH=$(pwd)/build/bin:$PATH
192:fabric Ryoma$ export FABRIC_CFG_PATH=$(pwd)/sampleconfig
192:fabric Ryoma$ configtxgen -profile SampleDevModeSolo -channelID syschannel -outputBlock genesisblock -configPath $FABRIC_CFG_PATH -outputBlock $(pwd)/sampleconfig/genesisblock
2021-11-24 12:31:30.500 CST [common.tools.configtxgen] main -> INFO 001 Loading configuration
2021-11-24 12:31:30.526 CST [common.tools.configtxgen.localconfig] completeInitialization -> INFO 002 orderer type: solo
2021-11-24 12:31:30.526 CST [common.tools.configtxgen.localconfig] Load -> INFO 003 Loaded configuration: /Users/Ryoma/go/fabric/sampleconfig/configtx.yaml
2021-11-24 12:31:30.529 CST [common.tools.configtxgen] doOutputBlock -> INFO 004 Generating genesis block
2021-11-24 12:31:30.529 CST [common.tools.configtxgen] doOutputBlock -> INFO 005 Creating system channel genesis block
2021-11-24 12:31:30.530 CST [common.tools.configtxgen] doOutputBlock -> INFO 006 Writing genesis block
192:fabric Ryoma$ ls
CHANGELOG.md		NOTICE			common			gossip			orderer			tox.ini
CODEOWNERS		README.md		core			gotools.mk		pkg			vagrant
CODE_OF_CONDUCT.md	SECURITY.md		discovery		idemix			protoutil		vendor
CONTRIBUTING.md		bccsp			docker-env.mk		images			release_notes
LICENSE			build			docs			integration		sampleconfig
MAINTAINERS.md		ci			go.mod			internal		scripts
Makefile		cmd			go.sum			msp			tools
192:fabric Ryoma$ cd scripts/
192:scripts Ryoma$ ORDERER_GENERAL_GENESISPROFILE=SampleDevModeSolo orderer
2021-11-24 12:32:19.050 CST [localconfig] completeInitialization -> INFO 001 Kafka.Version unset, setting to 0.10.2.0
2021-11-24 12:32:19.051 CST [orderer.common.server] prettyPrintStruct -> INFO 002 Orderer config values:
	General.ListenAddress = "127.0.0.1"
	General.ListenPort = 7050
	General.TLS.Enabled = false
	General.TLS.PrivateKey = "/Users/Ryoma/go/fabric/sampleconfig/tls/server.key"
	General.TLS.Certificate = "/Users/Ryoma/go/fabric/sampleconfig/tls/server.crt"
	General.TLS.RootCAs = [/Users/Ryoma/go/fabric/sampleconfig/tls/ca.crt]
	General.TLS.ClientAuthRequired = false
	General.TLS.ClientRootCAs = []
	General.TLS.TLSHandshakeTimeShift = 0s
	General.Cluster.ListenAddress = ""
	General.Cluster.ListenPort = 0
	General.Cluster.ServerCertificate = ""
	General.Cluster.ServerPrivateKey = ""
	General.Cluster.ClientCertificate = ""
	General.Cluster.ClientPrivateKey = ""
	General.Cluster.RootCAs = []
	General.Cluster.DialTimeout = 5s
	General.Cluster.RPCTimeout = 7s
	General.Cluster.ReplicationBufferSize = 20971520
	General.Cluster.ReplicationPullTimeout = 5s
	General.Cluster.ReplicationRetryTimeout = 5s
	General.Cluster.ReplicationBackgroundRefreshInterval = 5m0s
	General.Cluster.ReplicationMaxRetries = 12
	General.Cluster.SendBufferSize = 10
	General.Cluster.CertExpirationWarningThreshold = 168h0m0s
	General.Cluster.TLSHandshakeTimeShift = 0s
	General.Keepalive.ServerMinInterval = 1m0s
	General.Keepalive.ServerInterval = 2h0m0s
	General.Keepalive.ServerTimeout = 20s
	General.ConnectionTimeout = 0s
	General.GenesisMethod = ""
	General.GenesisFile = ""
	General.BootstrapMethod = "file"
	General.BootstrapFile = "/Users/Ryoma/go/fabric/sampleconfig/genesisblock"
	General.Profile.Enabled = false
	General.Profile.Address = "0.0.0.0:6060"
	General.LocalMSPDir = "/Users/Ryoma/go/fabric/sampleconfig/msp"
	General.LocalMSPID = "SampleOrg"
	General.BCCSP.Default = "SW"
	General.BCCSP.SW.Security = 256
	General.BCCSP.SW.Hash = "SHA2"
	General.BCCSP.SW.FileKeystore.KeyStorePath = ""
	General.Authentication.TimeWindow = 15m0s
	General.Authentication.NoExpirationChecks = false
	General.MaxRecvMsgSize = 104857600
	General.MaxSendMsgSize = 104857600
	FileLedger.Location = "/var/hyperledger/production/orderer"
	FileLedger.Prefix = ""
	Kafka.Retry.ShortInterval = 5s
	Kafka.Retry.ShortTotal = 10m0s
	Kafka.Retry.LongInterval = 5m0s
	Kafka.Retry.LongTotal = 12h0m0s
	Kafka.Retry.NetworkTimeouts.DialTimeout = 10s
	Kafka.Retry.NetworkTimeouts.ReadTimeout = 10s
	Kafka.Retry.NetworkTimeouts.WriteTimeout = 10s
	Kafka.Retry.Metadata.RetryMax = 3
	Kafka.Retry.Metadata.RetryBackoff = 250ms
	Kafka.Retry.Producer.RetryMax = 3
	Kafka.Retry.Producer.RetryBackoff = 100ms
	Kafka.Retry.Consumer.RetryBackoff = 2s
	Kafka.Verbose = false
	Kafka.Version = 0.10.2.0
	Kafka.TLS.Enabled = false
	Kafka.TLS.PrivateKey = ""
	Kafka.TLS.Certificate = ""
	Kafka.TLS.RootCAs = []
	Kafka.TLS.ClientAuthRequired = false
	Kafka.TLS.ClientRootCAs = []
	Kafka.TLS.TLSHandshakeTimeShift = 0s
	Kafka.SASLPlain.Enabled = false
	Kafka.SASLPlain.User = ""
	Kafka.SASLPlain.Password = ""
	Kafka.Topic.ReplicationFactor = 3
	Debug.BroadcastTraceDir = ""
	Debug.DeliverTraceDir = ""
	Consensus = map[SnapDir:/var/hyperledger/production/orderer/etcdraft/snapshot WALDir:/var/hyperledger/production/orderer/etcdraft/wal]
	Operations.ListenAddress = "127.0.0.1:8443"
	Operations.TLS.Enabled = false
	Operations.TLS.PrivateKey = ""
	Operations.TLS.Certificate = ""
	Operations.TLS.RootCAs = []
	Operations.TLS.ClientAuthRequired = false
	Operations.TLS.ClientRootCAs = []
	Operations.TLS.TLSHandshakeTimeShift = 0s
	Metrics.Provider = "disabled"
	Metrics.Statsd.Network = "udp"
	Metrics.Statsd.Address = "127.0.0.1:8125"
	Metrics.Statsd.WriteInterval = 30s
	Metrics.Statsd.Prefix = ""
	ChannelParticipation.Enabled = false
	ChannelParticipation.MaxRequestBodySize = 1048576
	Admin.ListenAddress = "127.0.0.1:9443"
	Admin.TLS.Enabled = false
	Admin.TLS.PrivateKey = ""
	Admin.TLS.Certificate = ""
	Admin.TLS.RootCAs = []
	Admin.TLS.ClientAuthRequired = true
	Admin.TLS.ClientRootCAs = []
	Admin.TLS.TLSHandshakeTimeShift = 0s
panic: Error creating dir if missing: error while creating dir: /var/hyperledger/production/orderer/index: mkdir /var/hyperledger: permission denied

> goroutine 1 [running]:
github.com/hyperledger/fabric/common/ledger/util/leveldbhelper.(*DB).Open(0xc000135590)
	/Users/Ryoma/go/fabric/common/ledger/util/leveldbhelper/leveldb_helper.go:71 +0x205
github.com/hyperledger/fabric/common/ledger/util/leveldbhelper.openDBAndCheckFormat(0xc000088120)
	/Users/Ryoma/go/fabric/common/ledger/util/leveldbhelper/leveldb_provider.go:72 +0x145
github.com/hyperledger/fabric/common/ledger/util/leveldbhelper.NewProvider(0xc0000fd118)
	/Users/Ryoma/go/fabric/common/ledger/util/leveldbhelper/leveldb_provider.go:60 +0x1d
github.com/hyperledger/fabric/common/ledger/blkstorage.NewProvider(0xc00000e378, 0xc00000e3a8, {0x4bbb9d0, 0x526a670})
	/Users/Ryoma/go/fabric/common/ledger/blkstorage/blockstore_provider.go:70 +0x14d
github.com/hyperledger/fabric/common/ledger/blockledger/fileledger.New({0xc00040c300, 0x23}, {0x4bbb9d0, 0x526a670})
	/Users/Ryoma/go/fabric/common/ledger/blockledger/fileledger/factory.go:103 +0x113
github.com/hyperledger/fabric/orderer/common/server.createLedgerFactory(0x0, {0x4bbb9d0, 0x526a670})
	/Users/Ryoma/go/fabric/orderer/common/server/util.go:24 +0x105
github.com/hyperledger/fabric/orderer/common/server.Main()
	/Users/Ryoma/go/fabric/orderer/common/server/main.go:115 +0x5b5
main.main()
	/Users/Ryoma/go/fabric/cmd/orderer/main.go:15 +0x17
192:scripts Ryoma$ sudo ORDERER_GENERAL_GENESISPROFILE=SampleDevModeSolo orderer
Password:
2021-11-24 12:32:31.188 CST [viperutil] ReadInConfig -> ERRO 001 Unable to open the config file: 
2021-11-24 12:32:31.188 CST [orderer.common.server] Main -> ERRO 002 failed to parse config:  Error reading configuration: open : no such file or directory
192:scripts Ryoma$ cd ..
192:fabric Ryoma$ sudo ORDERER_GENERAL_GENESISPROFILE=SampleDevModeSolo orderer
Password:
2021-11-24 14:33:44.910 CST [viperutil] ReadInConfig -> ERRO 001 Unable to open the config file: 
2021-11-24 14:33:44.913 CST [orderer.common.server] Main -> ERRO 002 failed to parse config:  Error reading configuration: open : no such file or directory

**Comment by denyeart** [comment]
The instructions are being fixed in https://github.com/hyperledger/fabric/pull/3099

**Comment by Ethereumx** [comment]
@denyeart  oh my bad I was going through this too. Why haven't they merge this modification?

**Comment by denyeart** [comment]
It will be merged shortly once review feedback is addressed.

**Comment by Pheglovog** [comment]
peer channel signconfigtx的用处
