### ISSUE TITLE
[Fabric][Windows10][Docker2.5.0.1][Java/Javascript]Error: chaincode install failed with status: 500 - failed to invoke backing implementation of 'InstallChaincode': could not build chaincode: docker build failed: docker image inspection failed: cannot connect to Docker endpoint

### ISSUE THREAD

**Issue by mscode1729** [hyperledger/fabric#3081]
I was following steps provided in the doc https://hyperledger-fabric.readthedocs.io/en/latest/write_first_app.html for the above issue:
1.curl -sSL https://bit.ly/2ysbOFE | bash -s
2../network.sh up createChannel -c mychannel -ca
3. i. ./network.sh deployCC -ccn basic -ccp ../asset-transfer-basic/chaincode-java/ -ccl java
   ii. ./network.sh deployCC -ccn basic -ccp ../asset-transfer-basic/chaincode-javascript/ -ccl javascript
Steps 1,2 are successfully done and channel is created. But Step3.1/Step3.2 neither is succesful,  they fail saying 

**Chaincode is packaged
Installing chaincode on peer0.org1...
Using organization 1
+ peer lifecycle chaincode install basic.tar.gz
+ res=1
Error: chaincode install failed with status: 500 - failed to invoke backing implementation of 'InstallChaincode': could not build chaincode: docker build failed: docker image inspection failed: cannot connect to Docker endpoint
Chaincode installation on peer0.org1 has failed
Deploying chaincode failed**

Note- I had to try docker 2.5.0.1 as the latest versions are failing on different issues and the document too suggest to keep this docker version

**Comment by denyeart** [comment]
Looks like a Docker environment issue on Windows rather than a Fabric code issue.
Please use community support channels (https://hyperledger-fabric.readthedocs.io/en/latest/CONTRIBUTING.html#getting-help) instead of creating an issue against Fabric code.
