### ISSUE TITLE
How to develop and deploy the java-contract in the test-network-k8s

### ISSUE THREAD

**Issue by Xingxingyeyouxinshi** [hyperledger/fabric#3084]
I can't run the **chain-extenal** under **assert-transfer-basic** in **[fabric-sample](https://github.com/hyperledger/fabric-samples)**. Someone can share the operation process of Java chain code in "working with chain" mode, so that I can learn from it.

thank you very much

**Comment by Xingxingyeyouxinshi** [comment]
[this issue](https://github.com/hyperledger/fabric-samples/issues/548) is my question.

**Comment by denyeart** [comment]
Please don't open the same issues in multiple repositories, please use fabric-samples repository for samples issues.
