### ISSUE TITLE
Unclear empty critical section

### ISSUE THREAD

**Issue by guoger** [hyperledger/fabric#3101]
https://github.com/hyperledger/fabric/blob/516bc8bab548a484e2e62fee24b0f4fed5bf6873/core/ledger/kvledger/kv_ledger.go#L542-L547

I'm not sure why this is not implemented the same way as other methods in the same file. If a special case is indeed needed here, some comments would be appreciated

**Comment by yacovm** [comment]
I think it's just a synchronization for waiting for writers to finish before returning an API call because otherwise we get old data. 

If we defer the unlock we can remove the lint hint. 

@manish-sethi  @denyeart  wdyt?

**Comment by manish-sethi** [comment]
Yes, @yacovm - However, I guess @guoger is asking why it looks different from how it is on other similar functions. 

In the first version we had the above pattern in all the functions, having super perf-centric thinking in relation to block commit :-). We later changed to the more canonical style, as you see in the other functions. It seems this one got missed. Please feel free to push a PR if you want to fix this - Thanks!

**Comment by Hafiziddi** [comment]
I am new here

**Comment by AnilRaj27** [comment]
@manish-sethi I want to contribute to this issue.
