### ISSUE TITLE
Typo in the figure

### ISSUE THREAD

**Issue by JinchunChoi** [hyperledger/fabric#3106]
I found a typo in the figure (peers.diagram.8.png).
It should be updated like below:

Before:
Principal PA (e.g. **A1**, P5) communicates via channel C.

After:
Principal PA (e.g. **P1**, P5) communicates via channel C.

Thanks,
- Jinchun Choi.

**Comment by denyeart** [comment]
Thank you, the peer diagrams will be updated as part of #2807
