### ISSUE TITLE
leveldb panic

### ISSUE THREAD

**Issue by ghost** [hyperledger/fabric#3112]
when i run the command `peer node start`, i got the follow error,
![image](https://user-images.githubusercontent.com/34224979/145586413-d4d04b22-e2a1-404a-95aa-aa4dc79c1fce.png)

@denyeart @manish-sethi can you give me a clue?

**Comment by ghost** [comment]
the result of the `peer version`


![image](https://user-images.githubusercontent.com/34224979/145587929-98e017cd-f665-4959-bb2c-e127a826ef5f.png)

and the runtime environment of the peer is k8s, the map the `/var/hyperledger/fabric` directory the host

**Comment by denyeart** [comment]
It means there is already a database open that is using that file system. Perhaps you have another peer process using the same directory.
Also, Fabric v1.4.2 is very old and not being maintained/supported anymore.
