### ISSUE TITLE
Test killed with quit: ran too long (21m0s) when building hyperledger fabric

### ISSUE THREAD

**Issue by sousoul** [hyperledger/fabric#3124]
I am new to Hyperleger Fabric and I try to build  Hyperledger Fabric v2.2 according to the following documentation.
https://github.com/hyperledger/fabric-docs-i18n/blob/release-2.2/docs/locale/zh_CN/source/dev-setup/build.rst
However, I meet this error:
```
goroutine 1 [running]:
	goroutine running on other thread; stack unavailable

rax    0x104
rbx    0xa625e00
rcx    0x7ffeefbff388
rdx    0xb00
rdi    0x4771220
rsi    0xb0100000c00
rbp    0x7ffeefbff430
rsp    0x7ffeefbff388
r8     0x0
r9     0xa0
r10    0x0
r11    0x246
r12    0x47711e0
r13    0x16
r14    0xb0100000c00
r15    0xb00
rip    0x7fff20491cde
rflags 0x247
cs     0x7
fs     0x0
gs     0x0
*** Test killed with quit: ran too long (21m0s).
FAIL	github.com/hyperledger/fabric/bccsp/factory	1260.019s
Immutable = [false]
```

Before building hyper fabric, I have set up the development environment successfully according to this tutorial. 
https://hyperledger-fabric.readthedocs.io/en/release-2.4/dev-setup/devenv.html 

Version information are as following：
OS: macOS BigSur 11.6
hyperledger fabric v2.2.4
go version go1.16.7 darwin/amd64
Docker version 20.10.8, build 3967b7d
SoftHSM 2.6.1

So I am very confusing and cannot solve this problem, how can I solve the error?

**Comment by timo-kang** [comment]
I think you should make a issue on https://github.com/hyperledger/fabric-docs-i18n this repo.

**Comment by sousoul** [comment]
> I think you should make a issue on https://github.com/hyperledger/fabric-docs-i18n this repo.
ok, I try it

**Comment by davidkel** [comment]
@sousoul don't use softhsm 2.6.1, use softhsm 2.5. That's most likely to be your problem

**Comment by sousoul** [comment]
> @sousoul don't use softhsm 2.6.1, use softhsm 2.5. That's most likely to be your problem

OK，thank you, but I meet some difficulty when installing softhsm2.5 from source code as homebrew only provide softhsm2.6.1. Maybe It is a mistake to user hyperledger fabric on macOS. I give it up.

**Comment by denyeart** [comment]
Since Fabric docs recommend SoftHSM v2.5 I'll close this issue.
