### ISSUE TITLE
getQueryResultWithPagination code example

### ISSUE THREAD

**Issue by HarshMultani** [hyperledger/fabric#3125]
Hi Fabric Team,

Can anyone point me to a code example which involves fetching the records from Fabric using Pagination,
An example which involves the use of getQueryResultWithPagination?

**Comment by Param-S** [comment]
Please check this fabric sample: https://github.com/hyperledger/fabric-samples/blob/c646c5904ff0b45cb9052136b50b7a7a58cefe78/asset-transfer-ledger-queries/application-java/src/main/java/application/java/App.java#L131 whether it helps.

**Comment by denyeart** [comment]
And the corresponding chaincode sample:
https://github.com/hyperledger/fabric-samples/blob/main/asset-transfer-ledger-queries/chaincode-go/asset_transfer_ledger_chaincode.go#L345-L356
