### ISSUE TITLE
What API does keyword query historical transaction data use

### ISSUE THREAD

**Issue by suzhiliang** [hyperledger/fabric#3139]
With couchDB storage, can a smart contract vaguely retrieve historical data based on the value of an upchain content field? What's the API? I can only find a way to query historical data by key 'GetHistoryForKey(key String)'

**Comment by denyeart** [comment]
If you want to do other types of historical queries beyond GetHistoryForKey(), then you will need to keep whatever you want to query on in current state and then use one of the current state queries (i.e. key range query or couchdb JSON query).

**Comment by suzhiliang** [comment]
couchdb JSON query  methods cannot query the traceability data records of the same transaction number, only the latest coverage

**Comment by suzhiliang** [comment]
@denyeart couchdb JSON query methods cannot query the traceability data records of the same transaction number, only the latest coverage
