### ISSUE TITLE
error post "https://localhost:7053/participation/v1/channels

### ISSUE THREAD

**Issue by yekai1003** [hyperledger/fabric#3145]
When I follow fabric-samples to a run a test-network，I get this error.
error post "https://localhost:7053/participation/v1/channels

My comman is 
`
./network.sh up createChannel -c ykchannel
`
my version : 2.3.3

**Comment by denyeart** [comment]
Make sure your fabric images are at least v2.3 as well. The REST API was introduced in v2.3.

If you have additional issues running the fabric samples, please open issues in the fabric-samples repo at https://github.com/hyperledger/fabric-samples/issues.
