### ISSUE TITLE
about Updating an endorsement policy problems

### ISSUE THREAD

**Issue by binny1024** [hyperledger/fabric#3147]
I don’t know if it’s a bug to update the endorsement strategy. Personally, I think the execution logic is a bug.

```shell
peer lifecycle chaincode approveformyorg \
--signature-policy "AND ('Org1MSP.peer','Org2MSP.peer')" \
-o localhost:7050 \
--ordererTLSHostnameOverride orderer.example.com \
--channelID mychannel \
--name fabcar \
--version 1.0 \
--package-id $CC_PACKAGE_ID \
--sequence 1 \
--tls \
--cafile ${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp/tlscacerts/tlsca.example.com-cert.pem
```

- Output log

No error

```
2021-12-27 06:14:22.983 UTC [chaincodeCmd] ClientWait -> INFO 001 txid [026dc39d7a11a849c0dd656f5bdb96e1900b2a8e6ea7306e4e334d13b5d64b92] committed with status (VALID) at
```
But when I checked the approval status, I found that the organization did not approve

```shell
peer lifecycle chaincode checkcommitreadiness  \
--channelID mychannel  \
--name fabcar  \
--version 1.0  \
--sequence 2  \
--tls  \
--cafile ${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp/tlscacerts/tlsca.example.com-cert.pem  \
--output json
```

However, when I see that I also need to add that option when executing the commit command, I have also had questions, is this not necessary? [Setting chaincode-level endorsement policies](https://hyperledger-fabric.readthedocs.io/zh_CN/release-2.2/endorsement-policies.html#id3)，Isn't it okay to do it via the '—sequence' option? Because '--signature-policy' was added to the commit command.hahahaha...as a result ....i got what i wanted.

```shell
peer lifecycle chaincode checkcommitreadiness  \
--signature-policy "AND ('Org1MSP.peer','Org2MSP.peer')" \
--channelID mychannel  \
--name fabcar  \
--version 1.0  \
--sequence 2  \
--tls  \
--cafile ${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp/tlscacerts/tlsca.example.com-cert.pem  \
--output json
```
```
{
	"approvals": {
		"Org1MSP": true,
		"Org2MSP": true
	}
}
```

Butttttttttttttt!!! I still think it's a logical bug！！！

**Comment by binny1024** [comment]
I have solved the above problem, the solution is as above.

**Comment by denyeart** [comment]
The approveformyorg and commit parameters must match exactly. Looks like this is working as intended.
