### ISSUE TITLE
Orderer integration test flake

### ISSUE THREAD

**Issue by Param-S** [hyperledger/fabric#3149]
**Failing Stack:**
```
[e][OrdererOrg.orderer1] 2021-12-18 10:24:00.328 UTC 005b INFO [orderer.consensus.etcdraft] catchUp -> Finished syncing with cluster up to and including block [10] channel=systemchannel node=1 
[e][OrdererOrg.orderer1] panic: runtime error: invalid memory address or nil pointer dereference 
[e][OrdererOrg.orderer1] [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc7230a] 
[e][OrdererOrg.orderer1] 
[e][OrdererOrg.orderer1] goroutine 89 [running]: 
[e][OrdererOrg.orderer1] github.com/hyperledger/fabric/orderer/consensus/etcdraft.(*Chain).apply(0xc00083a000, 0xc000014f78, 0x1, 0x1) 
[e][OrdererOrg.orderer1] /home/vsts/work/1/fabric/orderer/consensus/etcdraft/chain.go:1149 +0xa8a 
[e][OrdererOrg.orderer1] github.com/hyperledger/fabric/orderer/consensus/etcdraft.(*Chain).run(0xc00083a000) 
[e][OrdererOrg.orderer1] /home/vsts/work/1/fabric/orderer/consensus/etcdraft/chain.go:781 +0x978 
[e][OrdererOrg.orderer1] created by github.com/hyperledger/fabric/orderer/consensus/etcdraft.(*Chain).Start 
[e][OrdererOrg.orderer1] /home/vsts/work/1/fabric/orderer/consensus/etcdraft/chain.go:368 +0x22f
```
**Failing Builds:**
1. https://dev.azure.com/Hyperledger/Fabric/_build/results?buildId=45519&view=logs&j=f2000854-c7fb-5d20-d92e-ea22102e0eb5&t=8c0b343e-a113-5c44-d189-698811f88d80
2. https://dev.azure.com/Hyperledger/Fabric/_build/results?buildId=44731&view=logs&j=f2000854-c7fb-5d20-d92e-ea22102e0eb5&t=8c0b343e-a113-5c44-d189-698811f88d80

as per stack frame line no. it is failing here:

https://github.com/hyperledger/fabric/blob/752853701709ce1d5d88db572cacf224ed0e4bd8/orderer/consensus/etcdraft/chain.go#L1147

Based on observation,  block data is empty array which could the reason for the SEGV while dereferencing the entry data as block `b.Header.Number`

```
[e][OrdererOrg.orderer3] 2021-12-30 11:21:21.537 UTC 0041 INFO [orderer.consensus.etcdraft] apply -> DEBUG block raw data:{Term:5 Index:19 Type:EntryNormal Data:[] XXX_unrecognized:[]} channel=systemchannel node=3
```

@guoger It is block type of `EntryNormal`,  can this type of raft entry be empty data & what conditions it can be empty?

In pipeline, it fails randomly. But I see the entry is empty every time with this scenario (ttps://github.com/hyperledger/fabric/blob/752853701709ce1d5d88db572cacf224ed0e4bd8/integration/raft/cft_test.go#L257). This raft entry received just after the orderer restart.  

I confirmed through adding few debug statements above if block. like below:

```
	c.logger.Infof("DEBUG block raw data:%+v", ents[position])
	b := protoutil.UnmarshalBlockOrPanic(ents[position].Data)
	c.logger.Infof("DEBUG %+v\n", b)

	if c.accDataSize >= c.sizeLimit {
```

**Comment by tock-ibm** [comment]
Maybe the problem is that `c.sizeLimit` changes?

The field `c.accDataSize` only changes when an entry with Data is encountered, so the other suspect would be the other side of the `if c.accDataSize >= c.sizeLimit {`

The field `c.sizeLimit` is written only in `NewChain` and `detectConfChange`
`detectConfChange` is called inside `commitBlock` which is called inside `catchUp`; that happens when a node syncs with a peer.... maybe it's worth checking the update model there

`sizeLimit` might have changed outside the `apply()`, and even though `apply()` did not encounter a data block (that can happen), the snapshot creation part was triggered?

to protect against that you simply need to augment the if:
`if c.accDataSize >= c.sizeLimit && <the data pointed by position is not nil>`

@yacovm @Param-S

**Comment by Param-S** [comment]
@tock-ibm 
> Maybe the problem is that c.sizeLimit changes?

Sorry, I am not sure what changes are referenced here. As per my understanding, sizeLimit is fixed value from chain struct/config. 

is raft message/entry with empty data array valid? what conditions raft send these messages? is it send by application?

```
{Term:5 Index:19 Type:EntryNormal Data:[] XXX_unrecognized:[]}
```

**Comment by tock-ibm** [comment]
1. Yes, a raft entry w/o data is valid.
2. I think a config tx can dynamically change the sizeLimit. Thus, a catchUp with another peer that fetches that config block and brings this into effect during the sync would change that. 

I think it is worth checking if that is the case.

**Comment by Param-S** [comment]
> 2. I think a config tx can dynamically change the sizeLimit. Thus, a catchUp with another peer that fetches that config block and brings this into effect during the sync would change that.
> I think it is worth checking if that is the case.

sizeLimit is not changed in this case.  This is the complete broadcast response msg where SoftState is nil & no. of committedEntries=1(entry’s Data field is empty array)

**Comment by Param-S** [comment]
When the failing orderer restarted, it received initial set of entries from the other orderer(in this case orderer3). In that, there were few data blocks present which got committed. Hence the initial values were `appliedIndex:8 sizeLimit:1024 accDataSize:63815` (just after restart, after sync with orderer)

```
[e][OrdererOrg.orderer1] 2022-01-04 18:33:01.023 UTC 0027 INFO [orderer.consensus.etcdraft] start -> Restarting raft node channel=systemchannel node=1
[e][OrdererOrg.orderer1] 2022-01-04 18:33:01.023 UTC 0028 INFO [orderer.consensus.etcdraft] becomeFollower -> 1 became follower at term 3 channel=systemchannel node=1
[e][OrdererOrg.orderer1] 2022-01-04 18:33:01.037 UTC 002e INFO [orderer.consensus.etcdraft] run -> DEBUG signal apply 8 <nil> {SoftState:<nil> HardState:{Term:3 Vote:1 Commit:8 XXX_unrecognized:[]} ReadStates:[] Entries:[] Snapshot:{Data:[] Metadata:{ConfState:{Nodes:[] Learners:[] XXX_unrecognized:[]} Index:0 Term:0 XXX_unrecognized:[]} XXX_unrecognized:[]} CommittedEntries:[{Term:1 Index:1 Type:EntryConfChange Data:[8 0 16 0 24 1] XXX_unrecognized:[]} {Term:1 Index:2 Type:EntryConfChange Data:[8 0 16 0 24 2] XXX_unrecognized:[]} {Term:1 Index:3 Type:EntryConfChange Data:[8 0 16 0 24 3] XXX_unrecognized:[]} {Term:2 Index:4 Type:EntryNormal Data:[] XXX_unrecognized:[]} {Term:2 Index:5 Type:EntryNormal Data:[ …..
[e][OrdererOrg.orderer1] 2022-01-04 18:33:01.039 UTC 0034 INFO [orderer.consensus.etcdraft] apply -> DEBUG updated value of position=4 and accDataSize:33788 channel=systemchannel node=1
[e][OrdererOrg.orderer1] 2022-01-04 18:33:01.040 UTC 0037 INFO [orderer.consensus.etcdraft] apply -> DEBUG updated value of position=6 and accDataSize:63815 channel=systemchannel node=1
```

> if c.accDataSize >= c.sizeLimit {
>     select {
>     case c.gcC <- &gc{index: c.appliedIndex, state: c.confState, data: ents[position].Data}:
>       c.logger.Infof(“Accumulated %d bytes since last snapshot, exceeding size limit (%d bytes), “+
>         “taking snapshot at block [%d] (index: %d), last snapshotted block number is %d, current nodes: %+v”,
>         c.accDataSize, c.sizeLimit, b.Header.Number, c.appliedIndex, c.lastSnapBlockNum, c.confState.Nodes)
>       c.accDataSize = 0
>       c.lastSnapBlockNum = b.Header.Number
>       c.Metrics.SnapshotBlockNumber.Set(float64(b.Header.Number))
>     default:
>       c.logger.Warnf(“Snapshotting is in progress, it is very likely that SnapshotIntervalSize is too small”)
>     }
>   }

I think the channel c.gcC was not ready, hence default case got executed.

```
[e][OrdererOrg.orderer1] 2022-01-04 18:33:01.045 UTC 003e WARN [orderer.consensus.etcdraft] apply -> Snapshotting is in progress, it is very likely that SnapshotIntervalSize is too small channel=systemchannel node=1
```

When next time new block with empty data array received, the channel was ready but the block is not complete hence it resulted into PANIC condition.

```

[e][OrdererOrg.orderer1] 2022-01-04 18:33:09.534 UTC 0058 INFO [orderer.consensus.etcdraft] run -> DEBUG signal apply 1 <nil> {SoftState:<nil> HardState:{Term:5 Vote:3 Commit:20 XXX_unrecognized:[]} ReadStates:[] Entries:[] Snapshot:{Data:[] Metadata:{ConfState:{Nodes:[] Learners:[] XXX_unrecognized:[]} Index:0 Term:0 XXX_unrecognized:[]} XXX_unrecognized:[]} CommittedEntries:[{Term:5 Index:20 Type:EntryNormal Data:[] XXX_unrecognized:[]}] Messages:[{Type:MsgAppResp To:3 From:1 Term:5 LogTerm:0 Index:20 Entries:[] Commit:0 Snapshot:{Data:[] Metadata:{ConfState:{Nodes:[] Learners:[] XXX_unrecognized:[]} Index:0 Term:0 XXX_unrecognized:[]} XXX_unrecognized:[]} Reject:false RejectHint:0 Context:[] XXX_unrecognized:[]}] MustSync:false} channel=systemchannel node=1
```

**Comment by Param-S** [comment]
consistently the issue can be reproduced with the testcase if we introduce an delay in snapshot routine startup.

> func (c *Chain) gc() {
> 	c.logger.Infof("DEBUG: delaying the snap shotter")
> 	**time.Sleep(1000 * time.Millisecond)**
> 	c.logger.Infof("DEBUG: the snap shotter is ready to listen")
> 	for {
> 		select {
> 		case g := <-c.gcC:

**Comment by shivdeep-singh-ibm** [comment]
In the function `(c *Chain) apply` , [this code](  https://github.com/hyperledger/fabric/blob/7b7b6e9248b77be956025cf56eec3e7799f17c72/orderer/consensus/etcdraft/chain.go#L1143) is not properly protected and can lead to a  segmentation fault, because at position=0, the entry.Type is ambiguous it can be either of {`raftpb.EntryNormal`, `raftpb.EntryConfChange`}, but this line tries to unmarshal it , assuming entry Type to be  `raftpb.EntryConfChange`. So we can prevent a seg fault if we do something like:

```
isNormalEntry := ents[position].Type == raftpb.EntryNormal
isEmpty := len(ents[position].Data) == 0

if c.accDataSize >= c.sizeLimit && (isNormalEntry && !isEmpty) {
		b := protoutil.UnmarshalBlockOrPanic(ents[position].Data)
```
So, we need to unmarshal data to a block only in case of `raftpb.EntryNormal` if position=0.
