### ISSUE TITLE
Error modifying Fabcar chaincode on Hyperledger Fabric

### ISSUE THREAD

**Issue by luismcortestirado** [hyperledger/fabric#3180]
good morning, I have modified some parameters of the FabCar chaincode in Java and launched it on my private network. When I invoke the chaincode with initLedger I get the following error:

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

I have added the following line in the build.gradle file in the dependencies section:

`compileOnly 'org.slf4j:slf4j-nop:1.7.32'`

Afterwards, I ran "`./gradlew installDist`" again successfully, but when invoking the chaincode I still get the same error. Does anyone know what could be the cause of this error? Thanks

**Comment by denyeart** [comment]
This repo's issues are intended for core Fabric code bugs.
For samples and usage questions, please see https://hyperledger-fabric.readthedocs.io/en/latest/CONTRIBUTING.html#getting-help.
