### ISSUE TITLE
error: scripts/createChannel.sh: line 40: osnadmin: command not found

### ISSUE THREAD

**Issue by joe-cryptosecurellc** [hyperledger/fabric#3192]
Using 2.2.4 and 1.5.2 HLF framework: ./network,sh up works, but when I run "./network.sh createChannel" I get the error.

Using 2.2.2 and 1.4.9 works (does not use osnadmin - it uses peer to create the channel).

Question: Is the 2.2.4/1.5.2 combination invalid? 

Thanks for your help.

**Comment by denyeart** [comment]
The v2.2 doc, v2.2 downloads, and v2.2 samples work together.
The main/latest doc, downloads, and samples work together.
Mix and match does not work since latest samples use osnadmin which was introduced in v2.3.

**Comment by joe-cryptosecurellc** [comment]
Yes - I now understand that - however the docs explicitly show using this combination as 2.2.4 (which was not found - defaulted to main, or 2.4) and 1.5.2.
