### ISSUE TITLE
Managing Certs documentation

### ISSUE THREAD

**Issue by joshhus** [hyperledger/fabric#3195]
Based on the Managing Certs workgroup.

**Comment by joshhus** [comment]
- Initial working draft - https://docs.google.com/document/d/1X6khMyedn0lGXeKDwbYjO-9fm_nXdf1CbVIncxYE4go/edit
- There are 2 categories of certs doc work - short-term and long-term.
- Planning notes, reqs, and ideas - https://docs.google.com/document/d/1Cq08W3IVlXzTNyJxeZLcTnzdJaYcIgXqxPzN1XcIeWA/edit

**Comment by joshhus** [comment]
Question - when ready to open up certs to a community call? 

Working outline and status:

1. Certs - what are they and their purpose / requirement in Fabric **- joshh - drafted**
2. Certs relationships to CA-created identities and their public and private keys
3. Cert mgmt. authorized user roles - for network/channel certs, org certs, user/app certs. 
4. Two types of Certs - MSP and TLS - and the dual-headed CA (one does both, TLS first)
5. Certs Lifecycle e2e - Includes Issue, Renew, Revoke, and link to how to do them. 
6. Chris’ reference table with certs types and locations etc. **- chrise - drafted**
7. Best Practices. Don’t let them expire, etc. 
8. Troubleshooting 
9. Help, support & references - including glossary / definitions of enrollment, registration, issue, renew, etc.
10.

**Comment by joshhus** [comment]
Status 1/31 - @denyeart 
- Need the certs table 
- Need steps / how-to for the managing certs scenarios - see candidates under section 5 here - https://docs.google.com/document/d/1X6khMyedn0lGXeKDwbYjO-9fm_nXdf1CbVIncxYE4go/edit
- The rest I should be able to draft myself

**Comment by joshhus** [comment]
Several commits and reviews have happened, should be close to good to go -- PR https://github.com/hyperledger/fabric/pull/3307 
Next will create a new issue - managing revoked and expired certs.

**Comment by joshhus** [comment]
@jkneubuh to review
@c-elder

**Comment by denyeart** [comment]
Managing Certs doc has been merged.
We can open a new issue to handle next extensions such as managing expired certs.
