### ISSUE TITLE
New Feature proposal - Token-ERC-721 in GO

### ISSUE THREAD

**Issue by msalimbene** [hyperledger/fabric#3206]
Hello,

I've translated the code from token-erc-721 from JS (the only version available now) to golang. I got a full implementation, along with unit tests. I kept the same comments as in the JS version, and following the README.md instructions, anyone could choose whether to use JS or GO. I have the code ready and fully tested with said instructions.

I'd like to contribute this code, how can I proceed?
Thank you

**Comment by yacovm** [comment]
You are welcome to contribute it, but not to this repository. This repository holds the Fabric core (orderer and peer) and tokens is business logic, not infrastructure. 

You can take a look at [fabric-samples](https://github.com/hyperledger/fabric-samples) repository, which holds examples.

Alternatively you can contribute the code to the [fabric-token-sdk](https://github.com/hyperledger-labs/fabric-token-sdk) which is an evolving project that lets you do token exchange and asset management over Fabric and other blockchains.

**Comment by msalimbene** [comment]
Right, I intended to post this on fabric samples, my bad. Thanks for your prompt response.
