### ISSUE TITLE
peer channel command --tlsHandshakeTimeShift flag doesn't work

### ISSUE THREAD

**Issue by afrancoc2000** [hyperledger/fabric#3239]
Hi, 

I have an issue with my certificates so I needed to use the --tlsHandshakeTimeShift flag to be able to update my certificates but the flag doesn't work.

This is what  I tried:

    peer channel list --tlsHandshakeTimeShift 96h
    2022-02-18 06:31:55.132 -05 0001 ERRO [main] InitCmd -> Cannot run peer because error when setting up MSP of type bccsp from directory D:\Workspace\epm\certificates\reales\certificados-np-2022\testing-client\adminold\msp: signing identity expired 42h50m54.1317605s ago

As you can see the time shift is smaller that my certificates expired duration but it still doesn't work.

I have the same problem using peer channel update

    peer channel update -f configtestchainidUpdate.pb -c testchainid -o ${ORDERER_ADDRESS} --tls --cafile ${ORDERER_TLS_CA} --clientauth --certfile $ADMIN_TLS_CERTFILE --keyfile $ADMIN_TLS_KEYFILE --tlsHandshakeTimeShift 96h
    2022-02-18 06:37:19.121 -05 0001 ERRO [main] InitCmd -> Cannot run peer because error when setting up MSP of type bccsp from directory D:\Workspace\epm\certificates\reales\certificados-np-2022\testing-client\adminold\msp: signing identity expired 42h56m18.1211724s ago

I'm using the latest binaries for peer:

    $ peer version
    peer:
     Version: 2.4.2
     Commit SHA: fad7f691a
     Go version: go1.17.5
     OS/Arch: windows/amd64
     Chaincode:
      Base Docker Label: org.hyperledger.fabric
      Docker Namespace: hyperledger

**Comment by yacovm** [comment]
The TLS handshake timeshift only governs the TLS handshake. The error you are experiencing is related to signing identities. 
Just issue a new identity for your admin and then use it to do the channel update.

**Comment by afrancoc2000** [comment]
The issue with the admin is that I don't use node OUs so, it only recognizes the admins in the block configuration 😓. I have a new certificate in the admins folder for the orderers and peers but using it I get this message:

peer channel update -f configtestchainidUpdate.pb -c testchainid -o ${ORDERER_ADDRESS} --tls --cafile ${ORDERER_TLS_CA} --clientauth --certfile $ADMIN_TLS_CERTFILE --keyfile $ADMIN_TLS_KEYFILE
2022-02-18 13:22:30.114 UTC [channelCmd] InitCmdFactory -> INFO 001 Endorser and orderer connections initialized
Error: got unexpected status: BAD_REQUEST -- error applying config update to existing channel 'testchainid': error authorizing update: error validating DeltaSet: policy for [Value]  /Channel/Consortiums/SampleConsortium/epm/MSP not satisfied: signature set did not satisfy policy

So I guess I need to use the admin certificate inside the config but that one is expired.

**Comment by yacovm** [comment]
Then try to change the local time on the machine you use to send the channel config update

**Comment by afrancoc2000** [comment]
ok, I'll do that, thanks!!!
