### ISSUE TITLE
How to resolve configuration blocks

### ISSUE THREAD

**Issue by chaunsin** [hyperledger/fabric#3261]
May I ask how I parse the configuration block? I want to know what the structure of the configuration block is. The configuration block is different from the ordinary block. thank you

**Comment by taras-hk** [comment]
@chaunsin You can use `configtxlator` for this.

A sample command looks like this:
```
configtxlator proto_decode --input config_block.pb --type common.Block --output config_block.json
```

More details about this tool you can find [here](https://github.com/hyperledger/fabric/blob/main/docs/source/commands/configtxlator.md#configtxlator-proto_decode)

**Comment by chaunsin** [comment]
> @chaunsin You can use `configtxlator` for this.
> 
> A sample command looks like this:
> 
> ```
> configtxlator proto_decode --input config_block.pb --type common.Block --output config_block.json
> ```
> 
> More details about this tool you can find [here](https://github.com/hyperledger/fabric/blob/main/docs/source/commands/configtxlator.md#configtxlator-proto_decode)

tks
