### ISSUE TITLE
Change RocketChat to Discord

### ISSUE THREAD

**Issue by joshhus** [hyperledger/fabric#3270]
Update chat tool symbols on docs site: 

Change Rocket icon on main TOC to Discord - https://hyperledger-fabric.readthedocs.io/en/latest/index.html

Same for "Rocket Chat" text link at the CA URL - https://hyperledger-fabric-ca.readthedocs.io/en/latest/

https://chat.hyperledger.org/home

![image](https://user-images.githubusercontent.com/16542757/157307467-00b744b3-c0b5-46bf-8b65-84375e22a7cf.png)

**Comment by joshhus** [comment]
![image](https://user-images.githubusercontent.com/16542757/157308075-cb2a879d-438f-47b7-baf6-b1b545953eaa.png)

**Comment by joshhus** [comment]
@denyeart I think you said there was a PR with a new icon etc. for me to look at? Can you paste the PR here.

**Comment by AyushRaj8271** [comment]
Hey @joshhus ! This is Ayush, I am reall y interested into work on this PR . Is this still available ? Can you assign this PR to me?

**Comment by denyeart** [comment]
The RocketChat to Discord PR is at https://github.com/hyperledger/fabric/pull/3296.
The only thing remaining is to fix up the Discord graphic to match the color scheme of the other icons.

**Comment by joshhus** [comment]
> Hey @joshhus ! This is Ayush, I am reall y interested into work on this PR . Is this still available ? Can you assign this PR to me?

@AyushRaj8271 Thanks for your interest! We have a new Discord icon already. However the dimensions are a bit off compared to the Discord original, which is not the image file, but rather in the rendering (.md/HTML) if you want to check that out.

Likewise we need "Rocketchat" replaced with Discord here, with the updated link to Discord - https://hyperledger-fabric-ca.readthedocs.io/en/latest/

**Comment by sheetalj2205** [comment]
Hey, @joshhus I want to work on this issue, I'll replace the Rocketchat with Discord in this doc https://hyperledger-fabric-ca.readthedocs.io/en/latest/. Can you please assign this to me?

**Comment by denyeart** [comment]
Done in https://github.com/hyperledger/fabric/pull/3296
