### ISSUE TITLE
Language fixes - docs

### ISSUE THREAD

**Issue by joshhus** [hyperledger/fabric#3271]
Issue to collect one-off language etc. fixes when found to address in one PR: 

"have" ---> "having"

![image](https://user-images.githubusercontent.com/16542757/157331850-3e2ff9eb-1777-43a0-8624-0b9bceabf5f4.png)

**Comment by joshhus** [comment]
"deployements" typo -- 

![image](https://user-images.githubusercontent.com/16542757/157513104-d6234e6a-d8c8-4960-a080-624579f2e1a1.png)

**Comment by joshhus** [comment]
I think these "2.0" should all be "2.x" -- throughout the 2.4 docs likely. Unlikely anything is specific to only 2.0. 

![image](https://user-images.githubusercontent.com/16542757/157516071-73f25c66-4fba-4463-b351-8ff5bc229bc6.png)

**Comment by joshhus** [comment]
A number of : colon chars missing to lead in to lists, just punctuation: 
https://hyperledger-fabric.readthedocs.io/en/latest/cc_service.html

**Comment by ggold7046** [comment]
Hi, I'm interested in this fix. Could anyone tell me more about missing colon characters ? Should I check all the docs for typos or it is a single page ?

**Comment by denyeart** [comment]
@ggold7046 Go ahead and fix any issues you see. I doubt anybody is going to provide a list of all doc typos to fix, it is simpler to just fix them as you come across them.

**Comment by Sayalikukkar** [comment]
Hi @denyeart  I would like to contribute on this. Let me know if I can start.

**Comment by denyeart** [comment]
@Sayalikukkar Yes go ahead and submit a PR for any doc fixes.

**Comment by gadeShivani** [comment]
Hi, I would like to contribute. Please let me know if I can start on anything specific as new to this.

Thank you

**Comment by jaywonger** [comment]
Hi, would like to contribute to this. 

Thanks
