### ISSUE TITLE
Content updates - docs

### ISSUE THREAD

**Issue by joshhus** [hyperledger/fabric#3276]
Do we still want to call this "new"? It may be the new "Fabric" lifecycle in v.2.0. but it's not the latest "Transaction" lifecycle (which is new in 2.4 with new Fabric Gateway service). May just need changing from "new" to "v2.x" with caveat that Tx lifecycle changed in 2.4.

https://hyperledger-fabric.readthedocs.io/en/latest/chaincode_lifecycle.html#migrate-to-the-new-fabric-lifecycle

![image](https://user-images.githubusercontent.com/16542757/157509696-4ea702f9-2567-4941-9ff6-150eff0202b7.png)

**Comment by joshhus** [comment]
"new" for 2.0 may be problematic language for the "latest" (2.4) release docs and moving fwd. Depends on reader interpretation of "new". I don't think the "chaincode" lifecycle per se changed in 2.4 however, only Tx / gateway.
https://hyperledger-fabric.readthedocs.io/en/latest/enable_cc_lifecycle.html

![image](https://user-images.githubusercontent.com/16542757/157512191-68dc9b82-e905-4cb8-b669-a20ecb03a1c9.png)

**Comment by Akshit42-hue** [comment]
Hi, I am Axit, a contributor to OpenForce 2022. I would like to work on this issue. I would be making a PR as soon as I am done with resolving the issue. @joshhus
