### ISSUE TITLE
Graphics and diagrams updates - docs

### ISSUE THREAD

**Issue by joshhus** [hyperledger/fabric#3278]
For example, this one is pending / working: 

https://hyperledger-fabric.readthedocs.io/en/release-2.4/getting_started.html

![image](https://user-images.githubusercontent.com/16542757/157545894-b070fee2-75b7-4296-9c02-2244311268c2.png)

Others can be added and worked in this issue.

**Comment by joshhus** [comment]
https://github.ibm.com/WCE-ID/Content-Design/issues/386

**Comment by joshhus** [comment]
https://github.com/hyperledger/fabric/issues/3278

**Comment by AliakbarETH** [comment]
Hi @joshhus I have seen issue number #3278 opened whereas at the bottom the issue is closed.

Is the work done or needs some improvements?

Let me know.

Regards

**Comment by denyeart** [comment]
It is resolved now, closing.
