### ISSUE TITLE
Update copyright year

### ISSUE THREAD

**Issue by joshhus** [hyperledger/fabric#3279]
For newly published pages.
e.g. 
https://hyperledger-fabric.readthedocs.io/en/latest/getting_started.html

![image](https://user-images.githubusercontent.com/16542757/157671074-7ae3f7aa-eb3b-4a7a-8670-207a221deab2.png)

**Comment by SHIKHER09** [comment]
hello, Can I work on it

**Comment by joshhus** [comment]
> hello, Can I work on it

Sure, I'm not sure how it populates or what the rules are - only when a page is updated, only for updated pages, or if it's needed on every page regardless of updates.

**Comment by SHIKHER09** [comment]
> > hello, Can I work on it
> 
> Sure, I'm not sure how it populates or what the rules are - only when a page is updated, only for updated pages, or if it's needed on every page regardless of updates.

I searched about it and I found that we only need to update  updated pages only

**Comment by joshhus** [comment]
@SHIKHER09 Okay I think it's automated in the build - publishing the date at the bottom. So perhaps we just need to change it in some config file to "2020-2022" for v. 2.4 docs. 

Earlier versions should have earlier dates I would think.

**Comment by Akshit42-hue** [comment]
Can I work on this issue? @joshhus

**Comment by joshhus** [comment]
I think the home page for latest / 2.4 should say 2020-2022. 
@SHIKHER09 you can PR this, or defer to @Akshit42-hue if you are busy thanks!

**Comment by joshhus** [comment]
1. ey I took liberty to get this in the build queue -- 
2. for example - https://hyperledger-fabric--3307.org.readthedocs.build/en/3307/certs_management.html ... 
3. source file is in /source/_templates/footer.html
4. for doc collections, the standard is a range of years, such as 2020-2022 for Fabric 2.4.
