### ISSUE TITLE
Add ccaas builder to the release tarballs

### ISSUE THREAD

**Issue by jt-nti** [hyperledger/fabric#3286]
It would be useful to include the "built-in" Chaincode As A Server builder in the release tarballs. The packages currently contain...

```
/bin
/config
```

I propose adding a new directory for builders, i.e.

```
/bin
/builders
/builders/ccaas
/config
```

**Comment by mbwhite** [comment]
Updated in PR#3315

**Comment by jt-nti** [comment]
It would be good to get #3315 finished since the latest release has `/bin/ccaas_builder/bin` which is a bit odd

**Comment by denyeart** [comment]
Merged and backported.
