### ISSUE TITLE
Is Docker the only built-in way to build chaincode?

### ISSUE THREAD

**Issue by penumbra23** [hyperledger/fabric#3290]
Hi everyone!

First of all, thanks for the awesome work you put in here! :clap:

We're using the built-in way of installing the chaincode since `v1.4.3` where the peer builds and deploys the chaincode container via `CORE_VM_ENDPOINT` env variable.

We're migrating now to K8s 1.23+ and preparing for the deprecation of Docker (now it's using `containerd` with `runc` as the default runtime). This is now getting a real hard-stuck brick wall for us, so I wanted to ask:

1. Is there a light, easy and set-this-env-var way to make this possible?
2. If not 1), can we utilize the external builder support in HLF v2+ to make it work with `containerd` and if yes, does anyone have some guidelines or similar scripts?
3. If not 1) or 2), any other smarter solution that doesn't involve chaincode-as-a-service and deploying external containers manually?

Thanks for your time!

**Comment by yacovm** [comment]
@mbwhite  @jkneubuh

**Comment by mbwhite** [comment]
Hello @penumbra23  - thanks for you comments!

1) I don't think that there is a lightweight way to achieve this. The peer, by default is, going to try and contact the docker daemon to build and start processes. 

Only by running docker-in-docker or something similar does the Peer orchestrating the images work  in K8S.  

2) For the external builder support. This does allow great flexibility in how the containers are built when requested to do so via the peer.  The down side is that this has be custom written. Not aware of many people that have done this, one, maybe two.  

3) For running in K8S, as shown in the test-network-k8s in fabric-samples the preferred route is to run the chaincode-as-a-service. 

We've made a number of improvements to make this process easier - and if there are other things we can do we'd be interested to hear. Is it the deploying the containers for the chaincode that is the sticking point?

**Comment by penumbra23** [comment]
@mbwhite Thanks for your response!

As far as the external builder support goes, can it actually be set up so that it allows another container runtime to be built in OR is Docker the only way the peer builds the chaincode containers?

Regarding dind, I already managed to create a peer pod with a dind sidecar and it works (at least on the first glance, need to do more testing).

The problem for us is that we migrated to K8s 1.23 and to `containerd` as the runtime, but our Hyperledger infrastructure uses the built-in chaincode builder (`CORE_VM_ENDPOINT` must be set to Docker daemon socket).

**Comment by mbwhite** [comment]
@penumbra23 

for the builtin support the Peer only knows about talking to the docker daemon; so for K8S you can easily disable that and use the external builder approach. Here the peer calls out to a (configured) set of binaries that take on the responsibility of building and deploying the chaincode. In whatever manner they wish - the peer really doesn't care how it's done, so long the chaincode is started.  With any external builder approach, the peer doesn't do anything with docker or any other container runtime.

Fabric 2.4 comes with a set of pre-built external chaincode binaries to support Chaincode-as-a-service 'out of the box'.

**Comment by penumbra23** [comment]
Okay, that seems like the way-to-go for us too. 
@mbwhite Thanks for the info! Helped a lot!

**Comment by jkneubuh** [comment]
Hi @penumbra23 

Something to be aware of in this area is that the `core.vm.endpoint` attribute must be _removed_ from your peer core.yaml configuration file.  If this attribute is present (even if null) the peer will attempt to connect to a local Docker daemon.

**Comment by penumbra23** [comment]
Thanks @jkneubuh for the info, didn't know about that since it wasn't in my core.yaml file 😄

**Comment by jkneubuh** [comment]
Whoops!

`vm.endpoint`  (mapping to CORE_VM_ENDPOINT in the peer env)

**Comment by uqix** [comment]
Tips about using ccaas for bevel users:

1. build custom peer image with `vm.endpoint` commented out in `/etc/hyperledger/fabric/core.yaml`
2. remove `CORE_VM_ENDPOINT: unix:///host/var/run/docker.sock` in `platforms/hyperledger-fabric/charts/peernode/templates/configmap.yaml`
