### ISSUE TITLE
exploring the purpose of inactive chain in `orderer/consensus`

### ISSUE THREAD

**Issue by shivdeep-singh-ibm** [hyperledger/fabric#3293]
In `fabric/orderer` the `consensus` directory  holds various pluggable consensus implementations. Currently the consensus implementations  in the  `orderer/consensus/` directory are {etcdraft, kafka, solo, **inactive**}. 
This issue is created to understand the purpose of **inactive chain**. 

Seeks to address questions like:
- whether it is required only in the case of channel participation apis / system channel?
- whether it can be removed  or refactored?

**Comment by yacovm** [comment]
>  This issue is created to understand the purpose of inactive chain.

You can look at [git blame](https://github.com/hyperledger/fabric/blame/main/orderer/consensus/inactive/inactive_chain.go) and see the [commit](https://github.com/hyperledger/fabric/commit/a8a509460564e452ad6d58c0512d1d844ede0802) in which it was introduced.

The purpose of the inactive chain is to support a use case where an orderer is not part of a channel, but you don't want to return "this channel does not exist" to a client, so you have a dummy channel instance that returns a different message.
