### ISSUE TITLE
Unit test failure in TestEtcdraft

### ISSUE THREAD

**Issue by denyeart** [hyperledger/fabric#3294]
Seeing this failure in local environment:

{"level":"debug","msg":"Creating snapshot at index 7 from MemoryStorage","channel":"multi-node-channel","node":1}
{"level":"info","msg":"Persisting snapshot (term: 2, index: 7) to WAL and disk","channel":"multi-node-channel","node":1}
{"level":"info","msg":"Applied config change to remove node 3, current nodes in channel: [1 2]","channel":"multi-node-channel","node":3}
{"level":"info","msg":"This node is being removed from replica set","channel":"multi-node-channel","node":3}
{"level":"info","msg":"Raft node stopped","channel":"multi-node-channel","node":3}
{"level":"info","msg":"Stop garbage collecting","channel":"multi-node-channel","node":3}
{"level":"info","msg":"Stop serving requests","channel":"multi-node-channel","node":3}
{"level":"info","msg":"Periodic check is stopping.","channel":"multi-node-channel","node":3}
{"level":"debug","msg":"Releasing lock to wal files prior to 7","channel":"multi-node-channel","node":1}
{"level":"info","msg":"Raft node stopped","channel":"multi-node-channel","node":1}
{"level":"info","msg":"Stop serving requests","channel":"multi-node-channel","node":1}
{"level":"info","msg":"Periodic check is stopping.","channel":"multi-node-channel","node":1}
{"level":"debug","msg":"Purging in-memory raft entries prior to 6","channel":"multi-node-channel","node":1}
{"level":"info","msg":"Snapshot is taken at index 7","channel":"multi-node-channel","node":1}
{"level":"debug","msg":"Snapshots on disk (3) < limit (4), no need to purge wal/snapshot","channel":"multi-node-channel","node":1}
{"level":"info","msg":"Stop garbage collecting","channel":"multi-node-channel","node":1}
{"level":"debug","msg":"Quit proposing blocks, discarded 0 blocks in the queue","channel":"multi-node-channel","node":1}
{"level":"info","msg":"Raft node stopped","channel":"multi-node-channel","node":2}
{"level":"info","msg":"Stop garbage collecting","channel":"multi-node-channel","node":2}
{"level":"info","msg":"Stop serving requests","channel":"multi-node-channel","node":2}
{"level":"info","msg":"Periodic check is stopping.","channel":"multi-node-channel","node":2}
Send artificial MsgTimeoutNow to elect node 1
STEP: order envelop on node 1 to accumulate bytes

------------------------------
• Failure [0.982 seconds]
Chain
/Users/enyeart/work/src/github.com/hyperledger/fabric/orderer/consensus/etcdraft/chain_test.go:101
  3-node Raft cluster
  /Users/enyeart/work/src/github.com/hyperledger/fabric/orderer/consensus/etcdraft/chain_test.go:1556
    when 3/3 nodes are running
    /Users/enyeart/work/src/github.com/hyperledger/fabric/orderer/consensus/etcdraft/chain_test.go:2479
      when Snapshotting is enabled
      /Users/enyeart/work/src/github.com/hyperledger/fabric/orderer/consensus/etcdraft/chain_test.go:2978
        take snapshot on accumlated bytes condition met [It]
        /Users/enyeart/work/src/github.com/hyperledger/fabric/orderer/consensus/etcdraft/chain_test.go:2984

        Expected
            <int>: 2
        to equal
            <int>: 3

        /Users/enyeart/work/src/github.com/hyperledger/fabric/orderer/consensus/etcdraft/chain_test.go:3056
------------------------------

Summarizing 1 Failure:

[Fail] Chain 3-node Raft cluster when 3/3 nodes are running when Snapshotting is enabled [It] take snapshot on accumlated bytes condition met 
/Users/enyeart/work/src/github.com/hyperledger/fabric/orderer/consensus/etcdraft/chain_test.go:3056

Ran 124 of 124 Specs in 68.138 seconds
FAIL! -- 123 Passed | 1 Failed | 0 Pending | 0 Skipped
--- FAIL: TestEtcdraft (68.16s)
2022-03-21 16:25:07.582 EDT 0046 INFO [test] Stop -> Periodic check is stopping.
FAIL
exit status 1
FAIL	github.com/hyperledger/fabric/orderer/consensus/etcdraft	82.570s

**Comment by jcastrence** [comment]
Getting the exact same failure in local environment as well. This failure occurs after merging commit [fix fabric/orderer unit test flake](https://github.com/hyperledger/fabric/commit/2fc323cb40e46ee524ab380e6160f89c40ba631e).

**Comment by shivdeep-singh-ibm** [comment]
The unittest is failing on some machines because it takes some (variable duration) time to write snapshots to disk and the *Expect* comparison happens while the write is still in progress, so we get wrong number of snapshots, which is less than the expected number. It is fixed by replacing *Expect* by *Eventually* which waits for some time to check the *expected* values.

**Comment by jkneubuh** [comment]
Looks like a fix has been merged.  Can this Issue be closed?  Thanks Shivdeep and Julian for tracking this down.
