### ISSUE TITLE
Improve error message when deliver service is asked for a block that doesn't yet exist on the node

### ISSUE THREAD

**Issue by denyeart** [hyperledger/fabric#3320]
Improve error message when deliver service is asked for a block that doesn't yet exist on the node.

This is all we get for now:
`[common.deliver] deliverBlocks -> ERRO 18d59 [channel: channel1] Error reading from channel, cause was: NOT_FOUND`

It is enough for Fabric developers to know what happened, but not for users or support personnel.

**Comment by ptippett** [comment]
Yep.  Ideally it'd be "Block xxxx not found"

**Comment by Aniket21mathur** [comment]
Hey @denyeart! I am new to Hyperledger foundation. I went through the contribution documentation and thus decided to start with a straightforward good first issue to get a little grasp of the project codebase. Since there is no one assigned to this issue, I would like to work on it. 

Thanks!

**Comment by IT-dragon** [comment]
Can you explain in detail the reason for this error (I also encountered this problem) I would like to know when this error will occur and will it affect the operation of the chain
