### ISSUE TITLE
Update to Go 1.18.10 in all Fabric repositories

### ISSUE THREAD

**Issue by musinit** [hyperledger/fabric#3341]
Hey, looks like we can update all the stuff to the latest version?

**Comment by denyeart** [comment]
Main branch updated to Go 1.18.2:
https://github.com/hyperledger/fabric/pull/3404

Will do back releases next.

**Comment by SamYuan1990** [comment]
are we plan to use any go 1.18 new features ?

**Comment by SamYuan1990** [comment]
@denyeart , please take a look at 
https://github.com/hyperledger/fabric/blob/main/go.mod#L3

**Comment by denyeart** [comment]
Not planning to use any Go 1.18 features at the moment, but I'll plan on updating go.mod so that we can.
Note that the build has already been updated to use Go 1.18.

**Comment by denyeart** [comment]
Still need to update go.mod Go version.
Also need to check Go version in all other Fabric repositories.

**Comment by SamYuan1990** [comment]
> Still need to update go.mod Go version. Also need to check Go version in all other Fabric repositories.

and it seems we have go lang 1.19 for now? we will upgrade to 1.19?

**Comment by denyeart** [comment]
Go 1.19 requires some additional updates and is tracked in #3661

**Comment by denyeart** [comment]
I'll use this issue to ensure that all Fabric ecosystem repositories are at least at 1.18.8

**Comment by SamYuan1990** [comment]
https://github.com/Hyperledger-TWGC/fabric-admin-sdk/blob/main/go/go.mod#L3 admin sdk use golang version 1.18 for now.

**Comment by denyeart** [comment]
Done.
