### ISSUE TITLE
Hyperledger Fabric cryptogen and configtxgen not working

### ISSUE THREAD

**Issue by MekkiNassreddine** [hyperledger/fabric#3385]
I am trying to create the "crypto matrial" of my hyperledger fabric network using the cryptogen command line but I get "command not found" as result

My command line : user@ubuntu:~/go/src/github.com/*****/fabric-samples/bin$ cryptogen generate --config=./crypto-config.yam cryptogen: command not found

Please i need help

**Comment by denyeart** [comment]
Make sure cryptogen is in your PATH.
