### ISSUE TITLE
Hyperledger Fabric - Chaincode sample with Javascript

### ISSUE THREAD

**Issue by gunshukla** [hyperledger/fabric#3438]
Hello, I was trying to run Javascript Chaincode on my Macbook and came up with below error. Any direction or guidance will be great.

Error: chaincode install failed with status: 500 - failed to invoke backing implementation of 'InstallChaincode': could not build chaincode: docker build failed: docker image build failed: docker build failed: Failed to pull hyperledger/fabric-nodeenv:2.4: no matching manifest for linux/arm64/v8 in the manifest list entries
Chaincode installation on peer0.org1 has failed
Deploying chaincode failed

**Comment by jt-nti** [comment]
Hi @gunshukla, unfortunately arm64 support is not complete in Fabric, and there's an open issue #2994. You might be able to get further by using the chaincode as an external service approach instead of the built-in Node.js chaincode builder.

**Comment by davidkel** [comment]
@gunshukla another thing you could try is to pull down the the amd64 version manually `docker pull hyperledger/fabric-nodeenv:amd64-2.4.2` and retag it as `2.4`

**Comment by stinct9** [comment]
> @gunshukla another thing you could try is to pull down the the amd64 version manually `docker pull hyperledger/fabric-nodeenv:amd64-2.4.2` and retag it as `2.4`

I was facing the same issue and this solution worked for me. Thanks!

**Comment by rafaelferr88** [comment]
> > @gunshukla another thing you could try is to pull down the the amd64 version manually `docker pull hyperledger/fabric-nodeenv:amd64-2.4.2` and retag it as `2.4`
> 
> I was facing the same issue and this solution worked for me. Thanks!

How do you do this retag?

**Comment by Huyenhuynhh** [comment]
same question. how do you retag it?

**Comment by bestbeforetoday** [comment]
You would  re-tag an image using the [docker tag](https://docs.docker.com/engine/reference/commandline/tag/) command. You might find it easier to just pull the correctly tagged version directly by telling Docker you want an amd64 image, as described in this issue: https://github.com/hyperledger/fabric/issues/2994#issuecomment-1170102505
