### ISSUE TITLE
Error in setting csr.cn parameter with docker

### ISSUE THREAD

**Issue by Kelkut** [hyperledger/fabric#3453]
When attempting to create an intermediate CA, it is necessary to set the CSR.CN value to empty. Using docker, this operation is not possible because, by setting the environment variable as an empty string, it is automatically replaced by the default value.

**Comment by denyeart** [comment]
Assuming this is a fabric-ca issue... please close here and re-open in https://github.com/hyperledger/fabric-ca/issues

**Comment by Kelkut** [comment]
You was right. It was a docker issue. Sorry for the error.
