### ISSUE TITLE
Just because you put "secure" in the URL doesn't mean it's secure.

### ISSUE THREAD

**Issue by Asday** [hyperledger/fabric#3480]
https://jira.hyperledger.org/secure/attachment/15836/cluster_test1.log

I imagine those are private keys created and destroyed during the process of running the unit tests, but still, who knows what else there might be in Jira's attachments that you don't want me to see.

**Comment by yacovm** [comment]
But these are unit tests, the private keys that are generated in them have no use anywhere else. 
Besides, I'm not sure why you're posting this to the Fabric core repository. This isn't a Fabric core issue, it is at most a JIRA issue. You should post it in JIRA.

**Comment by Asday** [comment]
'Cause there's a URL to this repository in the log, and I figured someone might care that a misconfiguration is potentially exposing sensitive information.  I'd like to know, as a server admin.

I guess crypto bros are a different breed to people who do useful work.  Crazy world out there.
