### ISSUE TITLE
Chaincode related questions

### ISSUE THREAD

**Issue by ACwatermelon** [hyperledger/fabric#3482]
The chain code I defined needs to include some external library files, which can only be downloaded in Ubuntu. 
How can I deploy the smart contract?

**Comment by ACwatermelon** [comment]
The method I want to implement in smart contracts only works in Ubuntu 20.04. How can I combine it with fabric?

**Comment by denyeart** [comment]
Please reserve github issues for actual code issues.
For questions please use mailing list or discord chat - https://hyperledger-fabric.readthedocs.io/en/latest/CONTRIBUTING.html#communications-and-getting-help

**Comment by denyeart** [comment]
For starters take a look at using external chaincode service - https://hyperledger-fabric.readthedocs.io/en/latest/cc_service.html
