### ISSUE TITLE
build/bin folder shows zero byte binaries

### ISSUE THREAD

**Issue by dchampak** [hyperledger/fabric#3510]
Hi

I have cloned 2.3.0 version and build using "make dist-clean all". Build is successful (disabling unit tests, integration tests).
In the build/bin folder binaries have been created, but they are all of zero byte size.  Could you please help in resolving this issue?

Purpose of this experiment:  I was trying to run fabric-samples and debug / study framework source with additional logs. To this end, I have downloaded samples, and am planning to replace binaries built by me to enable this activity. In the earlier versions I remember creating binaries this way, but now they appear to have zero bytes.

Looking for your king help.

Thanks

**Comment by dchampak** [comment]
This issue appears to get resolved by removing touch in below lines in Makefile:
$(BUILD_DIR)/bin/%:
        @echo "Building $@"
        @mkdir -p $(@D)
        GOBIN=$(abspath $(@D)) go install -tags "$(GO_TAGS)" -ldflags "$(GO_LDFLAGS)" $(pkgmap.$(@F))
        @touch $@

**Comment by arroselli** [comment]
> Hi
> 
> I have cloned 2.3.0 version and build using "make dist-clean all". Build is successful (disabling unit tests, integration tests).
> In the build/bin folder binaries have been created, but they are all of zero byte size.  Could you please help in resolving this issue?
> 
> Purpose of this experiment:  I was trying to run fabric-samples and debug / study framework source with additional logs. To this end, I have downloaded samples, and am planning to replace binaries built by me to enable this activity. In the earlier versions I remember creating binaries this way, but now they appear to have zero bytes.
> 
> Looking for your king help.
> 
> Thanks
