### ISSUE TITLE
Idemixgen was removed from the set of Fabric produced binaries but is still mentioned in ReadTheDocs

### ISSUE THREAD

**Issue by denyeart** [hyperledger/fabric#3575]
Idemixgen was removed from the set of Fabric produced binaries but is still mentioned in ReadTheDocs.

Need to scrub references of Idemixgen in Fabric ReadTheDocs since it is no longer provided in the set of Fabric binaries. Need to reference the new location at https://github.com/IBM/idemix/tree/main/tools/idemixgen.

Also mention in release notes for v2.4.x (Dave Enyeart can do this for you!)

**Comment by Sayalikukkar** [comment]
@denyeart , I am intrested to work on this, Can I start?

**Comment by denyeart** [comment]
@Sayalikukkar I've assigned to you, go ahead and start!

I'd recommend remove the content from https://github.com/hyperledger/fabric/blob/main/docs/source/idemixgen.rst and add it to
https://github.com/IBM/idemix/blob/main/README.md.
This will require a pull request in each repository. Thanks!
