### ISSUE TITLE
Reflecting Cross-site Scripting (XSS) Bug

### ISSUE THREAD

**Issue by bhaskarvilles** [hyperledger/fabric#3613]
Unsanitized input from the request body `r.body` flows into `fmt.Fprintln`, where it is used to render an HTML page returned to the user. This may result in a Reflected Cross-Site Scripting attack (XSS).

https://github.com/hyperledger/fabric/blob/f4ea5f79593000f278100654f530f2ca52194676/internal/configtxlator/rest/protolator_handlers.go#L50

**Comment by denyeart** [comment]
An error is returned rather than unsanitized input.
