### ISSUE TITLE
Cannot clone fabric repository

### ISSUE THREAD

**Issue by Gipnomanul** [hyperledger/fabric#3627]
Hello there. I am using Windows 10 with Docker and when doing basic curl command from documentation i get an error "fabric-samples v2.4.6 does not exist, defaulting to main. fabric-samples main branch is intended to work with recent versions of fabric.". Can someone help me with this problem?

Command i am using is:
`curl -sSL https://bit.ly/2ysbOFE | bash -s`

Output is:

`main: line 63: git: command not found
fabric-samples v2.4.6 does not exist, defaulting to main. fabric-samples main branch is intended to work with recent versions of fabric.
main: line 71: git: command not found

Pull Hyperledger Fabric binaries

===> Downloading version 2.4.6 platform specific fabric binaries
===> Downloading:  https://github.com/hyperledger/fabric/releases/download/v2.4.6/hyperledger-fabric-linux-amd64-2.4.6.tar.gz
main: line 80: curl: command not found
tar: invalid magic
tar: short read
==> There was an error downloading the binary file.

------> 2.4.6 platform specific fabric binary is not available to download <----`

**Comment by AdamKen** [comment]
> git: command not found

> curl: command not found

The script cant find git and curl commad. Have you installed Git and cURL on your machine?

**Comment by Gipnomanul** [comment]
I have them installed, but i thought that they are also installed inside docker. How can i check if they are working correctly?

**Comment by AdamKen** [comment]
Assuming you run ` curl -sSL https://bit.ly/2ysbOFE | bash -s` on powershell, you can run ` bash` to start your wsl, then check if they are functional.
