### ISSUE TITLE
Is possible to choose between two versions of the same chaincode?

### ISSUE THREAD

**Issue by Dudu3710** [hyperledger/fabric#3630]
I am facing a problem when i have to use an older version of a chaincode, the version is already installed. Or the newest one will always be executed?

**Comment by denyeart** [comment]
The version that has been installed on the peer and approved and committed on the channel will be used.

To update the chaincode, the typical flow would be for all participants to increment the version of the chaincode and re-install on their peers, then increment the sequence number on the channel, and approve/commit the new version/sequence.

It is possible however for a single organization to install and re-approve a new version of the chaincode on a channel using the same sequence on their own peer. This new chaincode would then be called on this organization's peer only. The use case here is if individual orgs want to add more checks before they endorse a transaction. Each org would still have to endorse the same readset/writeset though, for the transaction to be validated.

More details can be found at https://hyperledger-fabric.readthedocs.io/en/latest/chaincode_lifecycle.html
