### ISSUE TITLE
scripts/ccutils.sh: line 25: jq: command not found 

### ISSUE THREAD

**Issue by mock123456** [hyperledger/fabric#3634]
When i keyboard the  ./fabcar command to test the network,i found a error.I receive this message:

scripts/ccutils.sh: line 25: jq: command not found
+ res=1
Query installed on peer0.org1 has failed
Deploying chaincode failed

**Comment by 1kangsheng** [comment]
you can try it “sudo apt install jq”

**Comment by mock123456** [comment]
> you can try it “sudo apt install jq”
Thanks for your suggestion and it works!
