### ISSUE TITLE
Issue with V2.4.6 branch

### ISSUE THREAD

**Issue by rajat-dlt** [hyperledger/fabric#3638]
While the code is working fine in main but in v2.4.6, the line https://github.com/hyperledger/fabric/blob/v2.4.6/scripts/bootstrap.sh#L12
does not have the darwin iteration. 

Thus it does not work for apple based laptops. Can this be pushed in the specific branch too? 

Or is there anything particular due to which we've skipped this? 
cc- @mbwhite

**Comment by rajat-dlt** [comment]
@denyeart , Is the reason for this #2994? 

But still, this could be pushed into v2.4.6. I could not get this.

**Comment by denyeart** [comment]
@rajat-dlt The bootstrap script in main branch is intended to be used as the installer for tagged releases as well, the intended fabric and fabric-ca version can be passed to the main bootstrap script. The bootstrap script is therefore not actively maintained in prior release branches. #2994 is a proposal to build native ARM images and binaries, that proposal is still in discussion.
