### ISSUE TITLE
Fix image on Getting Started - Install 

### ISSUE THREAD

**Issue by sibelly** [hyperledger/fabric#3647]
The current image is difficult to read, so I thought opening an issue to link the PR #3646  with the fix.

Before:
![Screenshot from 2022-09-23 16-37-14](https://user-images.githubusercontent.com/7544858/192052735-cda1cde9-9747-4d41-be3b-e97386951ed9.png)

After:
![Screenshot from 2022-09-23 16-33-18](https://user-images.githubusercontent.com/7544858/192052584-2e549d4a-64ff-46ca-b31e-156211db593b.png)

**Comment by denyeart** [comment]
https://github.com/hyperledger/fabric/pull/3646
