### ISSUE TITLE
Update to Go 1.19

### ISSUE THREAD

**Issue by denyeart** [hyperledger/fabric#3661]
Update to Go 1.19.

Note that Go 1.19 has x509 verification changes that will require MSP updates.

**Comment by denyeart** [comment]
@yacovm @C0rWin Could you comment on the latest thoughts around the MSP updates for Go 1.19? Are you hopeful this can be completed for a v2.5 LTS release around end of year?

**Comment by yacovm** [comment]
I cannot comment before I get time to investigate thoroughly, and in any case we should let @adecaro and @ale-linux  take a look at it, before even discussing timelines.

**Comment by denyeart** [comment]
PR for MSP updates being worked in https://github.com/hyperledger/fabric/pull/3774 by @C0rWin

**Comment by C0rWin** [comment]
@denyeart, is there any plan to review and take action wrt #3774? Golang 1.20 is going to be released soon. However, we still need to move Fabric to 1.19 first, and we cannot, which seems a little bit pitty.

**Comment by denyeart** [comment]
@C0rWin Initially we were waiting for Angelo or Ale to approve https://github.com/hyperledger/fabric/pull/3774. But since the PR is in Draft state with failed checks I don't think anybody has looked at it. If you can make the PR green and out of Draft state I'll make sure it gets review. I agree we need to move to 1.19 soon.

PS The tests have been more flaky since moving to Github actions, we're working to improve those. In the interim as a maintainer you can click into any failures and re-run them to make it green.
