### ISSUE TITLE
Peer Node Crash When Executing ChainCode

### ISSUE THREAD

**Issue by cheeseng** [hyperledger/fabric#3685]
Fabric version: 2.4.6

When we invoked chaincode from our program the related peer node crash with the following error: 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1580fc9]

goroutine 114930 [running]:
github.com/hyperledger/fabric/internal/pkg/gateway.rwsetDifference({0xc002d9fe40?, 0x142?, 0x160?}, {0xc002f18000, 0x142, 0x160})
	/go/src/github.com/hyperledger/fabric/internal/pkg/gateway/apiutils.go:325 +0x1c89
github.com/hyperledger/fabric/internal/pkg/gateway.payloadDifference({0xc000025860?, 0xc002687d30?, 0xc002687d10?}, {0xc000025a40, 0x1c3, 0x1e0})
	/go/src/github.com/hyperledger/fabric/internal/pkg/gateway/apiutils.go:278 +0x145
github.com/hyperledger/fabric/internal/pkg/gateway.(*plan).processEndorsement(0xc002e6f380, 0xc002eb43c0, 0xc003085f20)
	/go/src/github.com/hyperledger/fabric/internal/pkg/gateway/endorsement.go:123 +0x5fe
github.com/hyperledger/fabric/internal/pkg/gateway.(*Server).processProposal(0xc00268c300, {0x1b56198?, 0xc00288eb70}, 0xc002e6f100?, 0xc002eb43c0, 0xc002e600f0, 0xc0035f2038)
	/go/src/github.com/hyperledger/fabric/internal/pkg/gateway/api.go:263 +0x62c
github.com/hyperledger/fabric/internal/pkg/gateway.(*Server).Endorse.func1(0xc00029f750?)
	/go/src/github.com/hyperledger/fabric/internal/pkg/gateway/api.go:190 +0xa6
created by github.com/hyperledger/fabric/internal/pkg/gateway.(*Server).Endorse
	/go/src/github.com/hyperledger/fabric/internal/pkg/gateway/api.go:188 +0xd75
```

Any idea which area we can check to fix the error?

Thanks in advanced any guide and help given.  🙏🏻

Cheers.

**Comment by cheeseng** [comment]
@andrew-coleman Thanks for looking into the error with a PR 🙏🏻 .  At the moment, is there anything I can do to workaround the problem in 2.4.6?

**Comment by andrew-coleman** [comment]
@cheeseng Yes, this problem is occurring in code introduced in this [commit](https://github.com/hyperledger/fabric/commit/a91c63304fb48858dfecf0cc169396d635dbb5c8).  It can be disabled by setting the log level to “error” for the “gateway.responsechecker” logger.

**Comment by cheeseng** [comment]
> @cheeseng Yes, this problem is occurring in code introduced in this [commit](https://github.com/hyperledger/fabric/commit/a91c63304fb48858dfecf0cc169396d635dbb5c8). It can be disabled by setting the log level to “error” for the “gateway.responsechecker” logger.

I'll give that a try, thanks for the pointer!
