### ISSUE TITLE
The collision resistance of TxID not conform sha256‘s but confirm  getRandomNonce()

### ISSUE THREAD

**Issue by lluckydog** [hyperledger/fabric#3703]
I look into the function of generate txid in [protoutil/proputils.go](https://github.com/hyperledger/fabric/blob/cde0248c947f45e46bdf454ee5f6da42ebc79658/protoutil/proputils.go#L45)

Although it use sha256()function to compute txid, the collision resistance is not the same as sha256 but as function getRandomNonce(). A possible solution to this problem may be add unique transaction information into the compute of txid, which can improve the collision resistance

**Comment by denyeart** [comment]
@adecaro What do you think? Is getRandomNonce() good enough?

**Comment by adecaro** [comment]
Hi @denyeart and @lluckydog,

Very good point. The key measure here is the entropy of the message that we hash.
So, fixed the creator (that has at least 64 bits of entropy), the nonce brings in 192 bits of entropy (24 bytes), under the assumption that the PRG is working properly. I think we are good enough here. The source has at least 256 bits of entropy. 

We can certainly increase it and even move to SHA3-512 for better quantum resistance.

**Comment by lluckydog** [comment]
@adecaro Thanks for your answer, it really help me understand this point. The point I want to say not is the hash function isn't good enough, but it not help improve resistance, so I got a little confused at first. I didn't think about the PRG can improve this think, which, to my point, is also good enough.
