### ISSUE TITLE
Configtxgen binary for BFT

### ISSUE THREAD

**Issue by andrew-coleman** [hyperledger/fabric#3772]
Create a standalone command line utility to generate a config block for BFT

**Comment by shashank-priyadarshi** [comment]
Hi @andrew-coleman , I would like to take this up.

**Comment by denyeart** [comment]
@andrew-coleman @yacovm @tock-ibm 

Do you recall the motivation and design thoughts for this one, over and above what `configtxgen` already offers? Or maybe this one simply didn't get close out. Please expand the Description or close accordingly.

**Comment by yacovm** [comment]
We should have a thread necromancer badge on Github. 


> @andrew-coleman @yacovm @tock-ibm
> 
> Do you recall the motivation and design thoughts for this one, over and above what configtxgen already offers? Or maybe this one simply didn't get close out. Please expand the Description or close accordingly.

I remember what was the intent. 

If you remember, in the past, we said that we'd decouple all components in a way that would enable us to have the things common in Fabric, and then embed these things into each consensus type.

Currently, in configtxgen, we have a set of consensus specific code that parses the consenter config.
The intent was to refactor configtxgen such that this can be injected via dependency injection into configtxgen.
Then, we would have a configtxgen per consensus type.

Whether we close this or not is up to you, but I personally won't be reviewing this code contribution.

**Comment by denyeart** [comment]
There are no plans to refactor configtxgen, I am going to close this issue.
