### ISSUE TITLE
Incorrect configuration of CLI Image

### ISSUE THREAD

**Issue by Ajax-Light** [hyperledger/fabric#3780]
Fabric Version: 2.4.7
Docker Desktop Version: 4.12.0
Dev Environment: Ubuntu/WSL2 on Windows 10 version 21H1

![image](https://user-images.githubusercontent.com/54140487/201611536-62fe1dab-3bbd-45d9-a199-8e5eec1c2d87.png)

I'm not sure if the latest version of Fabric discourages use of the CLI container for interacting with the network, but it looks like a symlink has gone missing at `/etc/hyperledger/fabric/peercfg/mspreally`. I see that the `test-network/compose/docker/peercfg` folder is bind mounted to `/etc/hyperledger/fabric/peercfg`.
So `ln -s ../fabric/msp mspreally` seems to fix the issue.

**BUT** I'm hit with another subsequent error:
![image](https://user-images.githubusercontent.com/54140487/201622452-3c69e94a-2989-4e85-a7b9-c83ac4c905c4.png)

At this point I'm not sure if I haven't properly set up my env or whether this is a config issue in the image.

**Comment by denyeart** [comment]
@mbwhite There may be an issue in peercfg core.yaml. What's the story with `mspreally` :-)
https://github.com/hyperledger/fabric-samples/blob/main/test-network/compose/docker/peercfg/core.yaml#L345

**Comment by mbwhite** [comment]
@denyeart I've no idea really don't...

https://github.com/hyperledger/fabric-samples/pull/873

**Comment by denyeart** [comment]
Ok, fix merged, @Ajax-Light can you try fabric-samples main branch again?

**Comment by Ajax-Light** [comment]
@denyeart Thanks for working on this.
Unfortunately, I don't think the fix worked.

![image](https://user-images.githubusercontent.com/54140487/202763339-455c6c01-1697-4da6-9681-8876bebf34be.png)

As you can see, the error changes when I export the env variables for Org 1 (iirc the docs mentioned this already being set by default).
If I understand Fabric Config correctly, The only env variable which should've affected `peer` is `CORE_PEER_ADDRESS`. Since the container has no ports open, it cannot connect to the peer container, hence fails. I believe manually exposting ports with a `-p 7051:7051 -p 9051:9051` *should* fix the issue.
Could you please explain how the "Cannot init crypto" message disappears when `/etc/hyperledger/peercfg/msp` doesn't even exist?

**Comment by denyeart** [comment]
It shouldn't be looking for msp in /etc/hyperledger/peercfg/msp.

Peer should be looking for msp at /etc/hyperledger/fabric/msp:
https://github.com/hyperledger/fabric-samples/blob/main/test-network/compose/compose-test-net.yaml#L84

Based on in this volume:
https://github.com/hyperledger/fabric-samples/blob/main/test-network/compose/compose-test-net.yaml#L90

Therefore it should load msp directory from
test-network/organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp.

Similarly, if you are attempting CLI container it shouldn't read msp from /etc/hyperledger/peercfg/msp. If it does, that means that your CORE_PEER_MSPCONFIGPATH setting is not taking effect.
