### ISSUE TITLE
Hyperledger Fabric Error: error getting endorser client for channel: endorser client failed to connect

### ISSUE THREAD

**Issue by ecemozturkk** [hyperledger/fabric#3809]
I am walking through the [Hyperledger Fabric Build Your First Network](https://hyperledger-fabric.readthedocs.io/en/latest/test_network.html) tutorial and I am under the Create and Join Channel section. 

When I try and do the following command to create a channel on **test-network** in **fabric-samples** folder:

`./network.sh createChannel`

I receive the following error:

```
Channel 'mychannel' created
Joining org1 peer to the channel...
Using organization 1
+ peer channel join -b ./channel-artifacts/mychannel.block
+ res=1
+ peer channel join -b ./channel-artifacts/mychannel.block
+ res=1
+ peer channel join -b ./channel-artifacts/mychannel.block
+ res=1
+ peer channel join -b ./channel-artifacts/mychannel.block
+ res=1
2022-11-25 15:56:34.801 +03 0001 ERRO [comm.tls] ClientHandshake -> Client TLS handshake failed after 2.839083ms with error: EOF remoteaddress=[::1]:7051
2022-11-25 15:56:35.809 +03 0002 ERRO [comm.tls] ClientHandshake -> Client TLS handshake failed after 3.0385ms with error: EOF remoteaddress=[::1]:7051
2022-11-25 15:56:37.331 +03 0003 ERRO [comm.tls] ClientHandshake -> Client TLS handshake failed after 4.389334ms with error: EOF remoteaddress=[::1]:7051
Error: error getting endorser client for channel: endorser client failed to connect to localhost:7051: failed to create new connection: context deadline exceeded
After 5 attempts, peer0.org1 has failed to join channel 'mychannel' 
```

Even though I followed the same steps yesterday, it just worked fine. But today I have this error and I don't know how to solve it.

**Comment by denyeart** [comment]
If you still need help refer to the community support options:
https://hyperledger-fabric.readthedocs.io/en/latest/CONTRIBUTING.html#communications-and-getting-help

**Comment by Pheglovog** [comment]
I encounter the same question
and the tutorial has given a way to solve it :
![image](https://github.com/user-attachments/assets/1c0fefcc-9980-4793-8451-e223950d6855)

But, actually I can execute this command several days ago, so I just restart my compute, and re-execute this command successfully

**Comment by amritendunath** [comment]
@Pheglovog 
1st: ./network.sh down
2nd:  ./network.sh up createchannel -c mychannel -ca

It should solve the issue.
