### ISSUE TITLE
Unable to connect to the discovered orderer orderer0.example.com:7050

### ISSUE THREAD

**Issue by tprafull** [hyperledger/fabric#3812]
Hi 

I am unable to invoke transaction. I am getting below error 
Unable to connect to the discovered orderer orderer0.example.com:7050

`66f6b9d9d7c0   hyperledger/fabric-orderer:2.1                                                                                                                                          "orderer"                About an hour ago   Up About an hour   0.0.0.0:7050->7050/tcp, :::7050->7050/tcp, 0.0.0.0:8443->8443/tcp, :::8443->8443/tcp             orderer.example.com
cacd16bca285   hyperledger/fabric-orderer:2.1                                                                                                                                          "orderer"                About an hour ago   Up About an hour   7050/tcp, 0.0.0.0:8050->8050/tcp, :::8050->8050/tcp, 0.0.0.0:8444->8443/tcp, :::8444->8443/tcp   orderer2.example.com
8ba79e9b4d95   hyperledger/fabric-orderer:2.1                                                                                                                                          "orderer"                About an hour ago   Up About an hour   7050/tcp, 0.0.0.0:9050->9050/tcp, :::9050->9050/tcp, 0.0.0.0:8445->8443/tcp, :::8445->8443/tcp   orderer3.example.com
`
This is how my docker containers look like. What am I missing ? I can see 7050 port mapped to all three orderers. 

What should I change to make it running ? 

Thank you

**Comment by Param-S** [comment]
0.0.0.0:7050->7050/tcp, :::7050->7050/tcp, 0.0.0.0:8443->8443/tcp, :::8443->8443/tcp orderer.example.com
0.0.0.0:8050->8050/tcp, :::8050->8050/tcp, 0.0.0.0:8444->8443/tcp, :::8444->8443/tcp orderer2.example.com
0.0.0.0:9050->9050/tcp, :::9050->9050/tcp, 0.0.0.0:8445->8443/tcp, :::8445->8443/tcp orderer3.example.com 

Based on this port mapping, I suspect the conflict is between the individual orderer's admin service port and operations service port, not across the orderers.

Refer the test-network port definitions and mapping here: https://github.com/hyperledger/fabric-samples/blob/main/test-network/compose/compose-test-net.yaml#L45&L46.

Update the service ports & verify.

**Comment by projeto-nesa** [comment]
@tpraful did you resolve your problem ?
