### ISSUE TITLE
peer: Too many requests for /gateway.Gateway, exceeding concurrency limit (500)" 

### ISSUE THREAD

**Issue by lgy1027** [hyperledger/fabric#3829]
fabric version: 2.4.1
fabric-gateway v1.1.0
Three orderer and one org peer

Now I use fabric-gateway to call the alliance network, but I will report an error "Too many requests for /gateway.Gateway, exceeding concurrency limit (500)" every once in a while. I don't know where the problem is. I can guarantee the concurrent requests in the container Did not reach 500, may I ask where to locate the problem?

**Comment by lgy1027** [comment]
![微信截图_20221205172805](https://user-images.githubusercontent.com/38779388/205602082-c248714b-2855-4907-b608-480847f406ec.png)

**Comment by lgy1027** [comment]
![image](https://user-images.githubusercontent.com/38779388/205604804-9998b932-833d-4059-8e3a-a40d02268375.png)

**Comment by tmilox** [comment]
Hello @lgy1027,

It seems to be related to this config: https://github.com/hyperledger/fabric/blob/cde0248c947f45e46bdf454ee5f6da42ebc79658/core/peer/config_test.go#L273

Here you can set different limits for your peer:

https://github.com/hyperledger/fabric/blob/main/sampleconfig/core.yaml#L480-L491

Best,
