### ISSUE TITLE
No way to verify private data purge was completed successfully

### ISSUE THREAD

**Issue by jt-nti** [hyperledger/fabric#3844]
Fabric 2.5 adds the ability to purge private data from chaincode however this involves an element of background processing before all the data is eventually deleted from the persistent stores. There is currently no way to verify when the data purge has completed successfully, or to access any error details should the purge fail for any reason, which may have implications for anyone wishing to use the new purge private data API as part of any GDPR work.

**Comment by denyeart** [comment]
Additional logging was added for purge operation to resolve this.
