### ISSUE TITLE
Query installed on peer0.org1 has failed. Deploying chaincode failed

### ISSUE THREAD

**Issue by ghost** [hyperledger/fabric#3848]
when i used this command  - 

./network.sh deployCC -ccn basic -ccp ../asset-transfer-basic/chaincode-javascript/ -ccl javascript

i am facing this errors 
![Screenshot from 2022-12-12 14-04-14](https://user-images.githubusercontent.com/117824027/207231389-3c4be4b1-2d2e-4fd9-a5e9-e7510e957d8a.png)

Query installed on peer0.org1 has failed
Deploying chaincode failed

**Comment by Param-S** [comment]
Script needs command `jq` 
<img width="471" alt="image" src="https://user-images.githubusercontent.com/13217743/207231807-3ed2cf74-1613-4d38-8535-0b3e3b6f7c44.png">
Please refer hyperledger docs https://hyperledger-fabric.readthedocs.io/en/latest/prereqs.html?highlight=jq#jq for prereqs.

**Comment by ghost** [comment]
> Script needs command `jq` <img alt="image" width="471" src="https://user-images.githubusercontent.com/13217743/207231807-3ed2cf74-1613-4d38-8535-0b3e3b6f7c44.png"> Please refer hyperledger docs https://hyperledger-fabric.readthedocs.io/en/latest/prereqs.html?highlight=jq#jq for prereqs.

Thanks you Param, but i have already downloaded all prereqs for the same still i am getting this

**Comment by Param-S** [comment]
It may not be in your PATH settings for the shell to locate it.  Please update PATH variable with the location of the `jq` executable & try. https://github.com/hyperledger/fabric-samples/blob/a6028cd3985e3bac77409b839f4142eabaa53928/test-network/network.sh#L21

export PATH=${ROOTDIR}/../bin:${PWD}/../bin:$PATH:`<<provide the location of the jq command>>`

**Comment by Param-S** [comment]
Script was able to install the chaincode which we can confirm from this output. <img width="1780" alt="Screenshot 2022-12-13 at 11 04 52 AM" src="https://user-images.githubusercontent.com/13217743/207235350-1f4735fe-c3d2-4260-aa1e-8f5a55d11793.png"> 
It only failed to confirm the installation by interpreting the peer query output using `jq` command

**Comment by ghost** [comment]
> Script was able to install the chaincode which we can confirm from this output. <img alt="Screenshot 2022-12-13 at 11 04 52 AM" width="1780" src="https://user-images.githubusercontent.com/13217743/207235350-1f4735fe-c3d2-4260-aa1e-8f5a55d11793.png"> It only failed to confirm the installation by interpreting the peer query output using `jq` command

i have provided jq command then also getting same thing 
![image](https://user-images.githubusercontent.com/117824027/207239340-a483a1ae-4dde-4171-9ac3-f38c35fbd213.png)
please let me know what to do ?

**Comment by ghost** [comment]
sudo apt install jq 

Solve after installing this !! 
Thank you !
