### ISSUE TITLE
Encountered errors while bringing up the project

### ISSUE THREAD

**Issue by ghost** [hyperledger/fabric#3852]
./network.sh up createChannel -ca -c mychannel -s couchdb  after using this command 
![image](https://user-images.githubusercontent.com/117824027/207586859-d65e3a32-4a36-4763-a9f5-6c87fba8cb4b.png)
RROR: for 79c621d3c2dc_ca_org1  Cannot start service ca_org1: driver failed programming external connectivity on endpoint 79c621d3c2dc_ca_org1 (40bdb9fc585c1dd94c737b173038eed0d58448aa18566111661ab5347b83d4cc): Error starting userland proxy: listen tcp [::]:17054: bind: address already in use
Starting 43f4941e8ce5_ca_orderer ... error

ERROR: for 43f4941e8ce5_ca_orderer  Cannot start service ca_orderer: driver failed programming external connectivity on endpoint 43f4941e8ce5_ca_orderer (0d2aec4ddb039598ee26be8f836096514bd42a6d78dae81a1133ea5dea43065c): Error starting userland proxy: listen tcp [::]:19054: bind: address already in use

ERROR: for ca_org2  Cannot start service ca_org2: driver failed programming external connectivity on endpoint 8a50c5f93d44_ca_org2 (a6ac9148afed25faf2287a873a59062c965f8755955f603aff9b0272d94da811): Error starting userland proxy: listen tcp [::]:18054: bind: address already in use

ERROR: for ca_org1  Cannot start service ca_org1: driver failed programming external connectivity on endpoint 79c621d3c2dc_ca_org1 (40bdb9fc585c1dd94c737b173038eed0d58448aa18566111661ab5347b83d4cc): Error starting userland proxy: listen tcp [::]:17054: bind: address already in use

ERROR: for ca_orderer  Cannot start service ca_orderer: driver failed programming external connectivity on endpoint 43f4941e8ce5_ca_orderer (0d2aec4ddb039598ee26be8f836096514bd42a6d78dae81a1133ea5dea43065c): Error starting userland proxy: listen tcp [::]:19054: bind: address already in use
ERROR: Encountered errors while bringing up the project.

**Comment by denyeart** [comment]
"address already in use" indicates a container may already be up.

Please see the community support options for usage issues:
https://hyperledger-fabric.readthedocs.io/en/latest/CONTRIBUTING.html#communications-and-getting-help

We use github issues for code issues only.
