### ISSUE TITLE
Gateway support for BFT orderers

### ISSUE THREAD

**Issue by andrew-coleman** [hyperledger/fabric#3864]
Enhance the gateway service to submit transactions to all BFT orderers, as described in the RFC:

https://github.com/hyperledger/fabric-rfcs/blob/main/text/006-bft-based-ordering-service.md#changes-to-client-sdk-and-gateway-service

**Comment by tock-ibm** [comment]
@andrew-coleman was this task completed? Is there anything else we need to at the gateway?

**Comment by andrew-coleman** [comment]
Yes, I believe that was completed here: https://github.com/hyperledger/fabric/blob/main/internal/pkg/gateway/submit.go#L64

Although I gather there are sporadic failures in the integration test: https://github.com/hyperledger/fabric/pull/4543#issuecomment-1821200943
Not sure if this is caused by a recent change in smartbft behaviour, or whether there is an incorrect assumption in the test itself.
