### ISSUE TITLE
 Unable to register orderers in K8s - Timeout issue - 

### ISSUE THREAD

**Issue by kvk24680** [hyperledger/fabric#3883]
I am trying to deploy hyperledger fabric on multiple cluster and trying to connect them for my use case. Using kind cluster to test and I am using this repo: https://github.com/EspeoBlockchain/hlf-k8s-multi-cluster

I am not able to register the orderer users to the ord-ca config file generated from the command: 

`kubectl hlf ca register --name ord-ca --user orderer1 --secret orderer1pw --type orderer \
--enroll-id enroll --enroll-secret enrollpw --mspid OrdererMSP`

Created ord-ca from the command: 

```
kubectl hlf ca create \
    --storage-class standard \
    --capacity 1Gi \
    --name ord-ca \
    --enroll-id enroll \
    --enroll-pw enrollpw \
    --hosts <my-domain>
```

In my domain, I have pointed ord-ca.<domain> to my machine IP. It works fine for org1-ca. The output I get is 

```
[fabsdk/fab] 2022/12/23 06:01:07 UTC - n/a -> INFO TLS Enabled
 [fabsdk/fab] 2022/12/23 06:01:07 UTC - n/a -> INFO generating key: &{A:ecdsa S:256}
 [fabsdk/fab] 2022/12/23 06:01:07 UTC - logbridge.(*cLogger).Info -> INFO encoded CSR

Error: enroll failed: enroll failed: POST failure of request: POST https://ord-ca.<domain>:443/enroll

{"hosts":null,"certificate_request":"-----BEGIN CERTIFICATE REQUEST-----\n\nRwAwRAIgM+aYH9D/8DfzYZSuRg\nHFnGcBRaZyKlkRZORqiPPbXNMBcZH1xn\n-----END CERTIFICATE REQUEST-----\n","profile":"","crl_override":"","label":"","NotBefore":"0001-01-01T00:00:00Z","NotAfter":"0001-01-01T00:00:00Z","ReturnPrecert":false,"CAName":""}: Post "https://ord-ca.<domain>:443/enroll": dial tcp <machine-ip>:443: connect: connection refused
```

**Comment by denyeart** [comment]
Issues in this repo are for core Fabric code issues.
For kubernetes usage questions, I'd suggest to post to Discord fabric-kubernetes channel.
More information at https://hyperledger-fabric.readthedocs.io/en/latest/CONTRIBUTING.html#communications-and-getting-help.
