### ISSUE TITLE
Endorsement Policies Documentation needs explainanation

### ISSUE THREAD

**Issue by rajat-dlt** [hyperledger/fabric#3884]
The default documentation mentioned for [endorsement-policies](https://hyperledger-fabric.readthedocs.io/en/latest/endorsement-policies.html), does not work. 

As the samples only use `Org1MSP` or `Org2MSP`, all the examples state `"AND('Org1.peer', 'Org2.peer')"`. These don't work on the test network.

**Comment by rajat-dlt** [comment]
@denyeart, Could I pick this issue?

**Comment by denyeart** [comment]
@rajat-dlt Are you simply suggesting to switch `Org1` to `Org1MSP` (and same for Org2) as the example in the docs? I tend to agree... go ahead and open a PR.

**Comment by rajat-dlt** [comment]
@denyeart, 
I've added the intended changes to a PR, but somehow the unit tests are failing. I've just changed the doc file so Ideally this should not happen. Could you help me in resolving this?

**Comment by denyeart** [comment]
Thanks @rajat-dlt  The unit test failures occur randomly, not related to the doc. I've merged the PR.
