### ISSUE TITLE
panic: TLS is required for running ordering nodes of cluster type

### ISSUE THREAD

**Issue by ishamistygreen** [hyperledger/fabric#3886]
Running chaincode in development mode

Start the orderer

https://hyperledger-fabric.readthedocs.io/en/latest/peer-chaincode-devmode.html#start-the-orderer

ORDERER_GENERAL_GENESISPROFILE=SampleDevModeSolo orderer

I am getting below error

**2022-12-30 01:43:46.544 UTC 0007 PANI [orderer.common.server] reuseListener -> TLS is required for running ordering nodes of cluster type.
panic: TLS is required for running ordering nodes of cluster type.**

Kindly help me
Thanks in Advance

**Comment by SongZihuan** [comment]
How do you fix it?

**Comment by Diosan** [comment]
I am still having this issue. Please help.

**Comment by burhon97** [comment]
I have this issue too

**Comment by bellaj** [comment]
activate TLS
