### ISSUE TITLE
# docker-compose up -d  getting error - 

### ISSUE THREAD

**Issue by ghost** [hyperledger/fabric#3928]
![image](https://user-images.githubusercontent.com/117824027/212611451-c70d411b-30e1-45bc-ab4b-489f359dbccd.png)

i am using official doc for the Fabric CA and recived the following error after this command docker-compose up

**Comment by denyeart** [comment]
I think you've hit:
https://cri.dev/posts/2020-07-06-How-to-solve-Docker-docker-credential-desktop-not-installed-or-not-available-in-PATH/

rather than a Fabric issue.
