### ISSUE TITLE
Disable peer.deliveryclient.blockGossipEnabled in sample core.yaml

### ISSUE THREAD

**Issue by dvusboy** [hyperledger/fabric#3961]
In the release note of v2.5.0, under "FAB-15317: Block dissemination via gossip is deprecated", the recommended setting for `blockGossipEnabled` is `false`. I think [sampleconfig/core.yaml](https://github.com/hyperledger/fabric/blob/main/sampleconfig/core.yaml#L376) should reflect that.

**Comment by denyeart** [comment]
Moving to Fabric v3.0... in Fabric v3.0 either this default will be changed or the gossip block dissemination function will be entirely removed... see proposal in https://github.com/hyperledger/fabric-rfcs/pull/49.

**Comment by hxx258456** [comment]
Will newly joined nodes be affected when they perform block synchronization?
