### ISSUE TITLE
 integration/e2e/e2e_test.go:638:26: FullEtcdRaft not declared by package nwo

### ISSUE THREAD

**Issue by kudumula99** [hyperledger/fabric#3976]
Hi, I'm trying to setup the fabric(v2.x) development environment on windows 11 Pro(Version 22H2; Build Ver - 22621.1105) - WSL2(Ubuntu-20.04).
followed the instructions:
Prerequisites: https://hyperledger-fabric.readthedocs.io/en/release-2.5/prereqs.html
Setting up the development environment: https://hyperledger-fabric.readthedocs.io/en/latest/dev-setup/devenv.html#setting-up-the-development-environment

getting below error for: **make basic-checks integration-test-prereqs**
integration/e2e/e2e_test.go:638:26: FullEtcdRaft not declared by package nwo

![image](https://user-images.githubusercontent.com/32400303/215597826-dfe3d696-3846-400b-8f23-76d6a8bf6706.png)

In VSCode
![image](https://user-images.githubusercontent.com/32400303/215598867-dcdcc897-a580-4315-b9e7-d24efcd06ac7.png)

**Comment by denyeart** [comment]
@andrew-coleman Is this related to your fix in https://github.com/hyperledger/fabric/pull/3962 ?

**Comment by andrew-coleman** [comment]
Yes, this was fixed in that commit

**Comment by kudumula99** [comment]
It's working. Thanks.
