### ISSUE TITLE
EndorseError: 2 UNKNOWN: too many requests for /gateway.Gateway, exceeding concurrency limit (500)

### ISSUE THREAD

**Issue by gowthami1610** [hyperledger/fabric#4023]
I executed Hyperledger Fabric test network and it had no errors. When I benchmarked its performance with Hyperledger Caliper tool, it was successful. Caliper works fine for reading the records from my fabric network with any number of transaction.

When the records were created it worked fine for less number of transaction. When the transactions submitted is increased, the following error is thrown.

``2023.02.13-11:49:56.059 error [caliper] [connectors/peer-gateway/PeerGateway]   Failed to perform submit transaction [Admin_createPatient] using arguments [Client3_CAR557,Toyota,S,brown,Shotaro,29,123456890],  with error: EndorseError: 2 UNKNOWN: too many requests for /gateway.Gateway, exceeding concurrency limit (500)``

To rectify the error I changed the value of concurrency request limit value of gatewayService in core.yaml file but still the error not rectified. The core.yaml is located in config folder. 

How to update the configuration of Gateway service concurrency limit?

**Comment by denyeart** [comment]
We have confirmed increasing gatewayService in core.yaml will allow additional endorsements. In fact it has been tested with a Caliper client beyond 500.
Perhaps FABRIC_CFG_PATH for the peer isn't pointing to the correct core.yaml location and therefore updates aren't effective?
Note, you can also use environment variable CORE_PEER_LIMITS_CONCURRENCY_GATEWAYSERVICE to override the core.yaml value.

**Comment by davidkel** [comment]
@denyeart This issue was resolved in stackover. It can be closed
