### ISSUE TITLE
channel creation failed in test network

### ISSUE THREAD

**Issue by Anandakrishnan66** [hyperledger/fabric#4059]
Error: Post "https://localhost:7053/participation/v1/channels": dial tcp 127.0.0.1:7053: connect: connection refused

Channel creation failed

**Comment by denyeart** [comment]
Please reserve Fabric issues for bug reports. See the documentation for Getting Help options.
https://hyperledger-fabric.readthedocs.io/en/latest/CONTRIBUTING.html#communications-and-getting-help
