### ISSUE TITLE
Implicit PDC is much slower than normal PDC

### ISSUE THREAD

**Issue by kaiknight** [hyperledger/fabric#4075]
We are evaluated performance of PDC. We noticed as shown in attached file the write to implicit PDC is dramatically slower than user-created PDC. We are using fabric 2.4.7. The chain code is simply to put a single value to PDC: key=“1” with putPrivateData()

**Comment by kaiknight** [comment]
![image](https://user-images.githubusercontent.com/755951/222868398-6632f804-439e-4f78-a1fd-a4014cdb7468.png)
Uploaded the benchmark of caliper for both implicit PDC and normal PDC

**Comment by kaiknight** [comment]
![image](https://user-images.githubusercontent.com/755951/222940795-881f7b8f-5869-4c3b-9593-e9de2da03d20.png)

**Comment by kaiknight** [comment]
As you can see in above screenshot, same peer, same couchdb, same chaincode, different PDC.
For implicit PDC, TPS is 13.6. For explicit PDC, TPS is 55.5
Can you suggest the cause of this performance degradation.
A workaround is also eagerly needed.

**Comment by denyeart** [comment]
After looking at the logs the TPS rate appeared the same for most of the run, but it looks like environment had issues that caused some delays and timeouts at one or two times during the run causing the final numbers to be skewed.
