### ISSUE TITLE
peer: unable to disable core.vm.endpoint from env var

### ISSUE THREAD

**Issue by tbondarchuk** [hyperledger/fabric#4076]
core.vm.endpoint has default value set https://github.com/hyperledger/fabric/blob/bdb311b8c70d82b387b6bac2e8feaa7f8a486f71/sampleconfig/core.yaml#L516

I assume due to backward compatibility since users might relay on that default value?

I'm trying to run peer on kubernetes using default config file from  `/etc/hyperledger/fabric/core.yaml` but setting `CORE_VM_ENDPOINT` to empty string does not override default config, resulting in healthcheck failing on trying to check docker service. And looks like the only solution is to mirror whole core.yaml file to configmap and then override it using env vars
https://github.com/hyperledger/fabric-samples/blob/main/test-network-k8s/config/org1/core.yaml

I was able to track this to https://github.com/spf13/viper/blob/3970ad177ecc286c1e14b64c18449cb30f73d642/README.md?plain=1#L283 :
> By default empty environment variables are considered unset and will fall back to
the next configuration source. To treat empty environment variables as set, use
the `AllowEmptyEnv` method.

Would be nice to have it enabled here: https://github.com/hyperledger/fabric/blob/bdb311b8c70d82b387b6bac2e8feaa7f8a486f71/cmd/peer/main.go#L32 

Or perhaps just comment default value in example config file?

**Comment by denyeart** [comment]
Users do rely on the current default.
I think the AllowEmptyEnv() solution is reasonable and would welcome a pull request.

**Comment by mak2002** [comment]
Hey, I would like to work on this issue!

**Comment by tbondarchuk** [comment]
@mak2002 I have only basic knowledge of golang, good enough to read the code and understand some parts of it but not enough to contribute back I'm afraid, so please - feel free to work on this.
