### ISSUE TITLE
fanric-java-sdk how to use Taking ledger snapshots and using them to join channels

### ISSUE THREAD

**Issue by VastlyEternal** [hyperledger/fabric#4083]
fanric-java-sdk how to use Taking ledger snapshots and using them to join channels

**Comment by bestbeforetoday** [comment]
Joining channels using snapshots uses the peer CLI commands, as described in the Fabric [documentation](https://hyperledger-fabric.readthedocs.io/en/latest/peer_ledger_snapshot.html). The Java SDK does not support joining channels using snapshots.
