### ISSUE TITLE
AWS cloudhsm setup for fabric 

### ISSUE THREAD

**Issue by chetagra** [hyperledger/fabric#4091]
I am trying to run a peer service with pkcs11 and want to generate peer msp folder inside my AWS cloudhsm service 

I am getting following error 

![image](https://user-images.githubusercontent.com/46901115/225301025-dec91ef3-d04b-4e72-88bc-db876e61b21c.png)

and I have done following changes in peer configuration file
![Screenshot from 2023-03-15 17-23-56](https://user-images.githubusercontent.com/46901115/225301750-3b385ce3-ebaf-4172-823e-8012b655fa52.png)

**Comment by denyeart** [comment]
This sounds like a AWS question rather than a core Fabric issue.
Please reserve Fabric issue list for Fabric code issues.
For getting community help, see
https://hyperledger-fabric.readthedocs.io/en/latest/CONTRIBUTING.html#communications-and-getting-help
