### ISSUE TITLE
How do I use the official CouchDB docker image maintained by the Apache CouchDB project in 1.4.8？

### ISSUE THREAD

**Issue by 13310241314** [hyperledger/fabric#4093]
hello everyone：
I have a project that uses hyperledger/fabric 1.4.8。However, there are many security vulnerabilities in couchdb 2.3.1，So I want to replace the newer version of couchdb。However, when I update the official couchdb: 3.3.1 or couchdb 3.2.2, the peer node cannot be started, and an error is reported as follows，What could be the problem?
![image](https://user-images.githubusercontent.com/125418632/225808205-f4475c81-a5ae-455e-a27a-c71b5454a439.png)

**Comment by denyeart** [comment]
Fabric v1.4.x does not support CouchDB 3.2.
Fabric v1.4.x itself has not been in support for a long time and has not received fixes that are in Fabric v2.x.
Any Fabric v1.4 deployment should update to v2.x immediately to receive the latest set of fixes.
