### ISSUE TITLE
ServerHandshake -> ERRO 165733 TLS handshake failed with error write tcp 127.11.21:7050->121.11.11.127:33322: write: connection reset by peer server=Orderer remoteaddress=121.11.11.127:33322

### ISSUE THREAD

**Issue by willson-zhang** [hyperledger/fabric#4094]
After the disk is full, the following problems occur after restarting，I need help, can anyone tell me how to solve it

2023-03-17 16:51:49.386 CST [core.comm] ServerHandshake -> ERRO 165733 TLS handshake failed with error write tcp 127.11.21:7050->121.11.11.127:33322: write: connection reset by peer server=Orderer remoteaddress=121.11.11.127:33322

![1679043953598](https://user-images.githubusercontent.com/19216912/225860527-af29d549-3d98-4b75-9beb-c52da8d205c8.png)

**Comment by denyeart** [comment]
Fabric will not work with a disk that is full. Either add disk storage or move the orderer node to a host with storage available.

**Comment by willson-zhang** [comment]
The disk has been expanded, but the same problem still occurs

**Comment by willson-zhang** [comment]
> <img alt="@willson-zhang" width="20" height="20" src="https://avatars.githubusercontent.com/u/19216912?s=40&amp;u=0cd4604d77007293a3ae4203923643d812df9f90&amp;v=4">

The disk has been expanded, but the same problem still occurs

**Comment by willson-zhang** [comment]
> Fabric will not work with a disk that is full. Either add disk storage or move the orderer node to a host with storage available.

The disk has been expanded, but the same problem still occurs
