### ISSUE TITLE
binary file

### ISSUE THREAD

**Issue by LiFeiBiao** [hyperledger/fabric#4099]
amd binary file cannot use in arm

**Comment by bestbeforetoday** [comment]
v2.5 includes ARM binaries. See [v2.5.0-beta2](https://github.com/hyperledger/fabric/releases/tag/v2.5.0-beta2).

**Comment by denyeart** [comment]
v2.5 now released with ARM binaries - https://github.com/hyperledger/fabric/releases/tag/v2.5.0
