### ISSUE TITLE
how to compilation a arm binary

### ISSUE THREAD

**Issue by LiFeiBiao** [hyperledger/fabric#4100]

**Comment by bestbeforetoday** [comment]
v2.5 includes ARM binaries. See [v2.5.0-beta2](https://github.com/hyperledger/fabric/releases/tag/v2.5.0-beta2).

**Comment by ghost** [comment]
@LiFeiBiao , besides using the ready-build binaries mentioned by bestbeforetoday, you can review how the CI builds for arm:

https://github.com/hyperledger/fabric/blob/main/.github/workflows/release.yml

if you're not able to build manually, you can setup this ci in your fork and build your arm images.
