### ISSUE TITLE
Make docker error 2

### ISSUE THREAD

**Issue by AKIMdada** [hyperledger/fabric#4134]
I am having issues with make docker. I need help asap. please assistnce. I have search online and done all i could but cant find solution. error paste below. I am a beginner in this field. 

gotools.mk:58: recipe for target 'gotool.counterfeiter' failed
make[1]: Leaving directory '/opt/gopath/src/github.com/hyperledger/fabric'
make[1]: *** [gotool.counterfeiter] Error 2
make: *** [/opt/gotools/bin/counterfeiter] Error 2
gotools.mk:63: recipe for target '/opt/gotools/bin/counterfeiter' failed
Makefile:253: recipe for target '.build/docker/gotools' failed
make: *** [.build/docker/gotools] Error 2

**Comment by denyeart** [comment]
Please reserve github issue list for code issues.
For getting help please use Discord chat, see https://hyperledger-fabric.readthedocs.io/en/latest/CONTRIBUTING.html#communications-and-getting-help
