### ISSUE TITLE
handshake error : x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by naonan** [hyperledger/fabric#4136]
![image](https://user-images.githubusercontent.com/93034124/229288425-7a64b00c-2ed7-4a1b-aa6f-f328a783459c.png)
help~~~

**Comment by ghost** [comment]
possibly related/duplicate https://github.com/hyperledger/fabric/issues/3507

**Comment by denyeart** [comment]
Please reserve Fabric issue list for code issues. 
For getting community help, see 
https://hyperledger-fabric.readthedocs.io/en/latest/CONTRIBUTING.html#communications-and-getting-help
