### ISSUE TITLE
[CRITICAL] Unprocessed Issues

### ISSUE THREAD

**Issue by ghost** [hyperledger/fabric#4140]
I noticed that there are unprocessed issues, like e.g.:

- https://github.com/hyperledger/fabric/issues/3507

My question is:

Why would a linux-foundation project of the fabric caliber leave issues unprocessed?

The minimum(!) processing for the above issue would be:

- a quick comment that support is not provided here in this repo
  - move the issue to the Q&A discussion (https://github.com/hyperledger/fabric/discussions/categories/q-a)

### Forks vs. Action

* 8.5k Forks, yet the issue-tracker feels like a "dead project".
  * https://github.com/hyperledger/fabric/issues?q=is%3Aissue+is%3Aopen+sort%3Acomments-asc

I do not understand. Where does the development action happen?

**Comment by denyeart** [comment]
The project doesn't use the issues list for usage questions and getting help, but we often leave the issues open in case somebody can help.

If nobody can help, eventually the issue like the one referenced here is closed with a comment like the following:

> Please reserve Fabric issue list for code issues. 
> For getting community help, see 
> https://hyperledger-fabric.readthedocs.io/en/latest/CONTRIBUTING.html#communications-and-getting-help

**Comment by ghost** [comment]
(you should not comment-close)

@denyeart , please be aware that github does not allow the author to reopen issues. I still
