### ISSUE TITLE
Provide basic Issue Templates/Links

### ISSUE THREAD

**Issue by ghost** [hyperledger/fabric#4143]
In order to avoid questions on the issue-tracker, templates can be used. Provide a basic template/link.

(I can do this within the next days)              

---

> The project doesn't use the issues list for usage questions and getting help, but we often leave the issues open in case somebody can help.

If nobody can help, eventually the issue like the one referenced here is closed with a comment like the following:

> Please reserve Fabric issue list for code issues. 
> For getting community help, see 
> https://hyperledger-fabric.readthedocs.io/en/latest/CONTRIBUTING.html#communications-and-getting-help

_Originally posted by @denyeart in https://github.com/hyperledger/fabric/issues/4140#issuecomment-1494552050_

**Comment by ghost** [comment]
> I think the two important issue categories are "Bug Report" which you have, and "Proposed Work Item". Could you add the latter? It could go to a blank entry.
https://github.com/hyperledger/fabric/pull/4144#issuecomment-1494828754

The quasi-standard on github is `bug` (labeled 'bug'), and `Feature Request` (labeled `Enhancement`).

For "Proposed Work Item", could you elaborate a little bit, so I can add an explanation. (who proposes this? if its the visitors, then an `Enhancement/Feature Request` would be more appropriate. If its for the Team, then ok.)

**Comment by denyeart** [comment]
#4144 merged as a first pass on the issue template, thanks @abebeos .

Concerning a second button, I was envisioning it to be used by core contributors for "todos" and "improvements", as well as for public users for "feature requests", hence the generic name. But you're right, let's add two more buttons to make them clear, how about:

- "Feature Request" (`enhancement` label)

and

- "Other work item" (no label)

Both could use a blank template, so the only real difference would be the automatic `enhancement` label.

Thanks again for helping to improve the user community experience.

**Comment by denyeart** [comment]
Also, I'm not seeing the "Support, Help, Questions, Chat" button. Maybe the `about` field is required under contact_links.
See the example at https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser.

**Comment by ghost** [comment]
It should appear, did in other repos. Will take a look later.

**Comment by ghost** [comment]
@denyeart I've create the templates, please feel free to change as you see fit.

Otherwise just add a new label `workitem` (to distinguish from user-filed features, and core-dev file specific/concrete work-items). The current `workitem.yaml` template assigns a `workitem` label.

**Comment by denyeart** [comment]
Thanks @abebeos , looks really good now!
