### ISSUE TITLE
fileutil.CreateDirAll

### ISSUE THREAD

**Issue by Armandavarii** [hyperledger/fabric#4149]
### Description

I'm installing HLF for the first time and came upon a error while running the code 
`make basic-checks integration-test-prereqs`
to verify the build environment.
It says there is a problem with the code in the file vendor/go.etcd.io/etcd/server/v3/wal/wal.go. Specifically, there is a function call to fileutil.CreateDirAll on line 119 that expects two arguments - a *zap.Logger and a string. However, it seems that only a single argument of type string is being passed in.
![Error Screen Shot](https://user-images.githubusercontent.com/95676499/230163495-7533177b-03d5-43d0-970b-483decdcda4c.png)

I have installed go version go1.20.2 linux/amd64

**Comment by denyeart** [comment]
I'm not seeing this issue in main or release-2.5 branches. Both the caller and function called have a single argument in these branches:

https://github.com/hyperledger/fabric/blob/main/vendor/go.etcd.io/etcd/client/pkg/v3/fileutil/fileutil.go#L73

What branch are you using?

**Comment by denyeart** [comment]
Does not appear to be an issue in recent branches and no response from reporter, closing.
