### ISSUE TITLE
Please create an issue-label `workitem`

### ISSUE THREAD

**Issue by ghost** [hyperledger/fabric#4151]
label: `workitem`
description: 'A Work Item, usually created by a core-developer/contributor`

> Otherwise just add a new label `workitem` (to distinguish from user-filed features, and core-dev file specific/concrete work-items). The current `workitem.yaml` template assigns a `workitem` label.

_Originally posted by @abebeos in https://github.com/hyperledger/fabric/issues/4143#issuecomment-1499010581_

**Comment by denyeart** [comment]
Done!
