### ISSUE TITLE
Enrolling Org3 identities - failed with errors [[ { code: 71, message: 'Authorization failure' } ]]

### ISSUE THREAD

**Issue by heryani2007** [hyperledger/fabric#4155]
### Description

Hello, 
Just wanted to bring this to your attention.

Issue -
After spining up Org3 along with all its dependencies. I enrolled the Org3 admin, after which I attempted to enroll the first user. I recieved the following error
(node:11040) UnhandledPromiseRejectionWarning: Error: fabric-ca request register failed with errors [[ { code: 71, message: 'Authorization failure' } ]]

Cause -
The fabric-ca-server-config.yaml located in the fabric-samples/test-network/addOrg3/fabric-ca/org3 directory is incomplete.

Fix -
Modify the fabric-ca-server-config.yaml located in the fabric-samples/test-network/addOrg3/fabric-ca/org3 directory affiliation list to include org3 and at least one department

**Comment by heryani2007** [comment]
Added screenshots of the yaml file before and after the fix
![before fix](https://user-images.githubusercontent.com/99145757/231125014-e3b9ec68-64bc-45f2-8060-bceea32b4f66.png)
![after fix](https://user-images.githubusercontent.com/99145757/231125010-8c8a9398-032f-4a9b-94a1-932b04001f90.png)

**Comment by denyeart** [comment]
Thanks for identifying this. Fixed in https://github.com/hyperledger/fabric-samples/pull/1026
