### ISSUE TITLE
hyperledger fabric delete not deleted

### ISSUE THREAD

**Issue by 2hevva** [hyperledger/fabric#4156]
### Description

github.com/hyperledger/fabric v1.4.12
github.com/hyperledger/fabric-amcl v0.0.0-20210603140002-2670f91851c8 // indirect
system : MacOS-13.2.1 (22D68)-apple silicon
docker desktop:Version4.17.0 (99724)
Engine: 20.10.23
Compose: v2.15.1
Credential Helper: v0.7.0
Kubernetes: v1.25.4

used stub.DelState(key) with not error
but I always can use stub.GetState(key) get this state that is same data, state never changed
I ensure two times used same key, but result make me confused

I run debug in idea(goland), local test use mockstub ,then it worked. that is make me confused more

**Comment by 2hevva** [comment]
update(rePutState) is same failed,can not change anything
first PutState is worked, and GetState is worked

**Comment by denyeart** [comment]
Check your peer log, perhaps the subsequent update/delete transactions are getting invalidated.

You can also enable peer ledger and state database debug to better understand what is going on:
https://hyperledger-fabric.readthedocs.io/en/latest/logging-control.html#typical-debug-levels

**Comment by 2hevva** [comment]
Thank you very much for your reply
I opened the highest level log of the Peer node and found that the reason why my DelState method failed was that the log did not report an error, but stayed at [endorser].
not continued as PutState have method[committer.txvalidator], [blocksProvider], [protoutils]
Is it caused by the endorsement strategy? I use "-P ('TaobaoMSP.member','JDMSP.member')"

**Comment by denyeart** [comment]
Not enough information provided to troubleshoot root cause. What does the peer log indicate?

**Comment by 2hevva** [comment]
I am deeply sorry that due to nesting a layer of GIN requests, I overlooked the issue of multiple empty byte arrays within the GIN, which resulted in unexpected errors in the request for a smart contract.



Thank you very much for your help
