### ISSUE TITLE
peer chaincode query cli error message formatting

### ISSUE THREAD

**Issue by AQBKX** [hyperledger/fabric#4180]
### Description

It seems like the error message returned from the chaincode is encoded and cannot be displayed correctly in Chinese when running the peer's command. The error message looks correct in the server-debug log but when querying through the peer, it returns a decoding error.

The problem could be with the way the error message is presented in the CLI invocation. The line generating the error message could be the cause of the issue, which is located at https://github.com/hyperledger/fabric/blob/aaf9932bd0176eefaac7809d048c45af2ffbc5c8/internal/peer/chaincode/common.go#L157.

One possible solution to this problem is to use proto.MarshalTextString to insert the protocol buffer response message into the error string. More information about using proto.MarshalTextString can be found at https://pkg.go.dev/github.com/golang/protobuf@v1.5.3/proto#MarshalTextString.

### Steps to reproduce

follow the docs to this, 
https://github.com/hyperledger/fabric-samples/blob/main/full-stack-asset-transfer-guide/docs/SmartContractDev/01-Exercise-Getting-Started.md?plain=1#L316
and modify the string into `抱歉，资产 ${id} 尚未创建`  in https://github.com/hyperledger/fabric-samples/blob/main/full-stack-asset-transfer-guide/contracts/asset-transfer-typescript/src/assetTransfer.ts#L54
then can see in sever-debug log 
```
2023-04-24T15:51:36.498Z error [c-api:contracts-spi/chaincodefromcontract.js]     [mychannel-89d03efb] Error: 抱歉，资产 002 尚未创建  
2023-04-24T15:51:36.499Z error [c-api:lib/handler.js]                             [mychannel-89d03efb] Calling chaincode Invoke() returned error response [抱歉，资产 002 尚未创建]. Sending COMPLETED message back to peer  
```
and in org1admin log
```
peer chaincode query -C mychannel -n asset-transfer -c '{"Args":["ReadAsset","002"]}'
Error: endorsement failure during query. response: status:500 message:"\346\212\261\346\255\211\357\274\214\350\265\204\344\272\247 002 \345\260\232\346\234\252\345\210\233\345\273\272" 
```
the right message should  be 
```
peer chaincode query -C mychannel -n asset-transfer -c '{"Args":["ReadAsset","002"]}'
Error: endorsement failure during query. response: status:500 message:"抱歉，资产 002 尚未创建" 
```

**Comment by denyeart** [comment]
The call to `proto.MarshalTextString()` sounds like an appropriate resolution. A pull request would be welcome.

**Comment by AKARSHITJOSHI** [comment]
Hi  @AQBKX I would like to contribute on this. Let me know if I can start.

**Comment by AQBKX** [comment]
hello, first  clone [https://github.com/hyperledger/fabric-samples/blob/main/full-stack-asset-transfer-guide](https://github.com/hyperledger/fabric-samples/blob/main/full-stack-asset-transfer-guide) , and follow docs/SmartContractDev , you will soon watch it, just in doc01 line 316, where error emerges.

**Comment by neonbhai** [comment]
Hi! I would like to work on this.

**Comment by denyeart** [comment]
Thanks @neonbhai , I've assigned to you!

**Comment by rawatsushil** [comment]
Hi 
is this still open ? I would like to start on this
