### ISSUE TITLE
CouchDB memory consumption increases when deploying on RHEL9

### ISSUE THREAD

**Issue by takayuki-nagai** [hyperledger/fabric#4182]
### Description

I've noticed that CouchDB's memory usage increases abnormally when Hyperledger Fabric(HLF) is running on certain operating systems.

I deployed HLF v2.5.0 on a VM with RHEL9 installed and deployed a minimal BC network using fabric-samples/test-network.
Then the memory usage of the CouchDB container reached around 1.5GB.
I also found that the same phenomenon occurs when deploying HLF v2.4 or some earlier versions on RHEL9.
On the other hand, when deploying HLF on RHEL8 or Ubuntu, CouchDB memory usage was only about 50MB.

Due to this phenomenon, when a HLF network consisting of 2 Peers×2 organizations is deployed in one VM for example,
the network cannot be started unless 6 GB of VM memory can be secured for CouchDB.
As a result, even a network with a minimum configuration can only be started on a VM with high specifications.

### Steps to reproduce

After installing HLF by the method described in "Getting Started" section of hyperledger-fabricdocs, execute the following command.

 `cd fabric-samples/test-network `
 `network.sh up createChannel -ca -c mychannel -s couchdb -i 2.0.0 `
 `network.sh deployCC -ccn basic -ccp ../asset-transfer-basic/chaincode-javascript/ -ccl javascript`

**Comment by denyeart** [comment]
This repository is for Fabric code issues. For CouchDB container issues you'll need to raise through the CouchDB community.
