### ISSUE TITLE
Orderer v3: remove system channel: clean up msgprocessor package

### ISSUE THREAD

**Issue by tock-ibm** [hyperledger/fabric#4189]
The orderer/common/msgprocessor contains the 
```
type SystemChannel struct
```
in `systemchannel.go`

and 
```
type SystemChainFilter struct
```
in `systemchannelfilter.go`

These two are no longer used, they should be removed from the package. Note also that the Templator should also be removed, as it is used only by the system channel.

**Comment by JeffySolomBalan** [comment]
Hey! I would like to fix this. Can you please assign this to me

**Comment by semil** [comment]
@JeffySolomBalan thanks, but I am already on it :)
