### ISSUE TITLE
Deadlock on etcd raft orderer chain apply change on orderer startup

### ISSUE THREAD

**Issue by vodsej** [hyperledger/fabric#4199]
### Description

This issue was found on orderer version 2.5.0 is apparently caused by pull request #3919
Deadlock can occur on orderer startup while applying raft configuration changes from previous blocks.

Deadlock occures as follows:

1. [node](https://github.com/hyperledger/fabric/blob/v2.5.0/orderer/consensus/etcdraft/node.go) run function receives `n.Ready()` signal and emits apply change signal (line 156 - `n.chain.applyC <- apply{rd.CommittedEntries, rd.SoftState}`)
2. [chain](https://github.com/hyperledger/fabric/blob/v2.5.0/orderer/consensus/etcdraft/chain.go) run function receives `c.applyC ` signal and start processing received changes with apply function (for loop in run function is blocked by this).
3. As the signal is received by chain, node run for loop is no longer blocked and can proceed and finish the loop iteration and wait for another signal.
4. chain apply function is processing ents and needs to sync WAL. After mentioned pull request it does so by emitting signal to node ( line 1153 - `c.Node.storage.WALSyncC <- struct{}{}` ).  Processing of ents is blocked until signal is received by node. This means that for loop in chain run function for receiving signals is blocked as well.
5. node run function uses select to receive waiting signals. But the selection is random, when multiple signals are waiting. In this situation there are `n.Ready()` `n.storage.WALSyncC` signals waiting for receive. In this scenario `n.Ready()` is selected.
6. Another apply change signal is then emitted  (line 156 - `n.chain.applyC <- apply{rd.CommittedEntries, rd.SoftState}`)
7. We are now in deadlock. node run for loop is blocked by waiting for `n.chain.applyC <- apply{rd.CommittedEntries, rd.SoftState}` receive and chain run for loop is blocked by not finnished apply function, which is waiting for receive of signal `c.Node.storage.WALSyncC <- struct{}{}`

The most simple fix would be to rollback mentioned pull request as it does not introduce new functionality and previous solution worked without any issue. I managed to verify it on local deployment. When v2.5.0 always produces this deadlock, rollbacking this pull request solved deadlock issue.

**Comment by yacovm** [comment]
I think you're right, thanks for the report and the analysis.

Unfortunately just rolling back the change will bring back the [data race reported in the pull request](https://github.com/hyperledger/fabric/issues/3903), and while the data race in the issue is benign, as it is probably caused by a unit test halting the chain manually, I think we can still run into a data race if the node is removed from the channel which will then might be an issue if it is brought back into the channel.

I [pushed a PR](https://github.com/hyperledger/fabric/pull/4201) that both reverts the commit you mentioned and also moves the WAL sync in the chain to the node, making all WAL operations performed from the node's goroutine.

**Comment by vodsej** [comment]
I tested your PR in the same env and it seem to work without any issue. Thanks for the fast response.

**Comment by tock-ibm** [comment]
Done

**Comment by denyeart** [comment]
Backporting to release-2.5 now.

**Comment by tock-ibm** [comment]
> Backporting to release-2.5 now.

The scenario in which this bug might manifests itself is the following:

- a cluster with with N nodes
- one of those nodes (e.g. n1) is stopped or disconnected behind a network partition
- add a N+1th node via a config change
- order some messages, i.e. data transactions
- restart the stopped node n1 or heal the partition
- node n1 might get into a deadlock in which it does not make any progress on the consensus
- the solution is to restart the node n1
