### ISSUE TITLE
Broken link ---- Hyperledger Documentation Standards

### ISSUE THREAD

**Issue by ggold7046** [hyperledger/fabric#4215]
In this page : [Hyperledger Foundation](https://wiki.hyperledger.org/display/INTERN/Hyperledger+Documentation+Standards) there is a Github repo link which is broken.

This is the link : [Broken Link](https://github.com/hyperledger-archives/documentation-guidelines)

**Comment by denyeart** [comment]
Issues in this repository only cover code and docs in this repository, not other Hyperledger foundation wiki pages.
