### ISSUE TITLE
Wrong getTxTimestamp

### ISSUE THREAD

**Issue by vlasenkofedor** [hyperledger/fabric#4219]
### Description

I get the wrong format timestamp
node_modules/fabric-shim-api/types/index.d.ts
```javascript
getTxTimestamp(): Timestamp;
/* ---- */
interface Timestamp {
  seconds: Long;
  nanos: number;
}
```
**dependencies**
```javascript
"dependencies": {
    "fabric-contract-api": "^2.0.0",
    "fabric-shim": "^2.0.0"
},
``` 
**Versions**
```javascript
fabric-ca-client:
Version: 1.5.5
Go version: go1.18.2
OS/Arch: linux/amd64

fabric-ca-server:
Version: 1.5.5
Go version: go1.18.2
OS/Arch: linux/amd64
``` 

### Steps to reproduce

**My code in contract emit the History event**
```javascript
const action = { action: 'deposit', amount, userId, timestamp: ctx.stub.getTxTimestamp()};
ctx.stub.setEvent('Balance:History', Buffer.from(JSON.stringify(action)));
```
**My listener**
```javascript
let listener;
try {
    listener = async (event) => {
        const payload = JSON.parse(event.payload.toString());
        console.log(`*** Event: ${event.eventName}`);
        console.log(payload);
    };
    await contract.addContractListener(listener);
} catch (eventError) {
    console.log(`<-- Failed: Setup contract events - ${eventError}`);
}
``` 
I see in the console
```javascript
*** Event: Balance:History
{
  action: 'deposit',
  amount: '100',
  userId: 'fedor',
  timestamp: {
    wrappers_: null,
    arrayIndexOffset_: -1,
    array: [ 1684164619, 536000000 ],
    pivot_: 1.7976931348623157e+308,
    convertedPrimitiveFields_: {}
  }
}
```
Bad format field timestamp

**Comment by denyeart** [comment]
I think this should be opened against fabric-chaincode-node, but @mbwhite could you take a look?

**Comment by mbwhite** [comment]
@denyeart yes that's correct.

**Comment by vlasenkofedor** [comment]
@mbwhite 
Right what?
In the documentation, in the type code, there is one structure, but as a result, another
https://hyperledger.github.io/fabric-chaincode-node/release-2.2/api/fabric-shim.ChaincodeStub.html#getTxTimestamp

**Comment by mbwhite** [comment]
@vlasenkofedor right as in Dave's assertion the issue should on the fabric-chaincode-node repo.

https://github.com/hyperledger/fabric-chaincode-node/issues/400

**Comment by denyeart** [comment]
Ok, I'll close this one since it will get assessed over in https://github.com/hyperledger/fabric-chaincode-node/issues/400
