### ISSUE TITLE
Incorrect implementation of subscriber, publisher ( Event Emitter) in stub.SetEvent

### ISSUE THREAD

**Issue by vlasenkofedor** [hyperledger/fabric#4220]
### Description

Hi, i use [setEvent](https://hyperledger.github.io/fabric-chaincode-node/release-2.2/api/fabric-shim.ChaincodeStub.html#setEvent)
And I expect here to see a widespread Event Emitter or subscriber publisher

### Steps to reproduce

**In contract**
```javascript
ctx.stub.setEvent('name1', Buffer.from(JSON.stringify({})));
ctx.stub.setEvent('name2', Buffer.from(JSON.stringify({})));
``` 
**listener**
```javascript
let listener;
        try {
            listener = async (event) => {
                const payload = JSON.parse(event.payload.toString());
                console.log(`*** Event: ${event.eventName}`);
                console.log(payload);
            };
            await contract.addContractListener(listener);
        } catch (eventError) {
            console.log(`<-- Failed: Setup contract events - ${eventError}`);
        }
``` 
I only get the event named name2

**Comment by denyeart** [comment]
This is working as expected.
Only a single chaincode event can be included in a transaction. If setEvent() is called multiple times only the last event will be included in the transaction. 
This is documented in the original Go shim:
https://github.com/hyperledger/fabric-chaincode-go/blob/main/shim/interfaces.go#L365-L372

It was not mentioned in the fabric-chaincode-node docs. I've created a PR to mention it:
https://github.com/hyperledger/fabric-chaincode-node/pull/399

FYI @mbwhite

**Comment by denyeart** [comment]
@mbwhite I've also clarified fabric-chaincode-java doc:
https://github.com/hyperledger/fabric-chaincode-java/pull/304

**Comment by vlasenkofedor** [comment]
I will advise you to rename the function (setOneEvent) so you don't get asked questions.
But better you would implement the ability to send multiple events
