### ISSUE TITLE
How to change the time of TIMEOUT

### ISSUE THREAD

**Issue by LCY0710** [hyperledger/fabric#4227]
I want to test a large number of data. It will spend time over 30s. So how can i change it?
` error: [Endorser]: sendProposal[peer0.org2.example.com:9051] - peer0.org2.example.com:9051 timed out after: 30000
2023-05-17T09:03:05.106Z - error: [Endorser]: sendProposal[peer0.org2.example.com:9051] - rejecting with: Error: REQUEST TIMEOUT
2023-05-17T09:03:05.108Z - error: [DiscoveryHandler]: _build_endorse_group_member >> G1:0 - error on endorsement to peer0.org2.example.com:9051 error Error: REQUEST TIMEOUT`

**Comment by bestbeforetoday** [comment]
This looks to be a question about the legacy Node SDK. First thing to say is that moving forwards (Fabric v2.4 and later) you should be looking to use the [Fabric Gateway client API](https://hyperledger.github.io/fabric-gateway/) instead. With this API you have a high degree of control over connection management and timeouts.

With the legacy Node SDK, you can specify in the options passed to the Gateway object's [connect()](https://hyperledger.github.io/fabric-sdk-node/main/module-fabric-network.Gateway.html#connect) function the timeout values for endorsement and waiting for commit status.

**Comment by denyeart** [comment]
Please keep issues in this repository focused on Fabric code issues.
For SDK issues please use fabric-sdk-node or fabric-gateway repository.
For usage questions see:
https://hyperledger-fabric.readthedocs.io/en/latest/CONTRIBUTING.html#communications-and-getting-help
