### ISSUE TITLE
Add a check for V3 style signature - BFT consensus

### ISSUE THREAD

**Issue by arkadiPiven** [hyperledger/fabric#4228]
### Current Status

When running the test-network-nano-bash sample from the latest fabric binaries with BFT consensus I encountered a problem with configtx.yaml - V3 is not set to true explicitly in the configtx.yaml then the MSPId received by the peer from the orderer is empty. This is because the BFT orderer supports the V3 style signature which doesn't
 hold the certificate of the orderer that signed in the payload of the message, as a contrast to the V2.X style signature.
The current status is that Fabric doesn't have any check in the code that warns what kind of style is supported.
<img width="1042" alt="Screenshot 2023-05-17 at 16 23 25" src="https://github.com/hyperledger/fabric/assets/48690203/7247a5c8-2631-43f0-aca8-ab24d9d43b92">

### Expected

Add a check for when a channel is created,
If using V3 style signature then nothing printed,
If using V2.X style signature then print a warning.

### Solution

Couple of solution are valid,

1. If we're using a profile with orderer type BFT then we can print a warning log if the channel capabilities are set to V2.X when the first orderer joins the channel.
2. When running the command to create the genesis block we can print a warning log if the channel capabilities are set to V2.X in the configtx.yaml.

### Please let us know if you plan to work on this.

Maybe.

**Comment by yacovm** [comment]
Possible solutions could be: 

1. Not allow a BFT orderer to join a channel without the V3 capabilities enabled - we need to ensure that we don't commit the genesis block before creating the chain instance.
2. Make configtxgen reject creating a BFT genesis block if V3 capabilities are not set

I think (2) is easiest.

**Comment by yacovm** [comment]
@semil do you want to take a look at this?

**Comment by semil** [comment]
@yacovm yes, on it :)
