### ISSUE TITLE
Communication peer->chaincode as a service uses default 4MB gRPC message size

### ISSUE THREAD

**Issue by delaooliveira** [hyperledger/fabric#4245]
Hello everyone,

I was meddling with using an external builder and a chaincode as a service style of network. In my last tests, I found that if I try to execute a submit transaction with a payload larger than 4MB, I get the following message from the peer:
 
```
2023-05-30 21:16:08.425 -03 197f DEBU [chaincode] ProcessStream -> rpc error: code = ResourceExhausted desc = Received message larger than max (4782046 vs. 4194304)
```
which indicates the gRPC connection between the peer and the chaincode is using the default of 4MB.

My first thought was to change the gRPC option on the chaincode part (using node.js) and what was once:
`
fabric-chaincode-node server --chaincode-address=localhost:7100 --chaincode-id=<ccid> --chaincode-tls-cert-file=<path> --chaincode-tls-key-file=<path>",
`
became
`
fabric-chaincode-node server --chaincode-address=localhost:7100 --chaincode-id=<ccid> --chaincode-tls-cert-file=<path> --chaincode-tls-key-file=<path> --grpc.max_send_message_length=104857600 --grpc.max_receive_message_length=104857600",
`
however, nothing happened. 

Looking at core/chaincode/extcc/extcc_handler.go I found that the stream is initiated by the peer and  the ExternalChaincodeRuntime doesn't pass any gRPC Options when the connection is made, so I'm guessing it uses the default gRPC options ( such as 4MB message max size ).

Is there a way to modify the gRPC options on this, or am I just doing something wrong in my configs?

I'm running peer version 2.5.0 and fabric-contract-api and fabric-shim node libs @ 2.5.2

Thanks in advance.

**Comment by denyeart** [comment]
@mbwhite Can you take a look?

**Comment by delaooliveira** [comment]
@denyeart I actually found out that the gRPC server in fabric-shim on fabric-chaincode-node is ignoring any CLI arguments. I've made a PR on that repo fixing it. I don't think this issue should be open here anymore.

**Comment by denyeart** [comment]
Excellent, then we'll ask @mbwhite to review the PR - https://github.com/hyperledger/fabric-chaincode-node/pull/401
