### ISSUE TITLE
Peer panic when start with arm cpu

### ISSUE THREAD

**Issue by Virus-Syl** [hyperledger/fabric#4249]
### Description

2023-06-01 11:01:35.215 CST [nodeCmd] serve -> INFO 006 Starting peer with TLS enabled
unexpected fault address 0x64393137663f1d
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x64393137663f1d pc=0xf19820]

goroutine 1 [running]:
runtime.throw(0x16ba01e, 0x5)
	/usr/local/go/src/runtime/panic.go:1117 +0x54 fp=0x4000a85fa0 sp=0x4000a85f70 pc=0x984534
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:741 +0x230 fp=0x4000a85fe0 sp=0x4000a85fa0 pc=0x99c3f0
github.com/golang/snappy.encodeBlock(0x400026ea82, 0x97e, 0x97e, 0x40004d0000, 0x805, 0x1100, 0x40001e6001)
	/go/src/github.com/hyperledger/fabric/vendor/github.com/golang/snappy/encode_arm64.s:666 +0x360 fp=0x4000a8e080 sp=0x4000a85ff0 pc=0xf19820
github.com/golang/snappy.Encode(0x400026ea80, 0x980, 0x980, 0x0, 0x0, 0x0, 0x1, 0x40003a64c0, 0x100)
	/go/src/github.com/hyperledger/fabric/vendor/github.com/golang/snappy/encode.go:39 +0x17c fp=0x4000a8e0d0 sp=0x4000a8e080 pc=0xf184ac
github.com/syndtr/goleveldb/leveldb/table.(*Writer).writeBlock(0x4000372d80, 0x4000372dd8, 0x2, 0x79, 0x40001e61a8, 0xf20d44, 0x40001e6268)
	/go/src/github.com/hyperledger/fabric/vendor/github.com/syndtr/goleveldb/leveldb/table/writer.go:171 +0xb0 fp=0x4000a8e150 sp=0x4000a8e0d0 pc=0xf21540
github.com/syndtr/goleveldb/leveldb/table.(*Writer).finishBlock(0x4000372d80, 0xf21be0, 0x400010ca00)
	/go/src/github.com/hyperledger/fabric/vendor/github.com/syndtr/goleveldb/leveldb/table/writer.go:222 +0x4c fp=0x4000a8e1a0 sp=0x4000a8e150 pc=0xf219dc
github.com/syndtr/goleveldb/leveldb/table.(*Writer).Close(0x4000372d80, 0x400010c900, 0x40001e6308)
	/go/src/github.com/hyperledger/fabric/vendor/github.com/syndtr/goleveldb/leveldb/table/writer.go:295 +0x40 fp=0x4000a8e280 sp=0x4000a8e1a0 pc=0xf21dd0
github.com/syndtr/goleveldb/leveldb.(*tWriter).finish(0x400037b020, 0x0, 0x0, 0x0)
	/go/src/github.com/hyperledger/fabric/vendor/github.com/syndtr/goleveldb/leveldb/table.go:578 +0x58 fp=0x4000a8e310 sp=0x4000a8e280 pc=0xf43a88
github.com/syndtr/goleveldb/leveldb.(*tOps).createFrom(0x4000379890, 0x186dd58, 0x4000374b80, 0x0, 0xc, 0x0, 0x0)
	/go/src/github.com/hyperledger/fabric/vendor/github.com/syndtr/goleveldb/leveldb/table.go:408 +0x1c0 fp=0x4000a8e3b0 sp=0x4000a8e310 pc=0xf42cc0
github.com/syndtr/goleveldb/leveldb.(*session).flushMemdb(0x40002243c0, 0x4000229b80, 0x40003860e0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/hyperledger/fabric/vendor/github.com/syndtr/goleveldb/leveldb/session_compaction.go:35 +0xa4 fp=0x4000a8e510 sp=0x4000a8e3b0 pc=0xf3ada4
github.com/syndtr/goleveldb/leveldb.(*DB).recoverJournal(0x40003c01c0, 0x40003c01c0, 0x400004c300)
	/go/src/github.com/hyperledger/fabric/vendor/github.com/syndtr/goleveldb/leveldb/db.go:612 +0xa80 fp=0x4000a8e730 sp=0x4000a8e510 pc=0xf26a70
github.com/syndtr/goleveldb/leveldb.openDB(0x40002243c0, 0x0, 0x0, 0x40002243c0)
	/go/src/github.com/hyperledger/fabric/vendor/github.com/syndtr/goleveldb/leveldb/db.go:131 +0x488 fp=0x4000a8e820 sp=0x4000a8e730 pc=0xf25ab8
github.com/syndtr/goleveldb/leveldb.Open(0x186d438, 0x40000e8ee0, 0x40001e6988, 0x0, 0x0, 0x0)
	/go/src/github.com/hyperledger/fabric/vendor/github.com/syndtr/goleveldb/leveldb/db.go:203 +0xd0 fp=0x4000a8e890 sp=0x4000a8e820 pc=0xf25d10
github.com/syndtr/goleveldb/leveldb.OpenFile(0x4000251960, 0x1b, 0x40001e6988, 0x0, 0x0, 0x0)
	/go/src/github.com/hyperledger/fabric/vendor/github.com/syndtr/goleveldb/leveldb/db.go:225 +0x7c fp=0x4000a8e910 sp=0x4000a8e890 pc=0xf25f0c
github.com/hyperledger/fabric/common/ledger/util/leveldbhelper.(*DB).Open(0x4000346e60)
	/go/src/github.com/hyperledger/fabric/common/ledger/util/leveldbhelper/leveldb_helper.go:74 +0x104 fp=0x4000a8eae0 sp=0x4000a8e910 pc=0xf4e754
github.com/hyperledger/fabric/common/ledger/util/leveldbhelper.openDBAndCheckFormat(0x400036b1e0, 0x0, 0x0, 0x0)
	/go/src/github.com/hyperledger/fabric/common/ledger/util/leveldbhelper/leveldb_provider.go:72 +0xf4 fp=0x4000a8ec70 sp=0x4000a8eae0 pc=0xf4fdc4
github.com/hyperledger/fabric/common/ledger/util/leveldbhelper.NewProvider(0x400036b1e0, 0x400036b1e0, 0x1, 0x4000251960)
	/go/src/github.com/hyperledger/fabric/common/ledger/util/leveldbhelper/leveldb_provider.go:60 +0x28 fp=0x4000a8ecb0 sp=0x4000a8ec70 pc=0xf4fc18
github.com/hyperledger/fabric/core/transientstore.NewStoreProvider(0x4000251960, 0x1b, 0x2, 0x4000251960, 0x1b, 0x40003791a0)
	/go/src/github.com/hyperledger/fabric/core/transientstore/store.go:83 +0x58 fp=0x4000a8ecf0 sp=0x4000a8ecb0 pc=0xf6bbb8
github.com/hyperledger/fabric/internal/peer/node.serve(0x208b1e8, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/hyperledger/fabric/internal/peer/node/start.go:282 +0x9a8 fp=0x4000a8fcd0 sp=0x4000a8ecf0 pc=0x132c1f8
github.com/hyperledger/fabric/internal/peer/node.glob..func6(0x1f52a20, 0x208b1e8, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/hyperledger/fabric/internal/peer/node/start.go:127 +0x84 fp=0x4000a8fd20 sp=0x4000a8fcd0 pc=0x1335e84
github.com/spf13/cobra.(*Command).execute(0x1f52a20, 0x208b1e8, 0x0, 0x0, 0x1f52a20, 0x208b1e8)
	/go/src/github.com/hyperledger/fabric/vendor/github.com/spf13/cobra/command.go:762 +0x320 fp=0x4000a8fde0 sp=0x4000a8fd20 pc=0x11fa8a0
github.com/spf13/cobra.(*Command).ExecuteC(0x1f53140, 0x40001e7f40, 0x1, 0x1)
	/go/src/github.com/hyperledger/fabric/vendor/github.com/spf13/cobra/command.go:852 +0x22c fp=0x4000a8fec0 sp=0x4000a8fde0 pc=0x11fb07c
github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/github.com/hyperledger/fabric/vendor/github.com/spf13/cobra/command.go:800
main.main()
	/go/src/github.com/hyperledger/fabric/cmd/peer/main.go:54 +0x3d8 fp=0x4000a8ff70 sp=0x4000a8fec0 pc=0x13386f8
runtime.main()
	/usr/local/go/src/runtime/proc.go:225 +0x274 fp=0x4000a8ffd0 sp=0x4000a8ff70 pc=0x986c84
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1130 +0x4 fp=0x4000a8ffd0 sp=0x4000a8ffd0 pc=0x9bc414

goroutine 7 [IO wait]:
internal/poll.runtime_pollWait(0x7f782e2178, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:227 +0x44
internal/poll.(*pollDesc).wait(0x40002f4e98, 0x72, 0x0, 0x0, 0x16bc7f0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x38
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0x40002f4e80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:401 +0x1b0
net.(*netFD).accept(0x40002f4e80, 0x7fa1abaa68, 0x30, 0x40005360c0)
	/usr/local/go/src/net/fd_unix.go:172 +0x2c
net.(*TCPListener).accept(0x4000304720, 0xa040ac, 0x30, 0x15ed1e0)
	/usr/local/go/src/net/tcpsock_posix.go:139 +0x2c
net.(*TCPListener).Accept(0x4000304720, 0x40005360c0, 0x1730b00, 0x40002f05c0, 0x14df6a0)
	/usr/local/go/src/net/tcpsock.go:261 +0x5c
net/http.(*Server).Serve(0x40002f0540, 0x185b8b0, 0x4000304720, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2962 +0x234
created by github.com/hyperledger/fabric/core/operations.(*System).Start
	/go/src/github.com/hyperledger/fabric/core/operations/system.go:121 +0x168

goroutine 8 [select]:
github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0x4000386000)
	/go/src/github.com/hyperledger/fabric/vendor/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:209 +0xcc
created by github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
	/go/src/github.com/hyperledger/fabric/vendor/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:240 +0x154

goroutine 9 [select]:
github.com/syndtr/goleveldb/leveldb.(*session).refLoop(0x40002243c0)
	/go/src/github.com/hyperledger/fabric/vendor/github.com/syndtr/goleveldb/leveldb/session_util.go:189 +0x3b0
created by github.com/syndtr/goleveldb/leveldb.newSession
	/go/src/github.com/hyperledger/fabric/vendor/github.com/syndtr/goleveldb/leveldb/session.go:93 +0x22c

**Comment by denyeart** [comment]
What version of Fabric?
Where did you get the images or binaries?
How are you starting it?

Note that v2.5 was the first release with arm64 images and binaries.

**Comment by Virus-Syl** [comment]
Thanks for your answer！ I used version v2.2.8. I will try the version of v2.5,I hope it solves my problem。
