### ISSUE TITLE
Where can I view the  latest  official performance test report

### ISSUE THREAD

**Issue by mqtusi** [hyperledger/fabric#4250]
### Description

very appreciated, Where can I view the  latest  official performance test report? i  found  some last urls all invalid

**Comment by davidkel** [comment]
@mqtusi there is a blog posted at https://www.hyperledger.org/blog/2023/02/16/benchmarking-hyperledger-fabric-2-5-performance with basic performance figures as well as a reference to the performance considerations in the hyperledger fabric documentation. This is all that is available for performance information.

**Comment by mqtusi** [comment]
> @mqtusi there is a blog posted at https://www.hyperledger.org/blog/2023/02/16/benchmarking-hyperledger-fabric-2-5-performance with basic performance figures as well as a reference to the performance considerations in the hyperledger fabric documentation. This is all that is available for performance information.

big help,thanks!

**Comment by mqtusi** [comment]
thanks!
