### ISSUE TITLE
Error: chaincode install failed with status: 500

### ISSUE THREAD

**Issue by bajiang1** [hyperledger/fabric#4272]
### Description

Docker version 24.0.2  ，Ubuntu18.04  ，hyperledgerfabric2.3

Error: chaincode install failed with status: 500 - error in simulation: failed to execute transaction 7d0547029f57a3970601075137ccb72956d6dd12c03b823c935e6d62dc7b5c56: error sending: timeout expired while executing transaction
Chaincode installation on peer0.org1 has failed
Deploying chaincode failed

thank you for your help

**Comment by bajiang1** [comment]
Here is the log of the docker container
ProcessProposal -> Failed to invoke chaincode channel= chaincode=_lifecycle error="error in simulation: failed to execute transaction 7d0547029f57a3970601075137ccb72956d6dd12c03b823c935e6d62dc7b5c56: error sending: timeout expired while executing transaction"

**Comment by Pavani-2002** [comment]
> Here is the log of the docker container ProcessProposal -> Failed to invoke chaincode channel= chaincode=_lifecycle error="error in simulation: failed to execute transaction 7d0547029f57a3970601075137ccb72956d6dd12c03b823c935e6d62dc7b5c56: error sending: timeout expired while executing transaction"

Did you find the solution for the above problem

**Comment by lisunans** [comment]
> ### Description
> Docker version 24.0.2 ，Ubuntu18.04 ，hyperledgerfabric2.3
> 
> Error: chaincode install failed with status: 500 - error in simulation: failed to execute transaction 7d0547029f57a3970601075137ccb72956d6dd12c03b823c935e6d62dc7b5c56: error sending: timeout expired while executing transaction Chaincode installation on peer0.org1 has failed Deploying chaincode failed
> 
> thank you for your help
> 
> ### Steps to reproduce
> _No response_

I have the same problem as you, and I have successfully solved it
export GOMOD="{your-fabric-path}/fabric-samples/asset-transfer-basic/chaincode-go/go.mod"
