### ISSUE TITLE
Error: proposal failed (err: rpc error: code = Unknown desc = error validating proposal: access denied: channel [] creator org unknown, creator is malformed)

### ISSUE THREAD

**Issue by lichuanzs** [hyperledger/fabric#4284]
I'm building a network of three orderers, four organizations, one peer for each organization, and I can create channel, but I get the following error when I add the organization's peer to the channel:
“Error: proposal failed (err: rpc error: code = Unknown desc = error validating proposal: access denied: channel [] creator org unknown, creator is malformed)”, How can I solve this problem?

**Comment by denyeart** [comment]
Please use Discord chat for usage questions and errors:
https://hyperledger-fabric.readthedocs.io/en/latest/CONTRIBUTING.html#communications-and-getting-help

**Comment by Zegic** [comment]
i have the same question
