### ISSUE TITLE
BFT config: Merge batch size in configtx for both Raft and BFT

### ISSUE THREAD

**Issue by HagarMeir** [hyperledger/fabric#4294]
### Current Status

In `sampleconfig/configtx.yaml` there is `BatchSize` under `Orderer` used by Raft and under `SmartBFT` we have `RequestBatchMaxBytes` for example. 

### Expected

Have one setting in `configtx.yaml` for batch size used by both Raft and SmartBFT.

### Please let us know if you plan to work on this.

Maybe.

**Comment by aruns05** [comment]
@HagarMeir  I am interested in this. Can we connect for this ?

**Comment by yacovm** [comment]
@aruns05 you can push a PR if you want.

Look at [this function](https://github.com/hyperledger/fabric/blob/main/orderer/consensus/smartbft/util.go#L192) and change it accordingly.

**Comment by yacovm** [comment]
`support.SharedConfig().BatchSize()` and `support.SharedConfig().BatchTimeout()` can be accessed [here](https://github.com/hyperledger/fabric/blob/main/orderer/consensus/smartbft/consenter.go#L164):

**Comment by aruns05** [comment]
@yacovm  sure i will do

**Comment by yacovm** [comment]
@aruns05 any progress on this?

**Comment by aruns05** [comment]
Hello @yacovm  I will take this up shortly.

**Comment by yacovm** [comment]
> Hello @yacovm I will take this up shortly.

I'm sorry but it has almost been 3 weeks and this is still not done, so in the meantime @semil [did it](https://github.com/hyperledger/fabric/pull/4325).

If you want you can add tests to his PR if he won't do that before.

Please understand that we cannot wait indefinitely for tasks to be completed as we need to release BFT in a timely manner.
