### ISSUE TITLE
Add SmartBFT consensus knobs to configtx.yaml and make sure they are used

### ISSUE THREAD

**Issue by HagarMeir** [hyperledger/fabric#4295]
### Current Status

Currently `sampleconfig/configtx.yaml` doesn't show the SmartBFT consensus knobs.
An example can be found here: [https://github.com/hyperledger/fabric-samples/blob/main/test-network-nano-bash/bft-config/configtx.yaml#LL272C11-L272C11](url)

### Expected

The `configtx.yaml` should show the SmartBFT consensus knobs as in the Fabric samples.
Also one should make sure they are used properly. 

### Please let us know if you plan to work on this.

Maybe.

**Comment by aruns05** [comment]
@HagarMeir   is this being worked upon ?

**Comment by HagarMeir** [comment]
@aruns05 not that I know of

**Comment by yacovm** [comment]
@HagarMeir please if you have cycles, take care of it :-)

**Comment by aruns05** [comment]
@HagarMeir  I am keen to work on BFT.. can we connect if you are ok ?
