### ISSUE TITLE
Error: proposal failed (err: rpc error: code = Unknown desc = error validating proposal: access denied: channel [] creator org unknown, creator is malformed)

### ISSUE THREAD

**Issue by DarkShining-Orb** [hyperledger/fabric#4313]
### Description

I'm building a network of five orderers, two organizations, one peer for each organization, and I can create channel, but I get the following error when I add the organization's peer to the channel:
`peer channel join -b mychannel.block`
“Error: proposal failed (err: rpc error: code = Unknown desc = error validating proposal: access denied: channel [] creator org unknown, creator is malformed)”, How can I solve this problem?
What's more, the logs in the peer node reports that something wrong
`2023-07-10 13:45:12.330 UTC 00c9 WARN [endorser] Validate -> access denied channel= txID=7f6680e5 error="the supplied identity is not valid: x509: certificate signed by unknown authority" errorVerbose="x509: certificate signed by unknown authority\nthe supplied identity is not valid" identity="(mspid=Org1MSP subject=CN=Admin@org1.yyk.com,OU=admin,L=San Francisco,ST=California,C=US issuer=CN=ca.org1.yyk.com,O=org1.yyk.com,L=San Francisco,ST=California,C=US serialnumber=109329190946773132965003472001475745657)"
2023-07-10 13:45:12.330 UTC 00ca WARN [endorser] ProcessProposal -> Failed to preProcess proposal error="error validating proposal: access denied: channel [] creator org unknown, creator is malformed"
2023-07-10 13:45:12.330 UTC 00cb INFO [comm.grpc.server] 1 -> unary call completed grpc.service=protos.Endorser grpc.method=ProcessProposal grpc.peer_address=172.18.0.17:43598 error="error validating proposal: access denied: channel [] creator org unknown, creator is malformed" grpc.code=Unknown grpc.call_duration=752.87µs
2023-07-10 13:45:12.332 UTC [grpc] InfoDepth -> DEBU 005 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"`
It seems that I've got the same problem with another friend. But it was solve by the Discord so I cannot get any information about how to solve the problem. Could you please give me some help？

**Comment by DarkShining-Orb** [comment]
Oh, I finally find the solution to the problems——
Add the following configuration in the docker-compose.yaml, in the peer node:
`- CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp/`
the value need to be consistent with what you set in the `volumes`:
such as
`volumes:
      - /var/run/:/host/var/run/
      - ./organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp:/etc/hyperledger/fabric/msp
      - ./organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls:/etc/hyperledger/fabric/tls
      - peer0.org1.example.com:/var/hyperledger/production`
, and please use the path to your peer's msp .
I have done this and solved this problem, hoping to be helpful to those in need.
My English is not good, please forgive me!

**Comment by DarkShining-Orb** [comment]
Oh, I finally find the solution to the problems——
Add the following configuration in the docker-compose.yaml, in the peer node:
`- CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp/`
the value need to be consistent with what you set in the `volumes`:
such as
`volumes:
      - /var/run/:/host/var/run/
      - ./organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp:/etc/hyperledger/fabric/msp
      - ./organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls:/etc/hyperledger/fabric/tls
      - peer0.org1.example.com:/var/hyperledger/production`
, and please use the path to your peer's msp .
I have done this and solved this problem, hoping to be helpful to those in need.
My English is not good, please forgive me!

**Comment by 145d** [comment]
我也是这个错误，但是我是这样部署的- CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org.test.com/users/Admin@org.test.com/msp

**Comment by 145d** [comment]
peer1加入的时候报
[root@prod603 multiple-deployment]#  docker exec cli peer channel join -b ./channel-artifacts/channel-1.block
2023-11-28 11:49:24.835 UTC 0001 WARN [main] InitCmd -> CORE_LOGGING_LEVEL is no longer supported, please use the FABRIC_LOGGING_SPEC environment variable
2023-11-28 11:49:24.837 UTC 0002 WARN [main] SetOrdererEnv -> CORE_LOGGING_LEVEL is no longer supported, please use the FABRIC_LOGGING_SPEC environment variable
2023-11-28 11:49:24.840 UTC 0003 INFO [channelCmd] InitCmdFactory -> Endorser and orderer connections initialized
Error: proposal failed (err: rpc error: code = Unknown desc = error validating proposal: access denied: channel [] creator org unknown, creator is malformed)

**Comment by dyc1104** [comment]
> 我也是这个错误，但是我是这样部署的- CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org.test.com/users/[Admin@org.test.com](mailto:Admin@org.test.com)/msp

你好，请问你这样部署会报错吗

**Comment by lan-vin** [comment]
我是peer的名字大小写混乱，改过来就好了
