### ISSUE TITLE
Failed to generate platform-specific docker build: Error returned from build: 1 "no required module provides package github.com/fabcar: go.mod file not found in current directory or any parent directory; see 'go help modules'

### ISSUE THREAD

**Issue by 2419174660** [hyperledger/fabric#4336]
### Description

My environment：
fabric 1.4
ubuntu 20.04
docker  20.10.23
docker-compose 2.15.1
go 1.20.1

problem：install  chaincode success ，but fail to instantiate the chaincode.

I find my chaindode in the peer container path:/var/hyperledger/production/chaincodes
its name is fabcar.1 ,I think it named by the chaincodeName and version which i set at the install  perior.
I make sure that my chaincode source has go.mod and vendor file.
![image](https://github.com/hyperledger/fabric/assets/65146573/56c5c9e4-71ac-4a63-9459-30b7f630c65e)
and also install the chaincode successfully 
![image](https://github.com/hyperledger/fabric/assets/65146573/0d62db26-80e2-4e67-8dba-94a59a0fba8f)

`public Collection<ProposalResponse> instantiateChainCode(String chaincodeName, String version, String chaincodePath,
			String language, String functionName, String[] functionArgs, String policyPath)
			throws InvalidArgumentException, ProposalException, ChaincodeEndorsementPolicyParseException, IOException {
		Logger.getLogger(ChannelClient.class.getName()).log(Level.INFO,
				"Instantiate proposal request " + chaincodeName + " on channel " + channel.getName()
						+ " with Fabric client " + fabClient.getInstance().getUserContext().getMspId() + " "
						+ fabClient.getInstance().getUserContext().getName());
		InstantiateProposalRequest instantiateProposalRequest = fabClient.getInstance()
				.newInstantiationProposalRequest();
		instantiateProposalRequest.setProposalWaitTime(180000);
		ChaincodeID.Builder chaincodeIDBuilder = ChaincodeID.newBuilder().setName(chaincodeName).setVersion(version)
				.setPath(chaincodePath);
		ChaincodeID ccid = chaincodeIDBuilder.build();
		Logger.getLogger(ChannelClient.class.getName()).log(Level.INFO,
				"Instantiating Chaincode ID " + chaincodeName + " on channel " + channel.getName());
		instantiateProposalRequest.setChaincodeID(ccid);
		if (language.equals(Type.GO_LANG.toString()))
			instantiateProposalRequest.setChaincodeLanguage(Type.GO_LANG);
		else
			instantiateProposalRequest.setChaincodeLanguage(Type.JAVA);

		instantiateProposalRequest.setFcn(functionName);
		instantiateProposalRequest.setArgs(functionArgs);
		Map<String, byte[]> tm = new HashMap<>();
		tm.put("HyperLedgerFabric", "InstantiateProposalRequest:JavaSDK".getBytes(UTF_8));
		tm.put("method", "InstantiateProposalRequest".getBytes(UTF_8));
		instantiateProposalRequest.setTransientMap(tm);

		if (policyPath != null) {
			ChaincodeEndorsementPolicy chaincodeEndorsementPolicy = new ChaincodeEndorsementPolicy();
			chaincodeEndorsementPolicy.fromYamlFile(new File(policyPath));
			instantiateProposalRequest.setChaincodeEndorsementPolicy(chaincodeEndorsementPolicy);
		}

		Collection<ProposalResponse> responses = channel.sendInstantiationProposal(instantiateProposalRequest);
		CompletableFuture<TransactionEvent> cf = channel.sendTransaction(responses);

		Logger.getLogger(ChannelClient.class.getName()).log(Level.INFO,
				"Chaincode " + chaincodeName + " on channel " + channel.getName() + " instantiation " + cf);
		return responses;
	}`
my instanstiate code ,I find  whatever the chaincodePath is ,i get the error log .
![image](https://github.com/hyperledger/fabric/assets/65146573/870a165d-8d1f-46c8-af3e-6ceb4acd86b5)
Firstly ,I set the chaincode path as same as the install period,wrong. Then ,I try many path ,just like  /var/hyperledger/production/chaincodes,also fail.
I have no way.Please help me.

**Comment by denyeart** [comment]
Go modules were not supported in Fabric v1.4.
The latest version of Go tested with Fabric v1.4 was Go 1.14.
Further, Fabric v1.4 has not been supported or maintained in a couple years.
Please utilize Fabric v2.2 or v2.5 LTS releases which have been updated to support Go modules and Go 1.20.
For usage help, please utilize Discord and reserve issues for code bugs see https://hyperledger-fabric.readthedocs.io/en/latest/CONTRIBUTING.html#communications-and-getting-help

**Comment by 2419174660** [comment]
Thank you for your answer!

**Comment by 2419174660** [comment]
But my project must use fabric1.4. If i want to use,how can i install the chaincode written by java
