### ISSUE TITLE
Cannot download fabric samples by using curl.

### ISSUE THREAD

**Issue by 3956ray** [hyperledger/fabric#4357]
Hi there, there is a problem has bother me whole day. this is my environment.

Env: WSL2-Ubuntu20.04
Docker version: 24.0.5, build ced0996
docker-compose:  1.25.0, build unknown

I follow tutorial to download samples, but there is a error that always exist is 
`fabric-samples v2.5.3 does not exist, defaulting to main. fabric-samples main branch is intended to work with recent versions of fabric.`
I have tried 2 types of command that tutorial provided.

`curl -sSL https://bit.ly/2ysbOFE | bash -s`

and

`curl -sSL https://raw.githubusercontent.com/hyperledger/fabric/main/scripts/bootstrap.sh| bash -s`

but still cannot resolve it.
I have no idea about it.
plz help me tks.

**Comment by denyeart** [comment]
The message `fabric-samples v2.5.3 does not exist, defaulting to main` is expected.
fabric-samples main branch should work with Fabric v2.5.3, and therefore there is no need for the project to create a v2.5.3 tag in fabric-samples.
Did you hit an actual problem when running the samples? Or you were just concerned about this message?
