### ISSUE TITLE
Besu - QBFT - Free Gas

### ISSUE THREAD

**Issue by mydappwallet** [hyperledger/fabric#4363]
### Description

I want to run private network with QBFT consensus and free gas network
When I run besu with parameter --min-gas-price=0 besu log the warning: 
 _--min-gas-price has been ignored because --miner-enabled was not defined on the command line._

### Steps to reproduce
_besu --data-path=data --genesis-file=../genesis.json --rpc-http-enabled --rpc-http-api=ETH,NET,QBFT,WEB3 --host-allowlist="*" --rpc-http-cors-origins="all" --min-gas-price=0_
_No response_

**Comment by bestbeforetoday** [comment]
You probably want the [hyperledger/besu](https://github.com/hyperledger/besu) project, not Hyperledger Fabric.
