### ISSUE TITLE
image not found hyperledger/fabric-baseos:3.0

### ISSUE THREAD

**Issue by SamYuan1990** [hyperledger/fabric#4423]
### Description

```
Error: chaincode install failed with status: 500 - failed to invoke backing implementation of 'InstallChaincode': could not build chaincode: docker build failed: docker image build failed: manifest for hyperledger/fabric-baseos:3.0 not found: manifest unknown: manifest unknown
```
https://github.com/Hyperledger-TWGC/tape/actions/runs/6074480460/job/16478756610?pr=296#step:5:863

I try to deployment fabric 3.0 with bft preview and also with chaincode. I tried to install chaincode but failed as base image not found.

### Steps to reproduce

```
      curl -sSLO https://raw.githubusercontent.com/hyperledger/fabric/main/scripts/install-fabric.sh && chmod +x install-fabric.sh
      ./install-fabric.sh --fabric-version 3.0.0-preview
      cd fabric-samples/test-network
      echo y |  ./network.sh up createChannel -bft -c mychannel
      ARGS=(-cci initLedger)
      echo y |  ./network.sh deployCC -ccn basic -ccp ../asset-transfer-basic/chaincode-go/ -ccl go "${ARGS[@]}"
```

**Comment by satota2** [comment]
Hello @SamYuan1990

It seems to be caused by not pulling the baseos image in case of v3.x in install-fabric.sh.
I have created and submitted a patch to fix this(See https://github.com/hyperledger/fabric/pull/4424).

**Comment by SamYuan1990** [comment]
the fix LGTM
