### ISSUE TITLE
Inconsistency in Certification Authority in network diagrams

### ISSUE THREAD

**Issue by AnejVovcak** [hyperledger/fabric#4436]
### Description

On the documentation page https://hyperledger-fabric.readthedocs.io/en/release-2.4/network/network.html, I have noticed an inconsistency in the representation of Certification Authority CA0. In the first five diagrams, CA0 is depicted as the CA of organization R0. However, starting from the sixth diagram and onwards, the green CA is linked to CA4, which seems to be incorrect, since there is no organization R4. Looking at the commits it seems that there was a R4 organization presented on this page in a previous version. Maybe that's where the mix-up started. Thank you for looking into this and please let me know if I misunderstood the diagrams.

### Steps to reproduce

Go to page https://hyperledger-fabric.readthedocs.io/en/release-2.4/network/network.html.

**Comment by denyeart** [comment]
Thanks for identifying the issue. I believe the diagram source is at docs/source/diagrams/diagrams.pptx. It would be great to fix the source and the diagram images in main branch. I've tagged as a `good first issue` for somebody to work on.
