### ISSUE TITLE
Chaincode deployment not working for Fabric v2.5.4

### ISSUE THREAD

**Issue by RajanHarshit** [hyperledger/fabric#4442]
### Description

Hi,
I am using :-
(As per 2.5.4 release note)

**GO**                _v1.20.6_
**FABRIC**          _v2.5.4_
**COUCH_DB**   _v3.3.2_
**CA_VERSION** _v1.5.6_
**DOCKER**        _v20.10.23_

Fabric network created successfully , Now I am trying to deploy chaincode on fabric v2.5.4. 
I've exported below ENV inside peer's (peer0.org1.example.com) container

**CORE_PEER_MSPCONFIGPATH**=_/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp_

By using below command to approve chaincode

`peer lifecycle chaincode approveformyorg -o orderer0.example.com:7050 --ordererTLSHostnameOverride orderer0.example.com --channelID mychannel --name mychaincode --version 1.0 --init-required --package-id mychaincode_1.0:73c07bbd11f903aaaea27cc6043109fb6fb6997c98fd89ed343938613f544d9a --sequence 1 --tls true --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/example.com/orderers/orderer0.example.com/msp/tlscacerts/tlsca.example.com-cert.pem`

I am getting this error.

**Error: proposal failed with status: 500 - Failed to authorize invocation due to failed ACL check: Failed deserializing proposal creator during channelless check policy with policy [Admins]: [the supplied identity is not valid: x509: certificate signed by unknown authority]**

**peer logs**

_Failed deserializing proposal creator during channelless check policy error="the supplied identity is not valid: x509: certificate signed by unknown authority" errorVerbose="x509: certificate signed by unknown authority\nthe supplied identity is not valid" policyName=Admins i
dentity="(mspid=Org1MSP subject=CN=Admin@org1.example.com,OU=admin,L=San Francisco,ST=California,C=US issuer=CN=ca.org1.example.com,O=org1.example.com,L=San Francisco,ST=California,C=US ser
ialnumber=334694104772860526469172045005641667995)"_

**orderer log**

```
2023-09-14T07:03:59.366276808Z 2023-09-14 07:03:59.364 UTC 0142 WARN [common.deliver] deliverBlocks -> [channel: mychannel] Client 172.25.0.5:35456 is not authorized: implicit policy[10/1588$
on failed - 0 sub-policies were satisfied, but this policy requires 1 of the 'Readers' sub-policies to be satisfied: permission denied
2023-09-14T07:03:59.366282567Z 2023-09-14 07:03:59.364 UTC 0143 INFO [comm.grpc.server] 1 -> streaming call completed grpc.service=orderer.AtomicBroadcast grpc.method=Deliver grpc.peer_addr
ess=172.25.0.5:35456 grpc.code=OK grpc.call_duration=1.3268ms
2023-09-14T07:10:05.098469213Z 2023-09-14 07:10:05.098 UTC 0144 WARN [policies] SignatureSetToValidIdentities -> invalid identity error="the supplied identity is not valid: x509: certificat
e signed by unknown authority" identity="(mspid=Org1MSP subject=CN=peer0.org1.example.com,OU=COP,L=San Francisco,ST=California,C=US issuer=CN=ca.org1.example.com,OU=COP,O=org1.example.com,L
=San Francisco,ST=California,C=US serialnumber=268337738708423250738667250199689187829)"
2023-09-14T07:10:05.098849079Z 2023-09-14 07:10:05.098 UTC 0145 WARN [policies] SignatureSetToValidIdentities -> invalid identity error="the supplied identity is not valid: x509: certificat
e signed by unknown authority" identity="(mspid=Org1MSP subject=CN=peer0.org1.example.com,OU=COP,L=San Francisco,ST=California,C=US issuer=CN=ca.org1.example.com,OU=COP,O=org1.example.com,L
=San Francisco,ST=California,C=US serialnumber=268337738708423250738667250199689187829)"
2023-09-14T07:10:05.098879539Z 2023-09-14 07:10:05.098 UTC 0146 WARN [orderer.common.msgprocessor] Apply -> SigFilter evaluation failed error="implicit policy evaluation failed - 0 sub-poli
cies were satisfied, but this policy requires 1 of the 'Readers' sub-policies to be satisfied" ConsensusState=STATE_NORMAL policyName=/Channel/Readers signingIdentity="(mspid=Org1MSP subjec
t=CN=peer0.org1.example.com,OU=COP,L=San Francisco,ST=California,C=US issuer=CN=ca.org1.example.com,OU=COP,O=org1.example.com,L=San Francisco,ST=California,C=US serialnumber=268337738708423
250738667250199689187829)"
```

### Steps to reproduce

1. Start Fabric network with Fabric v2.5.4
2. Start deployment of chaincode.
     a. Package chaincode 
     b. Install chaincode on peer
     c. Approve for org
At this step it fails

**Comment by denyeart** [comment]
It looks like the certificates are not correct in this environment.
For usage help, please use Discord chat as mentioned at:
https://hyperledger-fabric.readthedocs.io/en/latest/CONTRIBUTING.html#communications-and-getting-help
The GitHub issues are reserved for code issues in the fabric repository.
