### ISSUE TITLE
How to use fabric-sdk-go to create channels with non-system channels

### ISSUE THREAD

**Issue by shengwenbin** [hyperledger/fabric#4443]
### Current Status

Hello, I'm using fabric-sdk-go for creating channels. I created channels using the system channel method and created channels via the SaveChannel function in go-sdk. But when I upgraded to fabric 2.4, when I used the non-system channel mode, no .tx file was generated, only a .block file, and there was no function in the go-sdk to create channels through the .block file. Do you have any suggestions for this problem?

### Expected

Pass in .block, call a function, and directly generate a new channel

**Comment by bestbeforetoday** [comment]
You could try using [hyperledger/fabric-admin-sdk](https://github.com/hyperledger/fabric-admin-sdk). Just be aware that, at the time of writing, a v1.0 release has not been mode of this API so it could still evolve slightly over time.

**Comment by denyeart** [comment]
Right, fabric-admin-sdk is the strategic SDK for managing channels. I'll close this one, please open issues in https://github.com/hyperledger/fabric-admin-sdk if you face any problems.
