### ISSUE TITLE
 Failed to preProcess proposal error="error validating proposal: access denied: channel [] creator org unknown, creator is malformed"

### ISSUE THREAD

**Issue by Piyushmethi09** [hyperledger/fabric#4485]
### Description

 Failed to preProcess proposal error="error validating proposal: access denied: channel [] creator org unknown, creator is malformed"

**Comment by shafa45** [comment]
@Piyushmethi09 
Yes. I am facing the same issue. If you are able to find a solution or maybe a work around for this then please share it with me.

**Comment by denyeart** [comment]
You’ll get this error if the client’s MSP (as specified by CORE_PEER_MSPCONFIGPATH) is not an admin for the peer’s org. Make sure the client certificate was issued by the peer org’s CA.
 
The peer log should have some additional error and certificate information for troubleshooting.
