### ISSUE TITLE
Drop `purego` from the build tags as soon as we upgrade to go1.21

### ISSUE THREAD

**Issue by ale-linux** [hyperledger/fabric#4546]
### Current Status

https://github.com/hyperledger/fabric/pull/4539/files#diff-5f3a47c18e7fb89bc9d1e5fd7563ad56a440fc15565e11301646d42a8f555ec8R145 introduced the `purego` build tag to be able to build `mathlib` as a shared library (see https://github.com/Consensys/gnark-crypto/issues/468). It turns out that the issue has been fixed with go1.21 so this issue tracks the fact that we can drop `purego` as soon as we bump the Go release.

### Expected

Not to have to build with the `purego` tag (note that `generic` is still needed).

### Solution

Remove the `purego` tag from `integration/pluggable/pluggable_test.go`

**Comment by denyeart** [comment]
@ale-linux Fabric is already on Go 1.21. Do you mean 1.21.4? The plugin compiled with the new tags so we got further, but the [test still complains](https://github.com/hyperledger/fabric/actions/runs/6882114365/job/18720043049) with `plugin was built with a different version of package google.golang.org/protobuf/reflect/protoreflect`

**Comment by ale-linux** [comment]
Correct - I meant 1.21.4. (I checked [this](https://github.com/hyperledger/fabric/blob/main/go.mod#L3) to determine the go level.

I've never seen the issue with `protoreflect`, I'll check.

**Comment by denyeart** [comment]
@ale-linux I've updated Fabric to Go 1.21.4.

I re-pushed the PR with just "generic" build tag. Again the plugins compile but [test fails](https://github.com/hyperledger/fabric/actions/runs/6909334522/job/18800531810?pr=4539), this time with error:

```
Error opening plugin at path testdata/plugins/validation/plugin.so: plugin.Open("testdata/plugins/validation/plugin"): plugin was built with a different version of package github.com/kilic/bls12-381
```

**Comment by denyeart** [comment]
@ale-linux Got it working in https://github.com/hyperledger/fabric/pull/4539. I'll close this one.
