### ISSUE TITLE
root CA certificate expired

### ISSUE THREAD

**Issue by devFabric24** [hyperledger/fabric#4573]
### Description

Our CA certificate has expired and all the Hyperledger certificates signed by that CA are rejected. No renewal process for the CA is described in the Hyperledger Fabric documentation. Could you please describe which are the steps for the renewal of the CA certificate?

**Comment by denyeart** [comment]
I've added a PR to document CA cert renewals, see https://github.com/hyperledger/fabric/pull/4609 for details.

**Comment by satoshimum** [comment]
@denyeart the added description is missing command lines, would you please add further instructions?
