### ISSUE TITLE
Is there possible create cross channel transaction in atomic

### ISSUE THREAD

**Issue by weiminw** [hyperledger/fabric#4587]
### Description

1.  submit sendX(a, b) transaction in Channel 1
2. submit sendY(c, d) transaction in Channel 2
3. submit sendZ(e, f)  transaction in Channel 3

is there possible to guarantee the step1 , step 2 and step3 be either all success or all failed

**Comment by denyeart** [comment]
Sorry, no, channels each commit independently.
