### ISSUE TITLE
Flakey integration test in gateway suite

### ISSUE THREAD

**Issue by tock-ibm** [hyperledger/fabric#4589]
### Description

```
  In [It] at: /home/runner/work/fabric/fabric/integration/gateway/gateway_bft_test.go:170
------------------------------

Ran 23 of 23 Specs in 806.827 seconds
FAIL! -- 22 Passed | 1 Failed | 0 Pending | 0 Skipped
```

https://github.com/hyperledger/fabric/actions/runs/7399063373/job/20141197747?pr=4571

### Steps to reproduce

integration tests are failing from time to time because of the gateway suite

**Comment by pfi79** [comment]
@tock-ibm can be closed as corrected.

**Comment by tock-ibm** [comment]
@pfi79 unfortunately, this flake is still alive.... 

https://github.com/hyperledger/fabric/actions/runs/7573138239/job/20624709380?pr=4612

**Comment by pfi79** [comment]
> unfortunately, this flake is still alive....

Yes, I agree, unfortunately.

After restarting an orderer other orderers do not see it because of backoff

Here's a [fix](https://github.com/hyperledger/fabric/pull/4610) for that. Please consider it.

**Comment by tock-ibm** [comment]
Thanks @pfi79
