### ISSUE TITLE
how to decode the result data from: peer chaincode query -C mychannel -n qscc -c '{"Args":["GetTransactionByID","mychannel","4c11b1e9fe432f17f9a3dd8c73410fd0151125995c7dca95c9186c61fc34c99a"]}' > t1.tx

### ISSUE THREAD

**Issue by hextzd** [hyperledger/fabric#4593]
### Description

I try use configtxlator tool with type "peer.ProcessedTransaction", but just got an error blow:
configtxlator proto_decode --input t1.tx --type peer.ProcessedTransaction --output t1.json

configtxlator: error: Error decoding: message of type %!s(<nil>) unknown

what should I do?

another error ocurred, with GetChainInfo:
peer chaincode query -C mychannel -n qscc -c '{"Args":["GetChainInfo","mychannel"]}' > cinfo.tx
configtxlator proto_decode --input cinfo.tx --type  common.BlockchainInfo
configtxlator: error: Error decoding: error unmarshalling: proto: cannot parse invalid wire-format data

someone can help me?

**Comment by denyeart** [comment]
For help please use the community resources mentioned at:
https://hyperledger-fabric.readthedocs.io/en/latest/CONTRIBUTING.html#communications-and-getting-help

Please reserve github issues for actual code bugs or improvements.
