### ISSUE TITLE
Fix documentation errors and warnings from Sphinx

### ISSUE THREAD

**Issue by denyeart** [hyperledger/fabric#4617]
### Current Status

```
# python -m sphinx -T -E -b html -d _build/doctrees -D language=en . ~/html
Running Sphinx v7.2.6
myst v2.0.0: MdParserConfig(commonmark_only=False, gfm_only=False, enable_extensions=set(), disable_syntax=[], all_links_external=False, url_schemes=('http', 'https', 'mailto', 'ftp'), ref_domains=None, fence_as_directive=set(), number_code_blocks=[], title_to_header=False, heading_anchors=0, heading_slug_func=None, html_meta={}, footnote_transition=True, words_per_minute=200, substitutions={}, linkify_fuzzy_links=True, dmath_allow_labels=True, dmath_allow_space=True, dmath_allow_digits=True, dmath_double_inline=False, update_mathjax=True, mathjax_classes='tex2jax_process|mathjax_process|math|output_area', enable_checkboxes=False, suppress_warnings=[], highlight_code_blocks=True)
building [mo]: targets for 0 po files that are out of date
writing output... 
building [html]: targets for 130 source files that are out of date
updating environment: [new config] 130 added, 0 changed, 0 removed
reading sources... [100%] write_first_app
/root/docs/source/channel_update_tutorial.rst:196: ERROR: Error in "code" directive:
maximum 1 argument(s) allowed, 3 supplied.

.. code:: bash
  cd ..
/root/docs/source/channel_update_tutorial.rst:253: ERROR: Error in "code" directive:
maximum 1 argument(s) allowed, 3 supplied.

.. code:: bash
   cd channel-artifacts
/root/docs/source/channel_update_tutorial.rst:356: ERROR: Error in "code" directive:
maximum 1 argument(s) allowed, 3 supplied.

.. code:: bash
   cd ..
/root/docs/source/channel_update_tutorial.rst:687: ERROR: Error in "code" directive:
maximum 1 argument(s) allowed, 3 supplied.

.. code:: bash
   cd channel-artifacts
/root/docs/source/channel_update_tutorial.rst:760: ERROR: Error in "code" directive:
maximum 1 argument(s) allowed, 3 supplied.

.. code:: bash
   cd ..
/root/docs/source/deployment_guide_overview.rst:2: WARNING: Duplicate explicit target name: "in the sampleconfig directory of hyperledger fabric".
/root/docs/source/peers/peers.md:30: WARNING: Non-consecutive header level increase; H1 to H3 [myst.header]
/root/docs/source/updating_capabilities.md:52: WARNING: Non-consecutive header level increase; H2 to H4 [myst.header]
looking for now-outdated files... none found
pickling environment... done
checking consistency... /root/docs/source/build_network.rst: WARNING: document isn't included in any toctree
/root/docs/source/developapps/apis.md: WARNING: document isn't included in any toctree
/root/docs/source/github/github.rst: WARNING: document isn't included in any toctree
/root/docs/source/ledger.rst: WARNING: document isn't included in any toctree
/root/docs/source/msp-identity-validity-rules.rst: WARNING: document isn't included in any toctree
/root/docs/source/policies.rst: WARNING: document isn't included in any toctree
/root/docs/source/tutorial/installxcode.md: WARNING: document isn't included in any toctree
```

### Goal

Fix the Sphinx warnings in the Fabric docs.

### Solution

Fix the Sphinx warnings in the Fabric docs.

**Comment by solo-daemon** [comment]
HI @tock-ibm i would like to work on this issue. Can you please assign this to me.

**Comment by Ming19880501** [comment]
> ### Current Status
> 
> ```
> # python -m sphinx -T -E -b html -d _build/doctrees -D language=en . ~/html
> Running Sphinx v7.2.6
> myst v2.0.0: MdParserConfig(commonmark_only=False, gfm_only=False, enable_extensions=set(), disable_syntax=[], all_links_external=False, url_schemes=('http', 'https', 'mailto', 'ftp'), ref_domains=None, fence_as_directive=set(), number_code_blocks=[], title_to_header=False, heading_anchors=0, heading_slug_func=None, html_meta={}, footnote_transition=True, words_per_minute=200, substitutions={}, linkify_fuzzy_links=True, dmath_allow_labels=True, dmath_allow_space=True, dmath_allow_digits=True, dmath_double_inline=False, update_mathjax=True, mathjax_classes='tex2jax_process|mathjax_process|math|output_area', enable_checkboxes=False, suppress_warnings=[], highlight_code_blocks=True)
> building [mo]: targets for 0 po files that are out of date
> writing output... 
> building [html]: targets for 130 source files that are out of date
> updating environment: [new config] 130 added, 0 changed, 0 removed
> reading sources... [100%] write_first_app
> /root/docs/source/channel_update_tutorial.rst:196: ERROR: Error in "code" directive:
> maximum 1 argument(s) allowed, 3 supplied.
> 
> .. code:: bash
>   cd ..
> /root/docs/source/channel_update_tutorial.rst:253: ERROR: Error in "code" directive:
> maximum 1 argument(s) allowed, 3 supplied.
> 
> .. code:: bash
>    cd channel-artifacts
> /root/docs/source/channel_update_tutorial.rst:356: ERROR: Error in "code" directive:
> maximum 1 argument(s) allowed, 3 supplied.
> 
> .. code:: bash
>    cd ..
> /root/docs/source/channel_update_tutorial.rst:687: ERROR: Error in "code" directive:
> maximum 1 argument(s) allowed, 3 supplied.
> 
> .. code:: bash
>    cd channel-artifacts
> /root/docs/source/channel_update_tutorial.rst:760: ERROR: Error in "code" directive:
> maximum 1 argument(s) allowed, 3 supplied.
> 
> .. code:: bash
>    cd ..
> /root/docs/source/deployment_guide_overview.rst:2: WARNING: Duplicate explicit target name: "in the sampleconfig directory of hyperledger fabric".
> /root/docs/source/peers/peers.md:30: WARNING: Non-consecutive header level increase; H1 to H3 [myst.header]
> /root/docs/source/updating_capabilities.md:52: WARNING: Non-consecutive header level increase; H2 to H4 [myst.header]
> looking for now-outdated files... none found
> pickling environment... done
> checking consistency... /root/docs/source/build_network.rst: WARNING: document isn't included in any toctree
> /root/docs/source/developapps/apis.md: WARNING: document isn't included in any toctree
> /root/docs/source/github/github.rst: WARNING: document isn't included in any toctree
> /root/docs/source/ledger.rst: WARNING: document isn't included in any toctree
> /root/docs/source/msp-identity-validity-rules.rst: WARNING: document isn't included in any toctree
> /root/docs/source/policies.rst: WARNING: document isn't included in any toctree
> /root/docs/source/tutorial/installxcode.md: WARNING: document isn't included in any toctree
> ```
> 
> ### Goal
> 
> Fix the Sphinx warnings in the Fabric docs.
> 
> ### Solution
> 
> Fix the Sphinx warnings in the Fabric docs.

**Comment by Ming19880501** [comment]
> ### Current Status
> 
> ``
> # python -m sphinx -T -E -b html -d _build/doctrees -D language=en . ~/html
> Running Sphinx v7.2.6
> myst v2.0.0: MdParserConfig(commonmark_only=False, gfm_only=False, enable_extensions=set(), disable_syntax=[], all_links_external=False, url_schemes=('http', 'https', 'mailto', 'ftp'), ref_domains=None, fence_as_directive=set(), number_code_blocks=[], title_to_header=False, heading_anchors=0, heading_slug_func=None, html_meta={}, footnote_transition=True, words_per_minute=200, substitutions={}, linkify_fuzzy_links=True, dmath_allow_labels=True, dmath_allow_space=True, dmath_allow_digits=True, dmath_double_inline=False, update_mathjax=True, mathjax_classes='tex2jax_process|mathjax_process|math|output_area', enable_checkboxes=False, suppress_warnings=[], highlight_code_blocks=True)
> building [mo]: targets for 0 po files that are out of date
> writing output... 
> building [html]: targets for 130 source files that are out of date
> updating environment: [new config] 130 added, 0 changed, 0 removed
> reading sources... [100%] write_first_app
> /root/docs/source/channel_update_tutorial.rst:196: ERROR: Error in "code" directive:
> maximum 1 argument(s) allowed, 3 supplied.
> 
> .. code:: bash
>   cd ..
> /root/docs/source/channel_update_tutorial.rst:253: ERROR: Error in "code" directive:
> maximum 1 argument(s) allowed, 3 supplied.
> 
> .. code:: bash
>    cd channel artifacts
> /root/docs/source/channel_update_tutorial.rst:356: ERROR: Error in "code" directive:
> maximum 1 argument(s) allowed, 3 supplied.
> 
> .. code:: bash
>    cd ..
> /root/docs/source/channel_update_tutorial.rst:687: ERROR: Error in "code" directive:
> maximum 1 argument(s) allowed, 3 supplied.
> 
> .. code:: bash
>    cd channel artifacts
> /root/docs/source/channel_update_tutorial.rst:760: ERROR: Error in "code" directive:
> maximum 1 argument(s) allowed, 3 supplied.
> 
> .. code:: bash
>    cd ..
> /root/docs/source/deployment_guide_overview.rst:2: WARNING: Duplicate explicit target name: "in the sampleconfig directory of hyperledger fabric".
> /root/docs/source/peers/peers.md:30: WARNING: Non-consecutive header level increase; H1 to H3 [myst.header]
> /root/docs/source/updating_capabilities.md:52: WARNING: Non-consecutive header level increase; H2 to H4 [myst.header]
> Looking for now-outdated files... none found
> pickling environment... done
> checking consistency... /root/docs/source/build_network.rst: WARNING: The document isn't included in any toctree
> /root/docs/source/developapps/apis.md: WARNING: The document isn't included in any toctree
> /root/docs/source/github/github.rst: WARNING: The document isn't included in any toctree
> /root/docs/source/ledger.rst: WARNING: The document isn't included in any toctree
> /root/docs/source/msp-identity-validity-rules.rst: WARNING: The document isn't included in any toctree
> /root/docs/source/policies.rst: WARNING: The document isn't included in any toctree
> /root/docs/source/tutorial/installxcode.md: WARNING: The document isn't included in any toctree
> ``
> 
> ### Goal
> 
> Fix the Sphinx warnings in the fabric docs.
> 
> ### Solution
> 
> Fix the Sphinx warnings in the fabric docs.

-

**Comment by tommyhuanghhh** [comment]
@denyeart by fixing the Sphinx warning, do you mean these in the log:

- /root/docs/source/build_network.rst: WARNING: document isn't included in any toctree
- /root/docs/source/developapps/apis.md: WARNING: document isn't included in any toctree
- /root/docs/source/github/github.rst: WARNING: document isn't included in any toctree
- /root/docs/source/ledger.rst: WARNING: document isn't included in any toctree
- /root/docs/source/msp-identity-validity-rules.rst: WARNING: document isn't included in any toctree
- /root/docs/source/policies.rst: WARNING: document isn't included in any toctree
- /root/docs/source/tutorial/installxcode.md: WARNING: document isn't included in any toctree

in that case, do you expect the contributor to remove these warning, or find the root cause of it? Actually, any suggestion that could help me get started is welcome.

**Comment by satota2** [comment]
@thuang86714 
The root cause of these warnings seems to be that each file is not referenced from any page.

One solution is to add links to each file from another file in the documents.

Alternatively, as a shortest solution, the following Q&A suggests that adding orhan to the beginning of each file that has a warning will eliminate the warning.
https://stackoverflow.com/questions/15249340/warning-document-isnt-included-in-any-toctree-for-included-file

**Comment by denyeart** [comment]
@thuang86714 The intent is to fix each of the errors and warnings, not just the ones you highlighted.

For the documents not included, these probably require a judgement call from an experienced project member, of whether the document is important enough to appear in the table of contents, or whether to suppress the warning as @satota2 indicates.

The other errors and warnings are good candidates for a new contributors. They require troubleshooting first. Once the troubleshooting is complete, I expect the fix will become obvious and the project would welcome pull requests to fix.

**Comment by thuang86714** [comment]
@denyeart can you share how I could reproduce the logs you provided? I've installed python and sphinx, and when I ran the your command, the configuration error came up saying that config directory doesn't contain a conf.py file. 
(FYI, I didn't do Download Fabric samples, Docker images, and binaries. Only cloned the repo)
`C:\Users\{my-username}\OneDrive\DeskTop\Projects\hyperLedgerFabric> python -m sphinx -T -E -b html -d _build/doctrees -D language=en . ~/html
Running Sphinx v7.2.5

Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\sphinx\cmd\build.py", line 293, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\sphinx\application.py", line 211, in __init__
    self.config = Config.read(self.confdir, confoverrides or {}, self.tags)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\sphinx\config.py", line 179, in read
    raise ConfigError(__("config directory doesn't contain a conf.py file (%s)") %
sphinx.errors.ConfigError: config directory doesn't contain a conf.py file (C:\Users\{my-username}\OneDrive\DeskTop\Projects\hyperLedgerFabric)

Configuration error:
config directory doesn't contain a conf.py file (C:\Users\{my-username}\OneDrive\DeskTop\Projects\hyperLedgerFabric)`

**Comment by solo-daemon** [comment]
@denyeart https://github.com/hyperledger/fabric/pull/4786 should fix the warning except for the extra document one. Should I start a discussion related to this on discord?
