### ISSUE TITLE
panic: TLS is required for running ordering nodes of cluster type (Reopen)

### ISSUE THREAD

**Issue by razorbohan** [hyperledger/fabric#4624]
### Description

Reopening the issue #3886

Running chaincode in development mode

Start the orderer

https://hyperledger-fabric.readthedocs.io/en/latest/peer-chaincode-devmode.html#start-the-orderer

ORDERER_GENERAL_GENESISPROFILE=SampleDevModeSolo orderer

I am getting below error

2022-12-30 01:43:46.544 UTC 0007 PANI [orderer.common.server] reuseListener -> TLS is required for running ordering nodes of cluster type.
panic: TLS is required for running ordering nodes of cluster type.

### Steps to reproduce

Follow the instruction:

https://hyperledger-fabric.readthedocs.io/en/latest/peer-chaincode-devmode.html#start-the-orderer

Until the step of starting orderer:

ORDERER_GENERAL_GENESISPROFILE=SampleDevModeSolo orderer

**Comment by yacovm** [comment]
This is not a bug. The latest version only supports Raft or BFT, you cannot run a solo orderer anymore and without TLS.

**Comment by cy414** [comment]
> This is not a bug. The latest version only supports Raft or BFT, you cannot run a solo orderer anymore and without TLS.

Maybe the [bug](https://hyperledger-fabric.readthedocs.io/en/latest/peer-chaincode-devmode.html#start-the-orderer) in doc and need some modifications for noob like me?
