### ISSUE TITLE
fabric/docs/source/couchdb_tutorial.rst

### ISSUE THREAD

**Issue by smng-acl** [hyperledger/fabric#4677]
Before querying the database, 2 export missing:
export PATH=${PWD}/../bin:$PATH
export FABRIC_CFG_PATH=${PWD}/../config

**Comment by satota2** [comment]
@smng-acl 
Thank you for your reporting. I created and submitted a PR to solve this issue.
https://github.com/hyperledger/fabric/pull/4690
