### ISSUE TITLE
External Chaincode NOT WORKING on v2.5.x specifically and working fine for v2.4.x and earlier versions

### ISSUE THREAD

**Issue by TahaYousufAli52** [hyperledger/fabric#4688]
### Description

**We have encountered issues with External Chaincode implementation after upgrading from Hyperledger Fabric v2.0.1 to v2.5.5**. Previously, our external chaincode implementation functioned without issues on v2.0.1; however, after the upgrade, we encountered failures during the installation process of external chaincode. Extensive debugging efforts led us to manipulate the code of the default External Chaincode Sample-Builders and somehow we were able to commit the External Chaincode but invocation still failed, leading to a deadlock in our progress.

****To validate whether the issue stemmed from our environment or the upgrade itself, we deployed a test network running various versions (v2.0.1, v2.4.1, v2.5.5).** Our observations revealed that external chaincode worked seamlessly on versions 2.0.1 and 2.4.1 but failed on 2.5.5, with an error message indicating an **_"unknown chaincodeType: EXTERNAL"_** and further, an **_"Illegal option -o"_** in the peer logs. This discrepancy prompted us to delve deeper into potential environmental changes.**

### Attachments:
Screenshots showcasing successful External Chaincode installations on versions 2.0.1 and 2.4.1, contrasted with failure on 2.5.5.

**v2.0.1**
![image](https://github.com/hyperledger/fabric/assets/117735994/b596478b-64eb-45a0-bc1e-5a73d594f231)
**v2.4.1**
![image](https://github.com/hyperledger/fabric/assets/117735994/578935e0-2e96-44b4-9848-96ba42901bf2)
**v2.5.5**
![image](https://github.com/hyperledger/fabric/assets/117735994/3cdf2cd2-8d38-4df7-aff8-a331b63b3904)
**Peer Logs - **v2.5.5****
![image](https://github.com/hyperledger/fabric/assets/117735994/d6041041-30a1-4813-b089-aac137529b5d)

**CORE.YAML**
![image](https://github.com/hyperledger/fabric/assets/87118953/a42fd9a6-4d99-4c17-9194-4d2828ea84f2)

### Steps to Reproduce:

- Deploy Hyperledger Fabric v2.5.5.
- Implement External Chaincode by referring to above **_core.yaml_**.
- Attempt Installation of external chaincode.
- Observe the failure with the error _**"unknown chaincodeType: EXTERNAL"**_ and **_"Illegal option -o"_** in the peer logs.

### **Expected Behavior:**
External Chaincode implementation should execute without errors or discrepancies, as observed in previous versions (v2.0.1, v2.4.1).

**We kindly request your prompt assistance in investigating and resolving this issue to ensure the seamless operation of external chaincode implementations in Hyperledger Fabric v2.5.x release. Your support in rectifying this matter would be greatly appreciated.**

**Comment by satota2** [comment]
@TahaYousufAli52 
This issue seems to have been resolved on the mailing list exchange, so please close this Issue.
https://lists.hyperledger.org/g/fabric/message/12167
