### ISSUE TITLE
Add org off-boarding to Operation Guides

### ISSUE THREAD

**Issue by takakir** [hyperledger/fabric#4730]
### Current Status

Org off-boarding procedures not defined in Hyperledger Fabric Docs

### Expected

Org off-boarding procedures defined in Hyperledger Fabric Docs.

### Solution

Add org off-boarding procedures for networks with PDC (which adds another layer of complexity) to Operation Guides.

Currently testing org off-boarding procedures w/ @kaiknight and his team which we defined with support from @denyeart & @satota2. 

Happy to draft & submit pull request if appropriate for Hyperledger Fabric Docs.

### Please let us know if you plan to work on this.

Yes!

**Comment by satota2** [comment]
@takakir 
Thank you for your proposal.
I beleave that the document you're proposing would be highly beneficial for the community.
We would be delighted if you could draft the document and submit a pull request.
Looking forward to your submission.

**Comment by takakir** [comment]
@kaiknight let's discuss this Monday.

**Comment by takakir** [comment]
@satota2 Can you assign this issue to my colleague @kaiknight ? 
I have given him the heads up on this and will draft operation guide end of next week/following week. (assuming there are no surprise in our testing..)

**Comment by satota2** [comment]
@takakir  @kaiknight
I attempted to assign @kaiknight to the issue, but it appears that users who have not yet taken any actions within the repository cannot be found in the search or assigned. For instance, if @kaiknight could make a post in this chat, it would then be possible to assign them.

However, from the conversation in this issue, it is clear that you two are handling this matter. So, it should be fine to proceed as is without making the assignment.

**Comment by kaiknight** [comment]
@satota2 Thank you for your approval. We're working on the verification of the steps and would start to draft operation guide once verification is successful.

**Comment by takakir** [comment]
@satota2 we've completed our test and the procedure looks good.
@kaiknight will be drafting the doc. 
in the process, we've also found part in HLF docs that needs an update. (peer deployment with latest configuration block)
Will also be proposing that fix in different issue as well.

**Comment by kaiknight** [comment]
@satota2 @takakir merge request is created in #4760. The doc is built for test in https://fabric-remove-org.readthedocs.io/en/latest/channel_remove_org.html

**Comment by takakir** [comment]
@satota2 appreciate any/all comments.

**Comment by satota2** [comment]
@takakir @kaiknight 
Thank you for submitting the PR, and I apologize for the delay in reviewing it. I am currently in the process of reviewing it. At first glance, it looks good. I'm in the midst of verifying the details by testing the documentation steps in my local environment, so I would appreciate a bit more patience.

**Comment by takakir** [comment]
@satota2 thanks. I realize the community is busy around v3 so no worries.

**Comment by satota2** [comment]
@kaiknight @takakir 
The PR has been merged, so I will close this issue.
Thank you for your wonderful contribution!

**Comment by takakir** [comment]
@kaiknight @satota2 we should also add link in operation guide
[https://hyperledger-fabric.readthedocs.io/en/release-2.5/ops_guide.html](https://hyperledger-fabric.readthedocs.io/en/release-2.5/ops_guide.html)

<img width="749" alt="image" src="https://github.com/hyperledger/fabric/assets/17231707/c4aa06d5-f517-4313-8f33-dd17813cbb9d">

**Comment by kaiknight** [comment]
@takakir The guide is added in tutorial section.
https://hyperledger-fabric.readthedocs.io/en/latest/tutorials.html
![image](https://github.com/hyperledger/fabric/assets/755951/bc1d9975-3add-468c-8743-ded35affe1c8)
![image](https://github.com/hyperledger/fabric/assets/755951/149e76ed-587c-4561-a389-9bbaf338366a)
