### ISSUE TITLE
无法创建通道

### ISSUE THREAD

**Issue by jokermoon** [hyperledger/fabric#4755]
### Description

当我进入cli 用生成的通道文件创建通道时会报以下错误
<img width="862" alt="Snipaste_2024-03-18_10-10-26" src="https://github.com/hyperledger/fabric/assets/119102908/691ed98e-4a23-45ca-b390-808ec0dd7f56">

**Comment by SamYuan1990** [comment]
please provide more specific log in English.
it's better for you to provide orderer side log with your peer command, as the error response is from orderer server.

**Comment by Pheglovog** [comment]
Are you trying tutorial's  test-network?
I think you need to try this steps according to the tutorial seriously
[Here](https://hyperledger-fabric.readthedocs.io/en/release-2.5/test_network.html#) is what you need to follow

**Comment by denyeart** [comment]
Did not hear back from originator, closing.
