### ISSUE TITLE
Remove global level endpoints from the channel config

### ISSUE THREAD

**Issue by MayRosenbaum** [hyperledger/fabric#4763]
### Current Status

The channel config specifies both [global-level endpoints](https://github.com/hyperledger/fabric/blob/main/common/channelconfig/util.go#L101-L105) and [per-organization endpoints](https://github.com/hyperledger/fabric/blob/main/integration/nwo/fabricconfig/configtx.go#L22-L29). 

### Expected

In V3.0 we should use the per-organization endpoints and eliminate the option to specify global-level endpoints.
This means that the configtx validation unit will check if any global-level endpoints have been configured and refuse and return a suitable error if so.

### Please let us know if you plan to work on this.

Yes!

**Comment by tock-ibm** [comment]
Finished with #4879
