### ISSUE TITLE
Is it possible to create different channels using different consensus algorithms in one system and have access to each other?

### ISSUE THREAD

**Issue by MingYueChunQiu** [hyperledger/fabric#4766]
### Current Status

Can I create multiple channels in a fabric-based system, with different channels configured with different consensus algorithms, and can different channels access data in each other's channels?

### Expected

Implement a system in which different channels can be created, different channels can be configured with different consensus algorithms, and channels can access each other's data in each other's channels。

**Comment by yacovm** [comment]
Yes you can run an orderer with a chain running BFT and a different chain running Raft. 

I've seen it happen live in the demo here: https://www.youtube.com/watch?v=4taLwa_pl9U
