### ISSUE TITLE
Error: query failed with status: 404 - namespace basic is not defined

### ISSUE THREAD

**Issue by Tbx998** [hyperledger/fabric#4776]
When I try this command,it occurred some errors.
./network.sh deployCC -ccn basic -ccp ../asset-transfer-basic/chaincode-java -ccl java
![QQ截图20240331164558](https://github.com/hyperledger/fabric/assets/56324247/e50890b4-c427-44bb-b896-f29a9bbff353)
after ,docker 
![QQ截图20240331164705](https://github.com/hyperledger/fabric/assets/56324247/6d618643-b30f-4591-8174-53b008b244d1)
Who can help me to solve those problems,
Thanks!

**Comment by eferos93** [comment]
Hello, I am having the same issue, did you find a solution for this?
Thanks.

**Comment by denyeart** [comment]
It looks like peer0.org1.example.com docker container (which uses port 7051) is not up.

Try `docker ps -a` to see exited containers. Then look at its logs with `docker logs <container_id>` to see why it may have gone down.

Note, please use Discord chat for help requests - https://hyperledger-fabric.readthedocs.io/en/latest/CONTRIBUTING.html#communications-and-getting-help.
We reserve Github Issues for code enhancements and bugs, so I'll close this one.
