### ISSUE TITLE
Update documentation: Variable name in Tutorials/Create a Channel

### ISSUE THREAD

**Issue by solo-daemon** [hyperledger/fabric#4779]
### Description

Varible name of TwoOrgsApplicationGenesis has been updated to ChannelUsingRaft in code

**Comment by satota2** [comment]
@solo-daemon
Thank you for submitting your PR. I have merged the PR you submitted.
At the same time, I found another PR addressing the same issue.
https://github.com/hyperledger/fabric/pull/4528

This PR seems to include a few addtional fixes aside from your contributions, but it has been stagnating for a long time while waiting for additional updates from the original submitter (I suspect the original submitter may have lost interest in this PR).
So, if possible, could you create and submit a separate PR that picks up on the differences your first PR(#4781) and this one(#4528)?
