### ISSUE TITLE
what is the recommended docker desktop version?

### ISSUE THREAD

**Issue by hasu234** [hyperledger/fabric#4833]
I was reviewing the documentation and saw this in the Run Fabric section. 

Note: The test network has been successfully verified with Docker Desktop version 2.5.0.1 and is the recommended version at this time. Higher versions may not work.

**Comment by denyeart** [comment]
There have been no problems reported with latest versions of Docker Desktop.
I've opened PR https://github.com/hyperledger/fabric/pull/4839 to remove the guidance around v2.5.0.1.
