### ISSUE TITLE
Yesterday I can run it,but today can't

### ISSUE THREAD

**Issue by MoLiShang** [hyperledger/fabric#4836]
### Description

When I run the configtxgen command,it report the bug as below,and I'm sure I don't change the file,the FABRIC_CFG_PATH is also can run.
![ECY4BWHA NWTA(H7W H2C)A](https://github.com/hyperledger/fabric/assets/37530126/e8bb6ace-682e-43eb-8a73-defd4af7ee30)
![image](https://github.com/hyperledger/fabric/assets/37530126/7c289e92-3a40-4020-a254-d57ee725cdc6)

**Comment by denyeart** [comment]
The error says there are no policies defined.
I can reproduce the problem only if I remove the policies from the configtxgen.yaml. Please check for a valid configtxgen.yaml.
