### ISSUE TITLE
Docs is using Obsolete version reference release-1.4 to hyperledger-fabric-ca

### ISSUE THREAD

**Issue by lir2002** [hyperledger/fabric#4854]
### Description

The maintaining team may think **release-1.4** is the LTS version of **hyperledger-fabric-ca docs**. However, the version hasn't been updated for 4 years and the **hyperledger-fabric-ca** team only issue the successor version 1.5 to **latest**. 

> ![image](https://github.com/hyperledger/fabric/assets/11921037/0c5afa3d-eb63-48c7-9719-e7450219ef1d)

**latest** and **release-1.4** are not equal, so don't confuse them.  The **hyperledger-fabric-ca** team do not abide by the convension as here we do

> ![image](https://github.com/hyperledger/fabric/assets/11921037/6fd487d0-8c2d-437a-bd1b-6883d2282c37)

If you are surfing in **hyperledger-fabric-ca release-1.4 docs**, you can find many issue within the document. For example,

> ![image](https://github.com/hyperledger/fabric/assets/11921037/61ea71c2-461b-48db-a487-e6e65d485ba8)

### Steps to reproduce

1. Open https://hyperledger-fabric-ca.readthedocs.io/en/latest/  and you can choose versions in the left-bottom.
2. Navigate to **release-1.4** and compare with **latest** version.
3. Click **Edit in Github** in the right-top corner of both **release-1.4** and **latest** version, and you will be brought to the source code of the docs.

**Comment by Priyansurout** [comment]
I checked the image directory, and there is no file named "network_topology.png". Is there an alternative image or diagram that can replace the missing one?

**Comment by lir2002** [comment]
> I checked the image directory, and there is no file named "network_topology.png". Is there an alternative image or diagram that can replace the missing one?

I don't think the team would like to maintain the "1.4" version. In the latest version the image is present well. Therefore my suggest is, just repeat it, to replace the reference to version 1.4 to latest, and I implemented it in #4855

**Comment by Priyansurout** [comment]
ok

**Comment by denyeart** [comment]
Thank you, since #4855 is merged I'll close this issue.
