### ISSUE TITLE
when reboot the Fabric system, one peer got error " getLocalAddress -> local IP address not auto-detectable: Error: route ip+net: netlinkrib: permission denied".

### ISSUE THREAD

**Issue by mabing993** [hyperledger/fabric#4897]
### Description

when reboot the Fabric system, one peer got error "Error: route ip+net: netlinkrib: permission denied", looks like ubuntu's network, but other peer is ok, and the configure of Fabric system is not changed since last success reboot. 
Compare with other peer, successful reboot should like this. Waiting for response and thanks.

![image](https://github.com/hyperledger/fabric/assets/16176462/29175837-c9d3-4604-8bd4-c37817ceedeb)

ERRO [peer] getLocalAddress -> local IP address not auto-detectable: route ip+net: netlinkrib: permission denied

![image](https://github.com/hyperledger/fabric/assets/16176462/91f5fd31-74c6-4ddb-9643-1acea0d817eb)

**Comment by denyeart** [comment]
It looks like the problem is not in Fabric code but between Go and the operating system:
https://github.com/golang/go/blob/master/src/net/interface.go#L124-L135

**Comment by mabing993** [comment]
It's useful, upgrade the kernel from 5.15 to 5.17, problem solved, maybe something went wrong.

Thanks.

![QQ截图20240621115847](https://github.com/hyperledger/fabric/assets/16176462/46849e4b-d4b7-44ea-a698-70cc599ca928)
