### ISSUE TITLE
Licenses need fixed.

### ISSUE THREAD

**Issue by ryjones** [hyperledger/fabric#4945]
### Description

[The latest license scan shows several files out of compliance.](https://lfscanning.org/reports/hyperledger/fabric-2024-07-24-3727ca4b-7755-42a6-92e1-541bc27bf1b9.html)

### Steps to reproduce

Finding #1
Priority: High
These files are under the MPL-2.0 license, a weak copyleft license, which may be incompatible with your project license. I recommend that you remove these files, and if they can't be removed you must be sure that they are not combined or integrated with any other project code in your repo.

fabric-2024-07-24.zip/fabric/vendor/github.com/hashicorp/hcl/LICENSE

**Comment by ryjones** [comment]
[see also](https://github.com/hyperledger/fabric-ca/issues/429)

[see also](https://github.com/hyperledger/fabric-lib-go/issues/35)

**Comment by yacovm** [comment]
[Viper](https://github.com/spf13/viper) uses [hcl](https://github.com/hashicorp/hcl):

```
vendor/github.com/spf13/viper/viper.go:	"github.com/hashicorp/hcl"
vendor/github.com/spf13/viper/viper.go:	"github.com/hashicorp/hcl/hcl/printer"
```
But recently they [moved away](https://github.com/spf13/viper/commit/ee6cffa48d1a585f4feeb1ffd42a138efd2866fd) from it.

All that is needed is to upgrade the viper version, I guess.

**Comment by yacovm** [comment]
@pfi79 do you want to do this?
