### ISSUE TITLE
When I tried to invoke a chaincode in the hyperledger fabric peer cli, I got Argument list too long error

### ISSUE THREAD

**Issue by ManjuVenkatachalam** [hyperledger/fabric#4952]
### Description

I have deployed a go chaincode called CalculateCC which has a calculation function. I used shim package. The calculation function gets the arguments in array of string "[]string". When I try to call the calculation function by passing the args [] string (the total length is 209477, i got the following error, bash: /usr/local/bin/peer: Argument list too long.

Note: I cannot breakdown the argument. Since I am doing all the calculation. so I need all the values.

### Steps to reproduce

pass the bigger length of arguments as a input.

**Comment by bestbeforetoday** [comment]
This seems to be an issue with your bash command-line, not a bug with Fabric itself or any related Fabric components. See if this StackOverflow answer helps:

https://stackoverflow.com/a/78898942/3680198
