### ISSUE TITLE
Missing argument in help information for command "peer lifecycle chaincode install"

### ISSUE THREAD

**Issue by jmmunoz-kolokium** [hyperledger/fabric#4976]
https://github.com/hyperledger/fabric/blame/0afafb845746653c19c9e815060998c418cad436/docs/source/commands/peerlifecycle.md#L119

In my opinion, the help information for this command is missing the package file parameter which should come after the word "install".

**Comment by satota2** [comment]
@jmmunoz-kolokium 
Thank you for the report. I agree with your observation that the parameter is missing and should be added. The command should be updated as follows:

`peer lifecycle chaincode install [packageFiles] [flags]`

Would you be interested in creating a PR to fix this, or was your intention to simply report the bug?
If you'd like to handle the PR, your contribution would be very welcome. If it's the latter, I can go ahead and create a PR for this.

**Comment by jmmunoz-kolokium** [comment]
@satota2 , Thank you for your reply.

Since this is my first contribution, I would be interested on handling this PR so I can see the full process.

I will create the PR as soon as possible, after reading the contribution guide.

Regards

**Comment by satota2** [comment]
@jmmunoz-kolokium 
Thank you for your contribution! I look forward to seeing your PR.
If you have any questions along the way, feel free to ask.

**Comment by jmmunoz-kolokium** [comment]
I have just created the pull request (my first one!). I hope it sticks to the project guidelines.

https://github.com/hyperledger/fabric/pull/4989
