### ISSUE TITLE
Block stream should be closed after used.

### ISSUE THREAD

**Issue by datbeohbbh** [hyperledger/fabric#4992]
### Current Status

https://github.com/hyperledger/fabric/blob/94590aa4332b20350e8aee5572a8cfd29164221c/common/ledger/blkstorage/blockfile_mgr.go#L425-L428

A block stream is opened to sync block index. After used, we should close that block stream.

### Expected

The block stream `stream` is closed after used.

### Solution

simply add `defer stream.close()`.
```go
var stream *blockStream
if stream, err = newBlockStream(mgr.rootDir, startFileNum, int64(startOffset), endFileNum); err != nil {
	return err
}
defer stream.close() // close stream
```

### Please let us know if you plan to work on this.

Maybe.

**Comment by Sayalikukkar** [comment]
Hi @datbeohbbh,

I am interested to work on this issue. can i start working on this?

Thank you

**Comment by datbeohbbh** [comment]
> Hi @datbeohbbh,
> 
> I am interested to work on this issue. can i start working on this?
> 
> Thank you
> 

@Sayalikukkar 
Hi! Sure, you can.
