### ISSUE TITLE
FABRIC_*_OPERATIONS_LISTENADDRESS Environment Variable Not Overriding Config File Setting in Fabric-CA Server, Peer or Orderer

### ISSUE THREAD

**Issue by Jenziner** [hyperledger/fabric#5020]
### Description

Description: When setting up a Fabric-CA server within a Docker container, it appears that the environment variable FABRIC_CA_OPERATIONS_LISTENADDRESS does not override the corresponding setting in the fabric-ca-server-config.yaml file.

In my Docker configuration, I have explicitly set FABRIC_CA_OPERATIONS_LISTENADDRESS=0.0.0.0:7049, expecting the server to bind to this address and port. However, despite this environment variable being set, the server instead defaults to using the listen address defined within the fabric-ca-server-config.yaml file, resulting in an unexpected binding to 127.0.0.1:9443. This behavior contradicts the expected precedence of configuration inputs as stated in the documentation, which lists environment variables as having a higher priority than configuration files.

Remark: 
- may be also for the remaining Operation environment variables as tls configuraition
- I observed similar for peer and orderer Operating ListenAddress but not yet tested in details as for CA.

### Steps to reproduce

Create a Docker container with the Fabric-CA server image.
Set the FABRIC_CA_OPERATIONS_LISTENADDRESS environment variable to 0.0.0.0:7049.
Observe that the server still defaults to the listen address defined in fabric-ca-server-config.yaml, not the specified environment variable.
Expected Behavior: The server should bind to the address specified by the FABRIC_CA_OPERATIONS_LISTENADDRESS environment variable, as it should override the configuration file.

Actual Behavior: The server ignores the FABRIC_CA_OPERATIONS_LISTENADDRESS environment variable and instead uses the address in fabric-ca-server-config.yaml.

Proposed Workaround: To work around this issue, I currently modify the fabric-ca-server-config.yaml directly and re-starting the server to ensure the correct listen address is set.

**Comment by Jenziner** [comment]
Ok, this should be in CA-Repo, but check it also for peer and orderer, as I had the same troubles there.

**Comment by Jenziner** [comment]
Based on what I found in the Hyperledger Fabric source code documentation, the environment variable settings for the operations port behave similarly for both the peer and the orderer nodes. For both components, the configurations in the core.yaml (for the peer) and orderer.yaml (for the orderer) files take precedence over environment variables in certain instances. This behavior aligns with my observations about the CA server.

Here’s the key insight: when setting the operations port via an environment variable, the peer and orderer components may revert to the default settings found in their respective configuration files, even when the environment variables are set. This suggests that, as with the CA server, the configurations are likely read first from the config files, and the operations port environment variables may not be directly overriding these.

**Comment by denyeart** [comment]
I've confirmed that the environment variable overrides work correctly.

For Fabric CA this works:

```
export FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=127.0.0.1:8446
./fabric-ca-server start

curl -X GET http://127.0.0.1:8446/healthz
{"status":"OK","time":"2024-10-09T17:11:02.108443-04:00"}
```

I think you had the environment variable name incorrect. You can also see the override working in test network here:

https://github.com/hyperledger/fabric-samples/blob/main/test-network/compose/compose-ca.yaml#L23

I've also confirmed it works for peer, see the test network override here:

https://github.com/hyperledger/fabric-samples/blob/main/test-network/compose/compose-test-net.yaml#L85

The peer also outputs the entire config in the log, using the core.yaml plus environment variable overrides, for example:

```
INFO [nodeCmd] serve -> Peer config with combined core.yaml settings and environment variable overrides:
...
operations:
  listenaddress: 127.0.0.1:8446
...
```

**Comment by Jenziner** [comment]
Oh dear - deer... You got me. As you can see, I forgot the word "SERVER" in the name. Sorry and thanks for the learning unit
