### ISSUE TITLE
vendor directory

### ISSUE THREAD

**Issue by pfi79** [hyperledger/fabric#5037]
### Current Status

Currently there is a vendor folder

I have a question: why is it needed?

It is written in the documentation for [vendoring](https://go.dev/ref/mod#vendoring): 
```
Vendoring may be used to allow interoperation with older versions of Go, or to ensure that all files used for a build are stored in a single file tree.
```

After trying to update github.com/prometheus/client_golang, the peer and orderer programs in docker stopped building. However, if the vendor folder is removed, everything builds fine. 

### Goal

It seems to me that this is already redundant in the fabric project. 
And it can be deleted.

### Solution

Try deleting the vendor folder and check that no functionality has fallen off.

**Comment by C0rWin** [comment]
> After trying to update github.com/prometheus/client_golang, the peer and orderer programs in docker stopped building. However, if the vendor folder is removed, everything builds fine.

Can you put here an error?

**Comment by pfi79** [comment]
> > After trying to update github.com/prometheus/client_golang, the peer and orderer programs in docker stopped building. However, if the vendor folder is removed, everything builds fine.
> 
> Can you put here an error?

https://github.com/hyperledger/fabric/pull/5032

https://github.com/hyperledger/fabric/issues/4052

```
vendor/github.com/prometheus/client_golang/prometheus/registry.go:62:15: undefined: NewGoCollector
```

a command that causes an error

```
make docker
```
