### ISSUE TITLE
Something is wrong, in the Chinese documentation

### ISSUE THREAD

**Issue by pipi0960** [hyperledger/fabric#5046]
### Description

Something is wrong, in the [https://hyperledger-fabric.readthedocs.io/zh-cn/latest/deploy_chaincode.html](Chinese documentation)
![image](https://github.com/user-attachments/assets/6a268b82-ba8e-4541-b0b9-034b62590ecc)

**Comment by denyeart** [comment]
The translated docs are maintained in https://github.com/hyperledger/fabric-docs-i18n. Please open an issue or pull request over in that repository.
