### ISSUE TITLE
failed constructing descriptor for chaincodes

### ISSUE THREAD

**Issue by ghost** [hyperledger/fabric#5062]
Hello all,

Versions
- Peers / orderers: 2.5.9
- Fabric CA: 1.5.12

I have the following hyperledger fabric setup:
- 2 Orgs, 1 peer each
- 4 Orderer nodes in etcraft fashion
- 2 NodeJS clietns for Org 1 with load balancer in front of them
- 7 Java chaincodes installed using chaincode as a service deployment fashion

I can use the client using APIs that I implemented to submit transaction and evaluate transaction on all the chaincodes.
I can submit transactions for all chaincodes except for chaincode with the following name "DigitalRegistryContracts"

I get this error from the client when I try to call any API that uses the "DigitalRegistryContracts" contract to communicate with the chaincode

{
  "error": "DiscoveryService: DigitalRegistryContracts error: failed constructing descriptor for chaincodes:{name:\"DigitalRegistryContracts\"}",
  "stack": "Error: DiscoveryService: DigitalRegistryContracts error: failed constructing descriptor for chaincodes:{name:\"DigitalRegistryContracts\"}\n at DiscoveryResultsProcessor.parseDiscoveryResults (/usr/src/app/node_modules/fabric-common/lib/DiscoveryResultsProcessor.js:31:11)\n at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n at async DiscoveryService.send (/usr/src/app/node_modules/fabric-common/lib/DiscoveryService.js:341:19)\n at async ContractImpl.newDiscoveryService (/usr/src/app/node_modules/fabric-network/lib/contract.js:281:9)\n at async ContractImpl.getDiscoveryHandler (/usr/src/app/node_modules/fabric-network/lib/contract.js:258:25)\n at async Transaction.submit (/usr/src/app/node_modules/fabric-network/lib/transaction.js:236:43)\n at async /usr/src/app/app.js:425:18"
}

Can anyone help me please.

Thanks,

**Comment by bestbeforetoday** [comment]
I think that this client-side error can occur if an incorrect discovery interest is configured with the legacy Node SDK. See the[ tutorial on using the discovery service](https://hyperledger.github.io/fabric-sdk-node/main/tutorial-discovery-fabric-network.html) for details. I don't know if this is the cause in your case. The peer logs might contain more information about the error.

While it should work with Fabric 2.5, the legacy Node SDK is no longer supported. You really should be using the [Fabric Gateway client API](https://hyperledger.github.io/fabric-gateway/) instead. In most cases the newer client API automatically handles [endorsement using collections and chaincode-to-chaincode calls](https://hyperledger.github.io/fabric-gateway/migration/#endorsement-requirements) correctly.

**Comment by ghost** [comment]
Hi @bestbeforetoday ,

Thank you for your response, I have applied the changes you suggested and used the Fabric Gateway client API. But when I started the client I got the below issue from the client docker container.
Logs:
******** FAILED to run the application: EndorseError: 10 ABORTED: failed to endorse transaction, see attached details for more info

As you can see no attached details to the logs.
Note that my blockchain network is running using docker swarm.

Thanks,

**Comment by bestbeforetoday** [comment]
Have a look at the [asset-transfer-basic/application-gateway-go](https://github.com/hyperledger/fabric-samples/blob/1aa382278823126c3f5cbe7cf1053227b7dca514/asset-transfer-basic/application-gateway-go/assetTransfer.go#L241-L287) sample in the fabric-samples repository for an example of accessing the associated error details. The (Gateway) peer logs should also contain information on the error.

Edit: Sorry, I linked to the Go sample. With Node you should see any associated error details if you write the whole error (not just the message) to the console: `console.log(err)` or `console.error(err)`, as in the [Node asset-transfer-basic](https://github.com/hyperledger/fabric-samples/blob/1aa382278823126c3f5cbe7cf1053227b7dca514/asset-transfer-basic/application-gateway-typescript/src/app.ts#L209-L225) sample. If you want to access the details directly, they are in a `details` property on the [EndorseError](https://hyperledger.github.io/fabric-gateway/main/api/node/classes/EndorseError.html).

**Comment by ghost** [comment]
Hi @bestbeforetoday 

I fixed the issue above but now I still get an error when trying to communicate with the "DigitalRegistryContracts" chaincode.

{
  "error": "9 FAILED_PRECONDITION: no combination of peers can be derived which satisfy the endorsement policy: No metadata was found for chaincode DigitalRegistryContracts in channel contractschannel",
  "stack": "EndorseError: 9 FAILED_PRECONDITION: no combination of peers can be derived which satisfy the endorsement policy: No metadata was found for chaincode DigitalRegistryContracts in channel contractschannel\n at /usr/src/app/node_modules/@hyperledger/fabric-gateway/dist/client.js:37:253\n at Object.callback (/usr/src/app/node_modules/@hyperledger/fabric-gateway/dist/client.js:102:20)\n at Object.onReceiveStatus (/usr/src/app/node_modules/@grpc/grpc-js/build/src/client.js:193:36)\n at Object.onReceiveStatus (/usr/src/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:360:141)\n at Object.onReceiveStatus (/usr/src/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)\n at /usr/src/app/node_modules/@grpc/grpc-js/build/src/resolving-call.js:129:78\n at process.processTicksAndRejections (node:internal/process/task_queues:85:11)"
}

Thanks,

**Comment by bestbeforetoday** [comment]
This message typically occurs when the requested chaincode is not successfully committed and running on the channel.

**Comment by ghost** [comment]
Hi @bestbeforetoday 

yes I found that this chaincode was not installed "also all the chaincodes are installed using script" might a timeout or something failed in the middle of the deployment of the chaincode. However I reinstalled it again, and finally I was able to communicate with the chaincode.
Thanks a lot for your effort and time.
