### ISSUE TITLE
Insecure dependencies detection (critical and high severity)

### ISSUE THREAD

**Issue by SbruiceS** [hyperledger/fabric#5066]
### Description

example - core/chaincode/platforms/golang/testdata/ccmodule/
go.mod

**Comment by bestbeforetoday** [comment]
Security vulnerability scans are run daily on the actual module code to detect known vulnerabilities in dependencies, and these scans are currently passing. Please could you provide more detail on the specific dependency and vulnerability that you see?

You cite test fixtures as having vulnerable dependencies. For code used only as test artefacts, I'm not sure I see a concern.

**Comment by SbruiceS** [comment]
go version differences ccaas-builder/go.mod line 3 - go 1.16  this one CVE 2022 32148 update to 1.17.12 in other code go.mod is 1.22 which one is CVE 2024 24784 so it's should update to 1.22.1 . And go 1.13 should 1.18.7

**Comment by SbruiceS** [comment]
Bypass-tls-verification 

gossip/comm/comm_test.go code line 1003 - this should only be used for debugging purpose Because it's leads to vulnerabilities to MTM attacks so that's why tlscCfg:=&tls.Config{ should defines Minversion.

**Comment by SbruiceS** [comment]
And orderer/mocks/utils/utils.go line 21 there RSA should 2048 as on 1024.

**Comment by bestbeforetoday** [comment]
> go version differences ccaas-builder/go.mod line 3 - go 1.16 this one CVE 2022 32148 update to 1.17.12 in other code go.mod is 1.22 which one is CVE 2024 24784 so it's should update to 1.22.1 . And go 1.13 should 1.18.7

These are minimum compatible Go versions. They do not mandate the Go version used at runtime. You are highlighting vulnerabilities within the Go standard libraries, which are dependent on the version of Go used at runtime, not the minimum compatible version listed in the go.mod file.

**Comment by bestbeforetoday** [comment]
> Bypass-tls-verification
> 
> gossip/comm/comm_test.go code line 1003 - this should only be used for debugging purpose Because it's leads to vulnerabilities to MTM attacks so that's why tlscCfg:=&tls.Config{ should defines Minversion.

This is test code.

**Comment by bestbeforetoday** [comment]
> And orderer/mocks/utils/utils.go line 21 there RSA should 2048 as on 1024.

This is a mock used only by tests.

**Comment by denyeart** [comment]
For building the peer, go 1.23.4 is currently recommended per https://github.com/hyperledger/fabric/blob/main/go.mod#L3.

Agree with the comments from @bestbeforetoday , I'll go ahead and close.
