### ISSUE TITLE
grpc-client-new-insecure-connection

### ISSUE THREAD

**Issue by SbruiceS** [hyperledger/fabric#5067]
### Description

internal/peer/node/start.go

Found an insecure gRPC connection using insecure.NewCredentials(). This creates a connection without encryption to a gRPC server. A malicious attacker could tamper with the gRPC message, which could compromise the machine. Instead, establish a secure connection with an SSL certificate using the grpc.WithTransportCredentials() function. You can create a create credentials using a tls.Config{} struct with credentials.NewTLS(). The final fix looks like this: grpc.WithTransportCredentials(credentials.NewTLS(<config>)).

References

    https://owasp.org/Top10/A07_2021-Identification_and_Authentication_Failures

**Comment by bestbeforetoday** [comment]
The insecure connection is only used if TLS is explicitly disabled by user configuration.

**Comment by denyeart** [comment]
Production deployments utilize TLS. The insecure.NewCredentials() is a fallback for test environments if "peer.tls.enabled" is not set. Since this is an intentional config option, and the docs and samples are pretty clear that TLS should be configured, I'll go ahead and close.
