### ISSUE TITLE
The ordering nodes panic during synchronization.

### ISSUE THREAD

**Issue by w4z5** [hyperledger/fabric#5076]
### Description

I have deployed a consensus cluster with 10 orderer nodes in Hyperledger Fabric version 3.0.0-beta. Among these, orderer8, orderer9, and orderer10 are randomly started and stopped. During the experiment, I repeatedly use `docker stop` and `docker start` commands to stop and start these nodes. At any given time, only one node is stopped, with a downtime of 2 minutes, and a recovery time of 5 minutes after it is started again. During the experiment, the following panic occurs during the node recovery phase.
![Image](https://github.com/user-attachments/assets/7d9f789f-fec7-46ce-a713-c03e866ffce2)
Upon reviewing the logs of orderer9, I found the following two log entries:

> 2024-11-09 09:06:46.618 UTC 164fa DEBU [orderer.consensus.smartbft.chain] getBlocksFromSyncBuffer -> Fetched and committed block [223] from cluster channel=channel1
> 2024-11-09 09:06:46.896 UTC 168b5 DEBU [orderer.consensus.smartbft.chain] getBlocksFromSyncBuffer -> Will fetch sequences [223-236] channel=channel1

Even after block 223 was committed, it was still selected as a block to synchronize. When the node attempted to submit block 223 again, a panic occurred.
Could the developers please help assess if such a panic represents a security risk in Fabric? I would appreciate any insights on this

**Comment by bestbeforetoday** [comment]
Do you see better behaviour using the v3.0.0 release version instead of the 3.0.0-beta?

**Comment by pfi79** [comment]
A few clarifying questions:
- What does `recovery time of 5 minutes after it is started again`, please specify.
- Is it the same on 7 knots with stop 7 and 6 or on 4 knots
- What load is applied to the fabric
- What happens to the node after a panic, does it remain inoperable or does it recover after some time and work normally

**Comment by pfi79** [comment]
It would also be my wish, if possible: 
- Reduce the number of nodes to 7 or 4 and have the error repeat.
- put order logs in "debug" for fabric and smart-bft, and when the error repeats, all orderers logs in different files should be archived and attached to the discussion.

**Comment by w4z5** [comment]
> A few clarifying questions:
> 
> * What does `recovery time of 5 minutes after it is started again`, please specify.
> * Is it the same on 7 knots with stop 7 and 6 or on 4 knots
> * What load is applied to the fabric
> * What happens to the node after a panic, does it remain inoperable or does it recover after some time and work normally

**Comment by w4z5** [comment]
> A few clarifying questions:
> 
> * What does `recovery time of 5 minutes after it is started again`, please specify.
> * Is it the same on 7 knots with stop 7 and 6 or on 4 knots
> * What load is applied to the fabric
> * What happens to the node after a panic, does it remain inoperable or does it recover after some time and work normally

1. I used the following script to operate the nodes.
```shell
#!/bin/bash

CONTAINERS=("orderer8.example.com" "orderer9.example.com" "orderer10.example.com")
while true; do
  # Randomly select a container
  RANDOM_INDEX=$((RANDOM % ${#CONTAINERS[@]}))
  SELECTED_CONTAINER=${CONTAINERS[$RANDOM_INDEX]}

  echo "$(date): STOP CONTAINER $SELECTED_CONTAINER"
  docker stop "$SELECTED_CONTAINER"

  # Wait for 2 minutes before restarting
  sleep 120

  echo "$(date): RESTART CONTAINER $SELECTED_CONTAINER"
  docker start "$SELECTED_CONTAINER"

  # Wait for 5 minutes before the next round of operations
  sleep 300
done
```
2. I will conduct this experiment later.
3. I used the `asset-transfer-basic/application-gateway-go` example from [fabric-samples](https://github.com/hyperledger/fabric-samples) to repeatedly send createAsset transactions, sending one transaction per second.
4. The nodes do not automatically recover; the `docker start` command is used to restart the nodes.
5. The log files generated by the nodes during operation are as follows:
    [logs.zip](https://github.com/user-attachments/files/18160640/logs.zip)

**Comment by pfi79** [comment]
> > A few clarifying questions:
> > 
> > * What does `recovery time of 5 minutes after it is started again`, please specify.
> > * Is it the same on 7 knots with stop 7 and 6 or on 4 knots
> > * What load is applied to the fabric
> > * What happens to the node after a panic, does it remain inoperable or does it recover after some time and work normally
> 
> 1. I used the following script to operate the nodes.
> 
> #!/bin/bash
> 
> CONTAINERS=("orderer8.example.com" "orderer9.example.com" "orderer10.example.com")
> while true; do
>   # Randomly select a container
>   RANDOM_INDEX=$((RANDOM % ${#CONTAINERS[@]}))
>   SELECTED_CONTAINER=${CONTAINERS[$RANDOM_INDEX]}
> 
>   echo "$(date): STOP CONTAINER $SELECTED_CONTAINER"
>   docker stop "$SELECTED_CONTAINER"
> 
>   # Wait for 2 minutes before restarting
>   sleep 120
> 
>   echo "$(date): RESTART CONTAINER $SELECTED_CONTAINER"
>   docker start "$SELECTED_CONTAINER"
> 
>   # Wait for 5 minutes before the next round of operations
>   sleep 300
> done
> 2. I will conduct this experiment later.
> 3. I used the `asset-transfer-basic/application-gateway-go` example from [fabric-samples](https://github.com/hyperledger/fabric-samples) to repeatedly send createAsset transactions, sending one transaction per second.
> 4. The nodes do not automatically recover; the `docker start` command is used to restart the nodes.
> 5. The log files generated by the nodes during operation are as follows:
>    [logs.zip](https://github.com/user-attachments/files/18160640/logs.zip)

thank you. yeah, it's a bug in the fabric.
I'll figure out how to fix it.

**Comment by yacovm** [comment]
In the meantime can you perhaps try and set [this](https://github.com/hyperledger/fabric/blob/main/sampleconfig/orderer.yaml#L128) configuration parameter to "simple"? it should solve your problem in the short term.

**Comment by pfi79** [comment]
@w4z5 wait for the new release.

**Comment by pfi79** [comment]
@w4z5 By the way, you don't have to wait, you can use the `make docker` command to build the images yourself and continue your research
